const f = (id, label, type = "text", options = {}) => ({ id, label, type, ...options });
const commonPatient = [
  f("patientId", "Patient / scenario ID", "text", { required: true }),
  f("dateTime", "Assessment date and time", "datetime-local", { required: true }),
];

export const CLINICAL_FORM_CATEGORIES = [
  { id: "assessment", label: "Assessment & admission" },
  { id: "risk", label: "Risk & safety" },
  { id: "nutrition", label: "Nutrition & fluid balance" },
  { id: "skin", label: "Skin integrity & wounds" },
  { id: "neurology", label: "Neurological observations" },
  { id: "medicines", label: "Medicines safety" },
  { id: "communication", label: "Communication & care records" },
];

export const CLINICAL_FORM_TEMPLATES = {
  admission: {
    title: "Patient Admission Record", short: "Admission", category: "assessment",
    description: "Complete a structured, person-centred admission and identify immediate priorities.",
    source: "Patient Admission Form", skCodes: ["SK1", "SK4", "SK9", "SK18"], poCodes: ["PO3", "PO5", "PO9"],
    pearson: ["Supporting Healthcare PO1 — safe working practices", "Supporting Healthcare PO2 — overall care, comfort and wellbeing"],
    guidance: ["Verify identity using approved identifiers.", "Record allergies and reactions before medicines-related activity.", "Escalate urgent concerns without waiting for form completion."],
    fields: [...commonPatient,
      f("preferredName", "Preferred name and pronouns", "text", { required: true }),
      f("dob", "Date of birth", "date", { required: true }),
      f("reason", "Source and reason for admission", "textarea", { required: true }),
      f("nextOfKin", "Next of kin / contact"),
      f("consent", "Consent to share information", "select", { options: ["Confirmed", "Declined", "Unable to confirm — escalate"], required: true }),
      f("communication", "Communication, accessibility or interpreter needs", "textarea"),
      f("allergies", "Allergies and reaction", "textarea", { required: true }),
      f("history", "Relevant clinical history", "textarea"),
      f("medicines", "Medicines reconciliation status", "select", { options: ["Completed", "In progress", "Not started — escalate"], required: true }),
      f("baseline", "Baseline observations / NEWS2", "textarea", { required: true }),
      f("priorities", "Immediate risks and care priorities", "textarea", { required: true }),
    ],
  },
  generalRisk: {
    title: "General Risk Assessment", short: "General risk", category: "risk",
    description: "Identify hazards, existing controls and proportionate further action.",
    source: "General Risk Assessment / Identifying Risk", skCodes: ["SK4", "SK7", "SK18"], poCodes: ["PO2", "PO4", "PO9"],
    pearson: ["Supporting Healthcare PO1 — maintain a safe environment", "Therapy Teams PO3 — safe environment, equipment and resources"],
    guidance: ["Risk score is calculated as likelihood × severity.", "Immediate danger must be controlled and escalated first."],
    calculator: "risk",
    fields: [
      f("assessmentTitle", "Assessment title", "text", { required: true }), f("location", "Location", "text", { required: true }),
      f("hazard", "Hazard", "textarea", { required: true }), f("people", "Who may be harmed and how", "textarea", { required: true }),
      f("controls", "Existing controls", "textarea", { required: true }),
      f("likelihood", "Likelihood (1–5)", "number", { min: 1, max: 5, required: true }),
      f("severity", "Severity (1–5)", "number", { min: 1, max: 5, required: true }),
      f("furtherAction", "Further action required", "textarea"), f("owner", "Action owner / due date"),
      f("residualRisk", "Residual risk and review outcome", "textarea"),
    ],
  },
  coshh: {
    title: "COSHH Assessment", short: "COSHH", category: "risk",
    description: "Assess hazardous substances using the supplier safety data sheet and local controls.",
    source: "COSHH Assessment Sheet", skCodes: ["SK4", "SK7", "SK18"], poCodes: ["PO2", "PO4"],
    pearson: ["Supporting Healthcare PO1 — safe working practices and environment"],
    guidance: ["Use the current supplier safety data sheet.", "Never infer exposure limits or PPE from product colour or packaging."],
    fields: [
      f("product", "Substance / product", "text", { required: true }), f("sdsDate", "Supplier / SDS date", "text", { required: true }),
      f("task", "Task and location", "textarea", { required: true }), f("hazards", "Hazard classification", "textarea", { required: true }),
      f("exposed", "Who may be exposed", "textarea"), f("routes", "Routes of exposure", "textarea"),
      f("frequency", "Quantity and frequency"), f("controls", "Existing controls", "textarea", { required: true }),
      f("ppe", "Required PPE", "textarea"), f("storage", "Storage / segregation", "textarea"),
      f("spill", "Spill and emergency response", "textarea", { required: true }), f("firstAid", "First aid", "textarea"),
      f("disposal", "Disposal arrangements", "textarea"), f("residualRisk", "Residual risk / review date", "textarea"),
    ],
  },
  mobility: {
    title: "Mobility & Falls Assessment", short: "Mobility", category: "risk",
    description: "Record current mobility, falls factors, equipment and the safe assistance plan.",
    source: "Patient Mobility Assessment", skCodes: ["SK4", "SK9", "SK15"], poCodes: ["PO5", "PO6", "PO10"],
    pearson: ["Adult Nursing PO2 — support activities of daily living", "Supporting Healthcare PO2 — comfort and wellbeing"],
    guidance: ["Assess function, cognition, medicines, continence, vision, footwear and environment.", "Use the locally approved falls tool when required."],
    fields: [...commonPatient,
      f("baselineMobility", "Baseline mobility", "textarea"), f("currentMobility", "Current mobility", "textarea", { required: true }),
      f("transfers", "Transfers and assistance level", "textarea", { required: true }), f("equipment", "Walking aid / equipment"),
      f("gait", "Balance, gait and strength", "textarea"), f("cognition", "Cognition and insight", "textarea"),
      f("sensory", "Vision and hearing"), f("postural", "Postural symptoms / pain", "textarea"),
      f("continence", "Continence / urgency"), f("footwear", "Footwear and feet"),
      f("medicines", "Medicine-related concerns", "textarea"), f("falls", "Falls history", "textarea"),
      f("environment", "Environmental risks", "textarea"), f("plan", "Safe mobility plan, referral and review", "textarea", { required: true }),
    ],
  },
  movingHandling: {
    title: "Moving & Handling Risk Assessment", short: "Moving & handling", category: "risk",
    description: "Plan a safe movement using task, individual, load and environment factors.",
    source: "Moving and Handling Risk Assessment", skCodes: ["SK4", "SK9", "SK15"], poCodes: ["PO2", "PO5", "PO10"],
    pearson: ["Supporting Healthcare PO1 — safe working practices", "Adult Nursing PO2 — activities of daily living"],
    guidance: ["Avoid hazardous manual handling where reasonably practicable.", "Use trained staff and checked equipment within role boundaries."],
    fields: [...commonPatient,
      f("task", "Movement / transfer task", "textarea", { required: true }), f("individual", "Individual capability and participation", "textarea", { required: true }),
      f("load", "Load / person factors", "textarea"), f("environment", "Environment", "textarea"),
      f("equipment", "Equipment required and checks", "textarea", { required: true }), f("staff", "Number and competence of staff", "text", { required: true }),
      f("communication", "Communication and consent plan", "textarea"), f("pain", "Pain, fatigue or behaviour considerations", "textarea"),
      f("method", "Safe handling method", "textarea", { required: true }), f("emergency", "Emergency / fall response", "textarea"),
      f("review", "Review triggers", "textarea"),
    ],
  },
  bmi: {
    title: "BMI Calculation & Context", short: "BMI", category: "nutrition",
    description: "Calculate BMI and document clinical context, limitations and actions.",
    source: "BMI Chart", skCodes: ["SK1", "SK5", "SK18"], poCodes: ["PO4", "PO6", "PO9"],
    pearson: ["Supporting Healthcare PO3 — routine clinical tasks", "Supporting Healthcare PO2 — health and wellbeing"],
    calculator: "bmi",
    guidance: ["BMI = weight (kg) ÷ height² (m).", "BMI alone does not diagnose nutritional status; interpret in clinical context."],
    fields: [...commonPatient,
      f("height", "Height (m)", "number", { min: 0.5, max: 2.5, step: 0.01, required: true }),
      f("weight", "Weight (kg)", "number", { min: 1, max: 400, step: 0.1, required: true }),
      f("limitations", "Relevant limitations / context", "textarea"), f("action", "Action or referral", "textarea", { required: true }),
    ],
  },
  must: {
    title: "MUST Recording Worksheet", short: "MUST", category: "nutrition",
    description: "Record results from the authorised BAPEN MUST tool and create an action plan.",
    source: "Universal Malnutrition Screening Tool", skCodes: ["SK4", "SK5", "SK18"], poCodes: ["PO4", "PO6", "PO9"],
    pearson: ["Supporting Healthcare PO2 — overall care and wellbeing", "Supporting Healthcare PO3 — routine tasks"],
    guidance: ["Use the authorised BAPEN MUST tool to assign scores.", "This workspace records the result and does not reproduce the copyrighted scoring tool."],
    calculator: "must",
    fields: [...commonPatient,
      f("height", "Height (m)", "number", { step: 0.01 }), f("weight", "Current weight (kg)", "number", { step: 0.1, required: true }),
      f("previousWeight", "Previous weight (kg)", "number", { step: 0.1 }), f("bmiScore", "BMI score from official tool", "number", { min: 0, max: 2, required: true }),
      f("weightLossScore", "Weight-loss score from official tool", "number", { min: 0, max: 2, required: true }),
      f("acuteScore", "Acute disease effect score", "number", { min: 0, max: 2, required: true }),
      f("riskCategory", "Risk category from official tool", "select", { options: ["Low", "Medium", "High"], required: true }),
      f("action", "Action / care plan", "textarea", { required: true }),
    ],
  },
  fluid: {
    title: "Fluid Balance Chart", short: "Fluid balance", category: "nutrition",
    description: "Record measurable input and output with automatic cumulative totals.",
    source: "Fluid Balance", skCodes: ["SK5", "SK18"], poCodes: ["PO4", "PO6", "PO9"],
    pearson: ["Supporting Healthcare PO3 — routine clinical tasks", "Adult Nursing PO1 — clinical tasks"],
    calculator: "fluid",
    guidance: ["Record measurable amounts in millilitres.", "Use the current care plan for targets, restrictions and escalation."],
    fields: [...commonPatient,
      f("target", "Fluid target / restriction", "text"), f("carryForward", "Carry-forward balance (ml)", "number"),
      f("oral", "Oral input (ml)", "number"), f("enteral", "Enteral input (ml)", "number"), f("iv", "IV input (ml)", "number"), f("otherInput", "Other input (ml)", "number"),
      f("urine", "Urine output (ml)", "number"), f("vomit", "Vomit (ml)", "number"), f("drain", "Drain / stoma (ml)", "number"), f("otherOutput", "Other output (ml)", "number"),
      f("notes", "Clinical notes and escalation", "textarea", { required: true }),
    ],
  },
  braden: {
    title: "Braden Pressure-Risk Record", short: "Braden", category: "skin",
    description: "Record component scores from an authorised Braden Scale and the prevention plan.",
    source: "Braden Scale", skCodes: ["SK4", "SK15", "SK18"], poCodes: ["PO4", "PO6", "PO10"],
    pearson: ["Adult Nursing PO3 — skin integrity assessment and care"],
    guidance: ["Use an authorised Braden Scale and clinical judgement.", "Record the component scores and prevention actions; do not rely on score alone."],
    calculator: "sum",
    fields: [...commonPatient,
      ...["Sensory perception","Moisture","Activity","Mobility","Nutrition","Friction and shear"].map((label, index) => f(`score${index + 1}`, `${label} score from authorised scale`, "number", { min: 1, max: 4, required: true })),
      f("judgement", "Clinical risk judgement", "textarea", { required: true }), f("actions", "Preventive actions", "textarea", { required: true }), f("review", "Review date / time", "datetime-local"),
    ],
  },
  waterlow: {
    title: "Waterlow Score Record", short: "Waterlow", category: "skin",
    description: "Record authorised Waterlow scores and create a prevention plan.",
    source: "Waterlow Score Assessment", skCodes: ["SK4", "SK15", "SK18"], poCodes: ["PO4", "PO6", "PO10"],
    pearson: ["Adult Nursing PO3 — skin integrity assessment and treatment support"],
    guidance: ["Use an authorised Waterlow tool and clinical judgement.", "This record does not reproduce the proprietary scoring criteria."],
    calculator: "sum",
    fields: [...commonPatient,
      ...["Build / BMI","Skin type / visual risk","Sex / age","Continence","Mobility","Nutrition screening","Tissue malnutrition","Neurological deficit","Major surgery / trauma","Medication"].map((label, index) => f(`score${index + 1}`, `${label} score from authorised tool`, "number", { min: 0, max: 20, required: true })),
      f("judgement", "Clinical risk judgement", "textarea", { required: true }), f("plan", "Prevention plan and review date", "textarea", { required: true }),
    ],
  },
  skinCheck: {
    title: "Pressure Area Daily Check", short: "Pressure areas", category: "skin",
    description: "Document systematic skin inspection and pressure-relief care.",
    source: "Pressure Area Daily Check", skCodes: ["SK4", "SK15", "SK18"], poCodes: ["PO5", "PO6", "PO10"],
    pearson: ["Adult Nursing PO3 — skin integrity assessments and care"],
    guidance: ["Assess colour changes across all skin tones, heat, firmness, moisture, pain and integrity.", "Escalate non-blanching erythema or deterioration promptly."],
    fields: [...commonPatient,
      f("position", "Current position / repositioning schedule", "textarea", { required: true }),
      f("areas", "Areas checked", "multiselect", { options: ["Occiput / ears","Shoulders / elbows","Spine","Sacrum / coccyx","Hips / ischial areas","Knees / ankles","Heels / toes","Device-contact areas"], required: true }),
      f("findings", "Skin findings", "textarea", { required: true }), f("relief", "Pressure relief / care provided", "textarea"),
      f("response", "Patient response and escalation", "textarea", { required: true }),
    ],
  },
  wound: {
    title: "Wound Assessment", short: "Wound assessment", category: "skin",
    description: "Record an objective wound assessment and treatment / escalation plan.",
    source: "Wound Grading and Classification Assessment", skCodes: ["SK1", "SK4", "SK18"], poCodes: ["PO4", "PO6", "PO10"],
    pearson: ["Adult Nursing PO3 — skin integrity and skin-condition care"],
    guidance: ["Use the locally approved wound classification system.", "Do not reverse-stage healing pressure ulcers."],
    fields: [...commonPatient,
      f("location", "Wound location", "text", { required: true }), f("type", "Wound type / aetiology", "text", { required: true }),
      f("classification", "Classification / category and system used", "text", { required: true }),
      f("length", "Length (cm)", "number", { step: 0.1 }), f("width", "Width (cm)", "number", { step: 0.1 }), f("depth", "Depth (cm)", "number", { step: 0.1 }),
      f("bed", "Wound bed tissue", "textarea"), f("exudate", "Exudate amount / type"), f("edge", "Wound edge and periwound skin", "textarea"),
      f("pain", "Pain assessment"), f("infection", "Infection concerns / escalation", "textarea", { required: true }),
      f("plan", "Dressing / treatment plan", "textarea", { required: true }),
    ],
  },
  gcs: {
    title: "Glasgow Coma Scale Record", short: "GCS", category: "neurology",
    description: "Record GCS components separately with automatic total and change prompt.",
    source: "Glasgow Coma Scale", skCodes: ["SK1", "SK17", "SK18"], poCodes: ["PO4", "PO9", "PO10"],
    pearson: ["Supporting Healthcare PO3 — routine clinical tasks", "Adult Nursing PO1 — clinical tasks"],
    calculator: "gcs",
    guidance: ["Use trained assessment and the approved local GCS chart.", "Record E, V and M separately and escalate deterioration."],
    fields: [...commonPatient,
      f("eye", "Eye response score (E)", "number", { min: 1, max: 4, required: true }),
      f("verbal", "Verbal response score (V)", "number", { min: 1, max: 5, required: true }),
      f("motor", "Motor response score (M)", "number", { min: 1, max: 6, required: true }),
      f("limitations", "Factors limiting assessment", "textarea"), f("change", "Change from previous assessment", "textarea"),
      f("action", "Action / escalation", "textarea", { required: true }),
    ],
  },
  neuro: {
    title: "Neurological Observation Chart", short: "Neuro observations", category: "neurology",
    description: "Record neurological observations, trends and escalation.",
    source: "Neurological Observation Monitoring Chart", skCodes: ["SK1", "SK17", "SK18"], poCodes: ["PO4", "PO9", "PO10"],
    pearson: ["Supporting Healthcare PO3 — routine tasks", "Adult Nursing PO1 — clinical tasks"],
    guidance: ["Trend observations rather than interpreting one value in isolation.", "Escalate deterioration using local policy and SBAR."],
    fields: [...commonPatient,
      f("gcs", "GCS total", "number", { min: 3, max: 15, required: true }), f("pupils", "Pupil size and reaction", "textarea", { required: true }),
      f("limbs", "Limb movement / strength", "textarea"), f("rr", "Respiratory rate", "number"), f("spo2", "SpO₂ (%)", "number"),
      f("pulse", "Pulse", "number"), f("bp", "Blood pressure"), f("temp", "Temperature °C", "number", { step: 0.1 }),
      f("pain", "Pain / headache / nausea", "textarea"), f("trend", "Trend, action and escalation", "textarea", { required: true }),
    ],
  },
  medicines: {
    title: "Medicine Proforma", short: "Medicine proforma", category: "medicines",
    description: "Practise medicine checks, monitoring, communication and consent in simulation.",
    source: "Medicine Proforma", skCodes: ["SK16", "SK18"], poCodes: ["PO4", "PO9", "PO10"],
    pearson: ["Supporting Healthcare PO1 — safe practice", "Adult Nursing PO1 — clinical tasks within scope"],
    guidance: ["Simulation only: not a prescription or administration authority.", "Follow local medicines policy and work under authorised supervision."],
    fields: [...commonPatient,
      f("medicine", "Generic medicine name", "text", { required: true }), f("form", "Form / strength", "text", { required: true }),
      f("indication", "Indication", "textarea", { required: true }), f("dose", "Dose", "text", { required: true }),
      f("route", "Route", "select", { options: ["Oral","Topical","Inhaled","Subcutaneous","Intramuscular","Intravenous","Other — authorised route"], required: true }),
      f("frequency", "Frequency / timing", "text", { required: true }), f("allergies", "Allergies / contraindications", "textarea", { required: true }),
      f("checks", "Student safety checks", "textarea", { required: true }), f("monitoring", "Monitoring required", "textarea"),
      f("information", "Patient information and consent", "textarea"), f("supervisor", "Supervisor feedback", "textarea"),
    ],
  },
  mar: {
    title: "MAR Simulation Record", short: "MAR simulation", category: "medicines",
    description: "Practise documenting a supervised simulated medicine administration or omission.",
    source: "Medication Administration Sheet", skCodes: ["SK16", "SK18"], poCodes: ["PO4", "PO9", "PO10"],
    pearson: ["Supporting Healthcare PO1 — safe practice", "Adult Nursing PO1 — clinical tasks"],
    guidance: ["Simulation only: not a legal medicines record.", "Check person, medicine, dose, route, time, allergies, indication, documentation and response."],
    fields: [...commonPatient,
      f("allergies", "Allergies / sensitivities", "textarea", { required: true }), f("medicine", "Medicine / form", "text", { required: true }),
      f("dose", "Dose", "text", { required: true }), f("route", "Route", "text", { required: true }), f("time", "Scheduled / administration time", "time", { required: true }),
      f("outcome", "Outcome", "select", { options: ["Administered in simulation","Omitted — reason documented","Withheld and escalated"], required: true }),
      f("reason", "Omission / withholding reason or administration notes", "textarea"), f("checks", "Checks completed", "textarea", { required: true }),
      f("supervisor", "Supervisor name / feedback", "textarea", { required: true }),
    ],
  },
  capacity: {
    title: "Mental Capacity Assessment", short: "Mental capacity", category: "communication",
    description: "Practise a decision-specific and time-specific capacity assessment.",
    source: "Mental Capacity Form", skCodes: ["SK8", "SK9", "SK18"], poCodes: ["PO3", "PO5", "PO7"],
    pearson: ["Supporting Healthcare PO2 — person-centred overall care and wellbeing"],
    guidance: ["Presume capacity and take all practicable steps to support decision-making.", "Capacity is decision-specific and time-specific."],
    fields: [...commonPatient,
      f("decision", "Specific decision to be made", "textarea", { required: true }), f("reason", "Why assessment is required", "textarea", { required: true }),
      f("support", "Support provided to aid decision-making", "textarea", { required: true }), f("impairment", "Impairment or disturbance of mind / brain", "textarea"),
      f("understand", "Can understand relevant information? Evidence", "textarea", { required: true }),
      f("retain", "Can retain it long enough? Evidence", "textarea", { required: true }),
      f("weigh", "Can use or weigh it? Evidence", "textarea", { required: true }),
      f("communicate", "Can communicate the decision? Evidence", "textarea", { required: true }),
      f("conclusion", "Capacity conclusion and rationale", "textarea", { required: true }),
    ],
  },
  mdt: {
    title: "MDT Referral", short: "MDT referral", category: "communication",
    description: "Create a concise, lawful and clinically relevant referral.",
    source: "MDT Referral Form", skCodes: ["SK6", "SK10", "SK11", "SK18"], poCodes: ["PO3", "PO4", "PO9"],
    pearson: ["Supporting Healthcare PO2 — overall care needs", "Therapy Teams PO1 — process referral and plan support"],
    guidance: ["Share only necessary information through approved channels.", "Obtain consent or record the lawful basis."],
    fields: [...commonPatient,
      f("service", "Service / discipline requested", "text", { required: true }), f("reason", "Reason for referral", "textarea", { required: true }),
      f("history", "Relevant history", "textarea"), f("assessment", "Current assessment and observations", "textarea", { required: true }),
      f("risks", "Risks / red flags", "textarea", { required: true }), f("communication", "Communication / accessibility needs", "textarea"),
      f("consent", "Consent / lawful basis", "textarea", { required: true }), f("urgency", "Urgency", "select", { options: ["Routine","Soon","Urgent","Immediate escalation"], required: true }),
      f("actions", "Actions already taken", "textarea"), f("outcome", "Response, outcome and plan", "textarea"),
    ],
  },
  incident: {
    title: "Incident Reporting Practice", short: "Incident report", category: "communication",
    description: "Create a factual DATIX-style learning record after immediate safety action.",
    source: "Incident Reporting DATIX", skCodes: ["SK6", "SK7", "SK8", "SK18"], poCodes: ["PO2", "PO3", "PO4"],
    pearson: ["Supporting Healthcare PO1 — safe practice and safe environment"],
    guidance: ["Training template only; real incidents use the organisation’s approved reporting system.", "Take immediate safety action before completing the record."],
    fields: [
      f("dateTime", "Incident date and time", "datetime-local", { required: true }), f("location", "Location", "text", { required: true }),
      f("people", "People involved / affected", "textarea", { required: true }), f("description", "Factual description", "textarea", { required: true }),
      f("immediate", "Immediate action taken", "textarea", { required: true }), f("actualHarm", "Actual harm", "textarea"),
      f("potentialHarm", "Potential harm", "textarea"), f("equipment", "Equipment / medicine details", "textarea"),
      f("witnesses", "Witnesses"), f("informed", "Who was informed", "textarea", { required: true }),
      f("candour", "Duty of candour consideration", "textarea"), f("safeguarding", "Safeguarding / external reporting", "textarea"),
      f("learning", "Learning factors", "textarea"), f("actions", "Further actions, owner and due date", "textarea", { required: true }),
    ],
  },
  careNote: {
    title: "Care Plan Continuation Entry", short: "Care plan entry", category: "communication",
    description: "Record assessment, care delivered, evaluation and a revised person-centred plan.",
    source: "Care Plan Continuation Sheet", skCodes: ["SK3", "SK9", "SK18"], poCodes: ["PO3", "PO5", "PO9"],
    pearson: ["Supporting Healthcare PO2 — overall care and needs", "Employer Set Project — update of a care plan"],
    guidance: ["Entries should be contemporaneous, factual, person-centred and attributable.", "Evaluate response and revise the plan where needed."],
    fields: [...commonPatient,
      f("problem", "Care plan / identified problem", "textarea", { required: true }), f("goal", "Goal / expected outcome", "textarea", { required: true }),
      f("reviewFrequency", "Review frequency", "text", { required: true }), f("assessment", "Assessment and care delivered", "textarea", { required: true }),
      f("evaluation", "Patient response / evaluation", "textarea", { required: true }), f("revisedPlan", "Revised plan", "textarea", { required: true }),
      f("nameRole", "Name and role", "text", { required: true }),
    ],
  },
  salt: {
    title: "SALT Eating, Drinking & Swallowing Record", short: "SALT record", category: "communication",
    description: "Record communication and swallowing needs using current authorised recommendations.",
    source: "Speech and Language Therapy Assessment SALT", skCodes: ["SK5", "SK9", "SK11", "SK18"], poCodes: ["PO5", "PO6", "PO10"],
    pearson: ["Adult Nursing PO2 — activities of daily living", "Therapy Teams PO2 — enable independence"],
    guidance: ["Use current SALT recommendations and the authorised IDDSI Framework.", "Do not change food or drink levels without authorised review."],
    fields: [...commonPatient,
      f("reason", "Reason for referral", "textarea", { required: true }), f("communication", "Communication profile", "textarea"),
      f("concerns", "Swallowing concerns / signs", "textarea", { required: true }), f("positioning", "Positioning / assistance", "textarea"),
      f("drink", "IDDSI drink level from authorised plan (0–4)", "number", { min: 0, max: 4 }), f("food", "IDDSI food level from authorised plan (3–7)", "number", { min: 3, max: 7 }),
      f("evidence", "Testing method / authorised evidence", "textarea"), f("equipment", "Equipment / utensils"),
      f("oralCare", "Oral care", "textarea"), f("plan", "Shared decision, escalation and referral plan", "textarea", { required: true }),
    ],
  },
  inventory: {
    title: "Patient Property Inventory", short: "Property inventory", category: "assessment",
    description: "Document simulated patient belongings and valuables handling.",
    source: "Patient Inventory Form", skCodes: ["SK9", "SK18"], poCodes: ["PO3", "PO5"],
    pearson: ["Supporting Healthcare PO1 — safe practice", "Supporting Healthcare PO2 — person-centred care"],
    guidance: ["Use for simulated belongings only.", "Follow local policy for valuables, medicines and witnessed transfers."],
    fields: [...commonPatient,
      f("ward", "Ward / area"), f("completedWith", "Inventory completed with", "text", { required: true }),
      f("items", "Items, quantity and condition", "textarea", { required: true }), f("location", "Kept with patient / stored / sent home", "textarea", { required: true }),
      f("valuables", "Valuables handling / receipt number", "textarea"), f("witness", "Patient / witness and staff initials", "text", { required: true }),
    ],
  },
  respect: {
    title: "ReSPECT Conversation Learning Record", short: "ReSPECT learning", category: "communication",
    description: "Reflect on a person-centred emergency-care planning conversation in simulation.",
    source: "Patient Respect Learning Form", skCodes: ["SK6", "SK8", "SK9", "SK12"], poCodes: ["PO5", "PO7", "PO9"],
    pearson: ["Supporting Healthcare PO2 — individual’s overall care and wellbeing"],
    guidance: ["Training record only; it is not the official ReSPECT form.", "Use authorised documentation and trained conversation processes in practice."],
    fields: [...commonPatient,
      f("matters", "What matters to the person", "textarea", { required: true }), f("context", "Relevant clinical context", "textarea"),
      f("preferences", "Understanding and preferences", "textarea", { required: true }), f("support", "Communication support / people involved", "textarea"),
      f("goals", "Agreed goals of care", "textarea", { required: true }), f("recommendations", "Emergency treatment recommendations discussed", "textarea"),
      f("capacity", "Capacity / representative considerations", "textarea"), f("review", "Uncertainties / review triggers", "textarea"),
      f("reflection", "Student reflection", "textarea", { required: true }),
    ],
  },
};

export const getClinicalForm = (id) => CLINICAL_FORM_TEMPLATES[id] || null;

export const getClinicalForms = () => Object.entries(CLINICAL_FORM_TEMPLATES).map(([id, form]) => ({ id, ...form }));
