export const ESP_CASES = [
  {
    id: "practice-amira-khan",
    name: "Amira Khan",
    age: 58,
    pronouns: "she/her",
    setting: "Community respiratory service following recent hospital discharge",
    summary: "Respiratory health, confidence with self-management and safe community follow-up.",
    theme: "Respiratory care",
    employerBrief: "Prepare evidence-based recommendations that help the multidisciplinary team support Amira's respiratory health, independence and confidence with self-management. Communicate with Amira, update her care plan and provide a safe professional handover.",
    baseline: [
      ["Primary condition", "COPD with a recent infective exacerbation"],
      ["Health history", "Hypertension; anxiety associated with breathlessness"],
      ["Current medicines", "Tiotropium inhaler daily; salbutamol inhaler when required; amlodipine 5 mg daily"],
      ["Social context", "Lives alone in a first-floor flat. Her daughter visits twice weekly. She previously attended a local walking group."],
      ["Preferences", "Wants to remain independent and avoid another admission. Prefers information explained without jargon and written down."],
      ["Communication", "English is her second language. She communicates confidently but asks for time to process complex clinical information."],
    ],
    task2Update: [
      ["Individual account", "Amira says she sometimes avoids using salbutamol in public because she feels embarrassed."],
      ["Technique concern", "She is unsure whether she is using both inhalers correctly."],
      ["Wellbeing", "Fear of breathlessness has led her to stop attending the walking group."],
      ["Environment", "She becomes breathless climbing the stairs to her flat and worries about carrying shopping."],
      ["Priority", "Her main goal is to feel confident leaving home independently."],
    ],
    task3Update: [
      ["New observations", "RR 24/min, SpO₂ 92% on air, HR 96 bpm, BP 146/86 mmHg, temperature 37.4°C, alert."],
      ["Clinical change", "Sputum is slightly darker today. Amira reports increased breathlessness since yesterday but can speak in full sentences."],
      ["Existing plan problem", "The current plan states only 'encourage exercise' and 'use inhalers as prescribed'; it contains no measurable outcomes, technique review, escalation thresholds or named responsibilities."],
      ["Required review", "Address inhaler technique, symptom monitoring, safe activity, anxiety, social participation and escalation."],
    ],
    task4Update: [
      ["Handover audience", "Community respiratory nurse receiving responsibility for follow-up."],
      ["Immediate requirement", "Communicate the recent respiratory change, observations, agreed plan and threshold for urgent escalation."],
      ["Professional question focus", "Evidence selection, rejected alternatives, person-centred decisions, risk management and limitations."],
    ],
    roleplayStimulus: "Amira is worried that worsening breathlessness will reduce her independence. She feels previous appointments focused on clinical measurements rather than her priorities. Explore her concerns, clarify what matters to her and agree safe next steps within your role.",
    questionPrompts: "Which respiratory evidence most influenced your recommendations? What alternative did you reject and why? How did Amira's preferences change the plan? What would trigger escalation? What is the main limitation of your final outcome?",
  },
  {
    id: "practice-daniel-owens",
    name: "Daniel Owens",
    age: 46,
    pronouns: "he/him",
    setting: "Primary care diabetes and tissue-viability clinic",
    summary: "Type 2 diabetes, a slow-healing foot wound and support for sustainable self-management.",
    theme: "Diabetes and wound care",
    employerBrief: "Develop recommendations that support safe diabetes self-management, protect Daniel's foot health and reduce avoidable deterioration. Communicate in a non-judgemental way, update the care plan and hand over emerging risks to the diabetes team.",
    baseline: [
      ["Primary condition", "Type 2 diabetes diagnosed six years ago"],
      ["Current concern", "Small plantar wound beneath the right first metatarsal head, present for ten days"],
      ["Health history", "Raised BMI, peripheral neuropathy and hyperlipidaemia"],
      ["Current medicines", "Metformin 1 g twice daily; atorvastatin 20 mg at night"],
      ["Social context", "Works rotating warehouse shifts and cares for his eight-year-old son on alternate weeks."],
      ["Preferences", "Wants practical changes that fit shift work. Dislikes being described as non-compliant."],
    ],
    task2Update: [
      ["Individual account", "Daniel often skips meals on late shifts and buys food from vending machines."],
      ["Foot care", "He checks the wound when reminded but continues wearing steel-toe work boots for long shifts."],
      ["Understanding", "He knows glucose control matters but is unsure how it affects wound healing."],
      ["Barrier", "He fears time off work will affect his income and custody arrangements."],
      ["Priority", "His priority is keeping mobile and remaining at work safely."],
    ],
    task3Update: [
      ["New observations", "Capillary blood glucose 15.8 mmol/L, temperature 37.7°C, HR 94 bpm; wound edge is red with increased exudate."],
      ["Clinical change", "Daniel reports more discomfort despite reduced sensation and noticed an unpleasant odour this morning."],
      ["Existing plan problem", "The plan says 'improve diet' and 'check feet' without wound measurements, monitoring frequency, referrals, responsibilities or escalation criteria."],
      ["Required review", "Address urgent wound review, pressure relief, glucose monitoring, nutrition, medicines support, work adjustments and escalation."],
    ],
    task4Update: [
      ["Handover audience", "Diabetes specialist nurse and tissue-viability service."],
      ["Immediate requirement", "Communicate infection indicators, glycaemic concern, work barriers, agreed actions and urgency."],
      ["Professional question focus", "Risk prioritisation, health inequalities, language choices, evidence and realistic alternatives."],
    ],
    roleplayStimulus: "Daniel expects to be blamed for his glucose level and is defensive about his work routine. Establish rapport, explore the practical barriers affecting meals and foot care, explain risk without alarmist language and agree realistic immediate actions.",
    questionPrompts: "How did you prioritise the wound risk? Which recommendation best reflects Daniel's circumstances? What language did you avoid and why? Which alternative was impractical? What requires urgent escalation?",
  },
  {
    id: "practice-elsie-turner",
    name: "Elsie Turner",
    age: 74,
    pronouns: "she/her",
    setting: "Intermediate-care stroke rehabilitation unit",
    summary: "Post-stroke rehabilitation, communication support, falls prevention and preparation for home.",
    theme: "Stroke rehabilitation",
    employerBrief: "Recommend coordinated support that enables Elsie to participate in rehabilitation and prepare safely for discharge. Adapt communication, update her person-centred rehabilitation plan and provide a concise multidisciplinary handover.",
    baseline: [
      ["Primary condition", "Left middle cerebral artery ischaemic stroke three weeks ago"],
      ["Current effects", "Right-sided weakness, mild expressive aphasia and fatigue"],
      ["Health history", "Atrial fibrillation and osteoarthritis of both knees"],
      ["Current medicines", "Apixaban 5 mg twice daily; bisoprolol 2.5 mg daily; paracetamol when required"],
      ["Social context", "Lives with her wife in a bungalow. Previously managed all household finances and enjoyed gardening."],
      ["Preferences", "Wants staff to speak with her rather than her wife and to allow enough time for her answers."],
    ],
    task2Update: [
      ["Individual account", "Elsie becomes frustrated when people finish sentences for her."],
      ["Rehabilitation", "She sometimes declines afternoon therapy because fatigue and knee pain are worse later in the day."],
      ["Confidence", "She worries that a walking aid will make her dependent."],
      ["Home context", "The bathroom doorway is narrow and there are two steps into the garden."],
      ["Priority", "Her main goal is making tea independently and returning to the garden."],
    ],
    task3Update: [
      ["New observations", "One near-fall during an unassisted transfer; new bruising to right forearm; neurological observations unchanged."],
      ["Clinical change", "Elsie reports dizziness on standing and says she did not want to wait for assistance."],
      ["Existing plan problem", "The plan uses generic mobility goals and does not record aphasia strategies, fatigue patterns, orthostatic symptoms, meaningful occupations or home barriers."],
      ["Required review", "Address safe transfers, postural observations, therapy timing, communication, medicines review, home assessment and meaningful goals."],
    ],
    task4Update: [
      ["Handover audience", "Community stroke rehabilitation team and district nurse."],
      ["Immediate requirement", "Communicate the near-fall, dizziness, communication needs, functional goals, home barriers and agreed monitoring."],
      ["Professional question focus", "Positive risk-taking, capacity, multidisciplinary roles, measurable outcomes and discharge readiness."],
    ],
    roleplayStimulus: "Elsie wants more independence but feels staff are speaking over her and being too cautious. Use supported communication, allow processing time, explore acceptable risk and agree goals that balance autonomy with safety.",
    questionPrompts: "How did you balance independence and falls risk? What communication adaptation was most important? Which professional roles are required? How will progress be measured? What could delay discharge?",
  },
  {
    id: "practice-george-mensah",
    name: "George Mensah",
    age: 82,
    pronouns: "he/him",
    setting: "Older people's assessment service planning discharge after a fall",
    summary: "Dementia-informed communication, medicines safety, carer support and discharge planning.",
    theme: "Dementia and discharge",
    employerBrief: "Prepare recommendations for a safe, least-restrictive discharge that protects George's dignity and supports his daughter. Gather his views, update the care plan and hand over unresolved risks and responsibilities to community services.",
    baseline: [
      ["Primary conditions", "Vascular dementia and hypertension"],
      ["Reason for admission", "Unwitnessed fall at home without fracture"],
      ["Current medicines", "Amlodipine 5 mg daily; donepezil 10 mg at night; paracetamol when required"],
      ["Social context", "Widowed and lives alone. Daughter Naomi visits daily and holds no registered health and welfare power of attorney."],
      ["Daily living", "Independent with personal care but needs prompts for meals and medicines."],
      ["Preferences", "Strongly wishes to return home and values attending church on Sundays."],
    ],
    task2Update: [
      ["Individual account", "George says strangers enter his home and move his belongings, referring to visiting care staff."],
      ["Carer view", "Naomi reports three missed evening medicine doses and two recent episodes of leaving the cooker on."],
      ["Communication", "George responds best to one question at a time, familiar photographs and a quiet environment."],
      ["Strengths", "He can describe his usual morning routine and recognises risks when they are explained concretely."],
      ["Priority", "He wants to keep his front-door key and continue going to church."],
    ],
    task3Update: [
      ["New observations", "BP 104/66 mmHg sitting and 88/58 mmHg standing with dizziness; HR 72 bpm; alert but disorientated to date."],
      ["Clinical change", "George attempted to leave the ward overnight and said he was going to church."],
      ["Existing plan problem", "The plan proposes continuous supervision without documenting capacity by decision, alternatives, medicines review, cultural routine, carer strain or assistive technology."],
      ["Required review", "Address postural hypotension, decision-specific capacity, least-restrictive options, medicines, nutrition, fire safety, carer support and community review."],
    ],
    task4Update: [
      ["Handover audience", "GP, social care coordinator and community mental health nurse."],
      ["Immediate requirement", "Communicate postural hypotension, cognition and capacity findings, home risks, George's wishes, Naomi's concerns and agreed safeguards."],
      ["Professional question focus", "Consent, confidentiality, least-restrictive practice, safeguarding thresholds and contingency planning."],
    ],
    roleplayStimulus: "George is clear that he wants to go home but becomes distressed when risks are listed quickly. Naomi asks you to tell him he cannot leave. Speak directly with George, use dementia-informed communication, explore his understanding and explain how decisions and safeguards will be agreed.",
    questionPrompts: "How did you uphold George's voice? Which decision requires a capacity assessment? What is the least-restrictive workable option? When might safeguarding escalation be required? What support does Naomi need?",
  },
];

export const ESP_CASE = ESP_CASES[0];

export function getESPCase(caseId) {
  return ESP_CASES.find((item) => item.id === caseId) || ESP_CASE;
}

export function createPortfolioForCase(caseData) {
  return {
    case_id: caseData.id,
    case_name: caseData.name,
    case_summary: caseData.summary,
    status: "in_progress",
    active_task: "task-1",
    active_section: "brief",
    section_progress: "{}",
    workspace_evidence: "{}",
  };
}
