// Learning data for interactive modules — mapped to Pearson T Level Health specification
// Each module maps to spec areas, SK codes, and performance outcomes for Ofsted compliance

export const ANATOMY_SYSTEMS = [
  {
    id: "cardio",
    name: "Cardiovascular System",
    color: "text-rose-600",
    bg: "bg-rose-50",
    border: "border-rose-200",
    specArea: "Area 8-9",
    skCodes: ["SK1", "SK17"],
    poCodes: ["PO4", "PO8"],
    description: "The body's primary delivery network. Relies on pressure gradients generated by the muscular heart to distribute oxygen and key nutrients via the arterial network and return metabolic waste via venous lines.",
    organs: [
      {
        id: "heart", name: "The Heart", cx: 100, cy: 145, r: 18,
        path: "M 100 130 C 100 130 90 115 80 115 C 65 115 55 125 55 140 C 55 160 80 180 100 195 C 120 180 145 160 145 140 C 145 125 135 115 120 115 C 110 115 100 130 100 130 Z",
        function: "Four-chambered muscular pump. The right side pumps deoxygenated blood to the lungs (pulmonary circuit); the muscular left side pumps oxygenated blood to the systemic circulation.",
        clinicalNote: "In Adult Nursing, heart health is evaluated via radial/apical pulses, blood pressure, capillary refill time, and ECG lead patterns. Left-sided heart failure causes pulmonary congestion (fluid in lung bases), while right-sided failure leads to peripheral oedema.",
      },
      {
        id: "aorta", name: "The Aorta", cx: 110, cy: 100, r: 10,
        path: "M 100 120 C 100 105 105 90 120 90 C 125 90 128 95 125 100 C 122 105 112 110 112 120 Z",
        function: "The largest artery in the human body, conducting high-pressure blood directly from the left ventricle into systemic circulation. Its elastic walls absorb systolic recoil.",
        clinicalNote: "Aortic compliance diminishes with atherosclerosis and ageing, resulting in isolated systolic hypertension. Manual BP cuff assessment monitors the systemic hydrostatic pressure wave within the arterial network.",
      },
    ],
  },
  {
    id: "respiratory",
    name: "Respiratory System",
    color: "text-sky-600",
    bg: "bg-sky-50",
    border: "border-sky-200",
    specArea: "Area 8-9",
    skCodes: ["SK1", "SK2", "SK17"],
    poCodes: ["PO4", "PO8"],
    description: "Enables vital external respiration: exchanging carbon dioxide for oxygen across the ultra-thin alveolar-capillary membrane via basic gas diffusion principles.",
    organs: [
      {
        id: "lungs", name: "Lungs & Alveoli", cx: 70, cy: 150, r: 24,
        path: "M 75 115 C 60 115 45 125 45 155 C 45 185 65 190 75 190 Z M 125 115 C 140 115 155 125 155 155 C 155 185 135 190 125 190 Z",
        function: "Spongy bilateral organs consisting of millions of microscopic alveoli. Alveolar walls are only one cell thick, allowing rapid passive diffusion of gases down partial pressure gradients.",
        clinicalNote: "Evaluate lung ventilation via respiratory rate, chest expansion symmetry, oxygen saturation, and chest auscultation. Crackles signal alveolar fluid (e.g., pneumonia or heart failure); wheezes indicate bronchoconstriction (COPD/asthma).",
      },
      {
        id: "trachea", name: "Trachea (Windpipe)", cx: 100, cy: 90, r: 8,
        path: "M 96 65 L 96 115 L 104 115 L 104 65 Z",
        function: "A rigid airway tube lined with ciliated epithelium and reinforced with C-shaped rings of hyaline cartilage to prevent collapse during inspiration.",
        clinicalNote: "Securing a patent airway is the absolute first priority in emergency clinical triage (the 'A' in ABCDE). Blockage via foreign bodies, secretions, or swelling is rapidly fatal; monitor swallowing reflexes in dysphagic patients.",
      },
    ],
  },
  {
    id: "urinary",
    name: "Urinary / Renal System",
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    border: "border-indigo-200",
    specArea: "Area 8-9",
    skCodes: ["SK5", "SK17"],
    poCodes: ["PO4", "PO8"],
    description: "Filters blood circulation to eliminate nitrogenous metabolic wastes (urea, creatinine), regulate systemic blood volume, and balance key blood electrolytes.",
    organs: [
      {
        id: "kidneys", name: "The Kidneys", cx: 65, cy: 185, r: 12,
        path: "M 70 170 C 65 170 60 175 60 185 C 60 195 65 200 70 200 Z M 130 170 C 135 170 140 175 140 185 C 140 195 135 200 130 200 Z",
        function: "Bilateral bean-shaped organs containing functional nephrons. Nephrons filter plasma under pressure, reabsorbing essential water and glucose while secreting excess wastes.",
        clinicalNote: "Monitor kidney health strictly via Fluid Balance Charts (measuring exact intake vs urine output) and blood biochemistry (Urea, Creatinine, Electrolytes). Reduced urine output (<0.5ml/kg/hr for 6 hours) is a major clinical warning of Acute Kidney Injury (AKI).",
      },
      {
        id: "bladder", name: "The Bladder", cx: 100, cy: 210, r: 14,
        path: "M 85 200 C 85 220 90 225 100 225 C 110 225 115 220 115 200 Z",
        function: "A distensible muscular sac lined with transitional epithelium that expands to store urine prior to safe micturition.",
        clinicalNote: "Urinary retention is a common post-operative nursing complication assessed using portable ultrasound bladder scanners. Palpate for a distended bladder and monitor output volumes diligently.",
      },
    ],
  },
  {
    id: "nervous",
    name: "Nervous System",
    color: "text-violet-600",
    bg: "bg-violet-50",
    border: "border-violet-200",
    specArea: "Area 8-9",
    skCodes: ["SK2", "SK17"],
    poCodes: ["PO4", "PO8"],
    description: "The body's rapid communication network. Electrical impulses transmit sensory input, motor commands, and higher cognitive functions through specialised neurons.",
    organs: [
      {
        id: "brain", name: "The Brain", cx: 100, cy: 55, r: 20,
        path: "M 80 40 C 75 35 80 25 90 25 C 95 20 105 20 110 25 C 120 25 125 35 120 40 C 125 45 125 55 120 60 C 120 70 110 75 100 75 C 90 75 80 70 80 60 C 75 55 75 45 80 40 Z",
        function: "The central organ of the nervous system. The cerebrum controls higher functions (thought, memory, voluntary movement), the cerebellum coordinates balance and motor control, and the brainstem regulates vital autonomic functions (breathing, heart rate).",
        clinicalNote: "Assess neurological status using AVPU (Alert, Voice, Pain, Unresponsive) or GCS (Glasgow Coma Scale). Check pupil size and reactivity. Monitor blood glucose — hypoglycaemia mimics stroke symptoms and is rapidly reversible.",
      },
      {
        id: "spinal", name: "Spinal Cord", cx: 100, cy: 130, r: 8,
        path: "M 97 75 L 97 180 L 103 180 L 103 75 Z",
        function: "A cylindrical bundle of nerve fibres that transmits signals between the brain and the peripheral nervous system. Protected by the vertebral column.",
        clinicalNote: "Spinal cord injury requires immediate immobilisation. Nurses must log-roll patients with suspected spinal injury and monitor for autonomic dysreflexia in injuries above T6.",
      },
    ],
  },
  {
    id: "digestive",
    name: "Digestive System",
    color: "text-amber-600",
    bg: "bg-amber-50",
    border: "border-amber-200",
    specArea: "Area 8-9",
    skCodes: ["SK15", "SK17"],
    poCodes: ["PO4", "PO8"],
    description: "Breaks down food into absorbable nutrients via mechanical and chemical digestion, absorbing them into the bloodstream for systemic distribution.",
    organs: [
      {
        id: "stomach", name: "The Stomach", cx: 80, cy: 140, r: 16,
        path: "M 65 120 C 60 125 60 145 70 155 C 80 160 95 155 95 145 C 95 130 85 115 75 115 C 70 115 67 117 65 120 Z",
        function: "A muscular J-shaped organ that mixes food with gastric acid (HCl) and pepsin to begin protein digestion. The pyloric sphincter controls release of chyme into the small intestine.",
        clinicalNote: "Assess for nausea and vomiting. Monitor NG tube placement and aspirate. Patients on NBM (nil by mouth) require IV fluid maintenance and regular mouth care to prevent oral mucosal damage.",
      },
      {
        id: "liver", name: "The Liver", cx: 120, cy: 135, r: 18,
        path: "M 105 120 C 100 125 100 145 110 150 C 125 155 140 145 140 130 C 140 120 130 115 120 115 C 112 115 108 117 105 120 Z",
        function: "The largest internal organ. Performs over 500 functions including detoxification, bile production, glycogen storage, protein synthesis (albumin, clotting factors), and metabolism of carbohydrates, fats, and proteins.",
        clinicalNote: "Monitor liver function via LFTs (ALT, AST, ALP, bilirubin). Observe for jaundice (yellowing of sclera/skin), ascites, and bruising — signs of impaired hepatic function. Administer medications cautiously as hepatic metabolism may be compromised.",
      },
    ],
  },
];

export const PPE_ITEMS = [
  {
    id: "hands", name: "Hand Hygiene (Wash / Rub)",
    donningDesc: "Perform complete 6-step hand hygiene prior to touching any PPE gear.",
    doffingDesc: "Perform comprehensive hand hygiene immediately after removing gloves and again after removing all other gear.",
    donningRank: 1, doffingRank: 5,
  },
  {
    id: "gown", name: "Apron / Gown",
    donningDesc: "Don apron over head and tie securely behind back, keeping chest completely covered.",
    doffingDesc: "Grasp the neck straps and break. Roll the apron down and away from the body, wrapping dirty side inwards. Dispose in orange clinical waste.",
    donningRank: 2, doffingRank: 2,
  },
  {
    id: "mask", name: "Surgical Mask / Respirator",
    donningDesc: "Secure straps or ear loops, shape metal nosepiece comfortably over bridge, and pull under chin. Perform fit check.",
    doffingDesc: "Remove last! Grasp the ear loops or straps from behind. Do NOT touch the front of the mask as it is highly contaminated. Dispose immediately.",
    donningRank: 3, doffingRank: 4,
  },
  {
    id: "visor", name: "Goggles / Visor (Eye Protection)",
    donningDesc: "Fit comfortably over face, adjusting the headband to prevent slippage during clinical procedures.",
    doffingDesc: "Handle strictly by the side headbands or ear arms. Do not touch the clear visor shield. Dispose or place in designated bin for reprocessing.",
    donningRank: 4, doffingRank: 3,
  },
  {
    id: "gloves", name: "Clinical Gloves",
    donningDesc: "Don gloves last. Pull the cuffs completely up and over the apron/gown wrists to ensure full coverage.",
    doffingDesc: "Remove first! Grasp the outside of the glove cuff with opposite gloved hand; peel off. Slide fingers under remaining glove at wrist; peel off. Dispose immediately.",
    donningRank: 5, doffingRank: 1,
  },
];

export const CLINICAL_HAZARDS = [
  { id: "spill", name: "Fluid Spill on Floor", description: "A body fluid spill has been left unattended on the corridor floor.", remedy: "Contain immediately using spill kit. Apply PPE, cover with absorbent granules, scoop into clinical waste bag, disinfect area with chlorine-based solution, and display wet floor sign.", regulation: "COSHH", x: 15, y: 55, w: 20, h: 12 },
  { id: "sharps", name: "Uncapped Sharps on Trolley", description: "A used needle has been left uncapped on the medication trolley.", remedy: "Never recap needles. Dispose immediately into a designated sharps container at point of use. Report any sharps injury via incident reporting system and attend occupational health.", regulation: "HASAWA", x: 60, y: 30, w: 15, h: 15 },
  { id: "meds", name: "Unattended Medication", description: "A medication trolley has been left unlocked and unattended in the bay area.", remedy: "Never leave medication trolleys unlocked or unattended. Lock immediately when stepping away. Controlled drugs must be stored in a locked CD cupboard with a dedicated register.", regulation: "HASAWA", x: 55, y: 50, w: 20, h: 18 },
  { id: "blocked_exit", name: "Blocked Fire Exit", description: "The fire exit is obstructed by stored equipment and a laundry trolley.", remedy: "Fire exits must remain clear at all times. Remove all obstructions immediately. Report to facilities management. Fire exits are checked during safety walks and fire risk assessments.", regulation: "HASAWA", x: 78, y: 65, w: 18, h: 15 },
  { id: "handwash", name: "Empty Hand Wash Station", description: "The hand wash sink has no soap or paper towels available.", remedy: "Hand hygiene is the single most effective IPC measure. Restock immediately. The 5 Moments for Hand Hygiene must always be supported by accessible facilities including soap, water, and paper towels.", regulation: "IPC", x: 8, y: 30, w: 12, h: 15 },
  { id: "waste", name: "Overfilled Clinical Waste Bag", description: "The clinical waste bag is overfilled and not sealed properly, with waste protruding from the top.", remedy: "Clinical waste bags must be sealed when two-thirds full. Never overfill. Tie using the swan-neck method, label with source and date, and store in designated waste area. Follow waste segregation colour coding.", regulation: "COSHH", x: 35, y: 70, w: 15, h: 12 },
];

export const CHRONIC_CONDITIONS = [
  {
    id: "t2d", name: "Type 2 Diabetes Mellitus",
    definition: "A metabolic disorder characterized by systemic insulin resistance and progressive pancreatic beta-cell dysfunction, resulting in chronic hyperglycemia.",
    symptoms: [
      "Polyuria (excessive urination) & Polydipsia (excessive thirst).",
      "Chronic fatigue, blurred vision, and slow-healing cutaneous wounds.",
      "Acanthosis nigricans (hyperpigmentation in skin folds).",
    ],
    anatomicalImpact: "Microvascular damage (causing retinopathy, peripheral neuropathy, and nephropathy) and macrovascular disease (increasing stroke/MI risks).",
    nursingConsiderations: [
      "Perform daily visual diabetic foot assessments to detect painless neuropathic ulcerations.",
      "Educate patient on carbohydrate-controlled diets and monitor glycemic trends (HbA1c levels).",
      "Understand insulin/hypoglycemia protocols (administering quick-acting glucose if values drop below 4.0 mmol/L).",
    ],
  },
  {
    id: "copd", name: "Chronic Obstructive Pulmonary Disease (COPD)",
    definition: "A common, preventable, and progressive respiratory disease characterized by persistent airflow limitation, usually caused by long-term exposure to toxic gases or cigarette smoke.",
    symptoms: [
      "Progressive dyspnoea (shortness of breath) during minor physical activity.",
      "Chronic productive cough with thick sputum production.",
      "Expiratory wheezing, chest tightness, and a barrel-chested appearance.",
    ],
    anatomicalImpact: "Loss of lung elasticity, alveolar wall destruction (emphysema), and chronic bronchial airway inflammation.",
    nursingConsiderations: [
      "For severe CO2 retainers, recognize that the hypoxic drive regulates breathing; maintain target oxygen saturation strictly at 88% to 92% to avoid respiratory depression.",
      "Assist patient into a high Fowler's (sitting upright, leaning forward) position to maximize diaphragmatic expansion.",
      "Liaise with respiratory nurses for pulmonary rehabilitation and smoking cessation pathways.",
    ],
  },
  {
    id: "ckd", name: "Chronic Kidney Disease (CKD)",
    definition: "Gradual, irreversible loss of renal function over months or years, leading to accumulation of metabolic waste products in the blood.",
    symptoms: [
      "Oliguria (reduced urine output) or Anuria in late stages.",
      "Uraemic pruritus (severe itchy skin) and metallic taste in the mouth.",
      "Peripheral and periorbital oedema (fluid swelling around eyes and ankles).",
    ],
    anatomicalImpact: "Fibrous scarring of renal glomeruli and nephrons, triggering systemic fluid overload, severe metabolic acidosis, and hyperkalaemia.",
    nursingConsiderations: [
      "Implement strict Fluid Balance Charts (measuring exact oral intake vs urine output) and perform daily weight checks.",
      "Advise patient on low-sodium, low-potassium, and phosphate-restricted diets to prevent lethal cardiac arrhythmias.",
      "Check glomerular filtration rate (eGFR) and watch for signs of fluid overload (bilateral crackles in lung bases).",
    ],
  },
  {
    id: "htn", name: "Hypertension (HTN)",
    definition: "Persistent elevation of systemic arterial blood pressure, forcing the left ventricle to work harder to pump blood, eventually causing cardiovascular remodeling.",
    symptoms: [
      "Usually asymptomatic (known as the 'Silent Killer').",
      "Severe acute cases can cause occipital headaches, epistaxis (nosebleeds), and visual disturbances.",
      "Dizziness and chest palpitations.",
    ],
    anatomicalImpact: "Arterial wall thickening, endothelial damage, left ventricular hypertrophy, and cerebral artery aneurysm risks.",
    nursingConsiderations: [
      "Ensure standard cuff-size match; an undersized BP cuff will record an artificially elevated reading.",
      "Advise on salt restriction (DASH diet) and monitor compliance with antihypertensive medications (beta-blockers, ACE inhibitors).",
      "Conduct regular postural blood pressure assessments to screen for orthostatic hypotension.",
    ],
  },
];

export const CONDITION_QUIZ = [
  { symptomText: "Patient exhibits a chronic productive cough, severe dyspnoea during minor exertion, expiratory wheezing, and is noted for having a barrel-shaped chest.", nursingCareText: "A primary nursing intervention is maintaining their prescribed target oxygen saturations strictly between 88% and 92%.", correctConditionId: "copd", rationale: "These are classic COPD symptoms. The 88-92% target is critical for CO2 retainers to prevent respiratory depression." },
  { symptomText: "Patient reports excessive urination and unquenchable thirst. They have slow-healing wounds and fatigue.", nursingCareText: "Administer quick-acting glucose if blood glucose drops below 4.0 mmol/L and perform daily diabetic foot assessments.", correctConditionId: "t2d", rationale: "Polyuria and polydipsia are hallmark T2D symptoms. The 4.0 mmol/L threshold triggers the hypoglycaemia protocol." },
  { symptomText: "Patient has peripheral oedema around the ankles and eyes, with a metallic taste and severe itching.", nursingCareText: "Implement strict Fluid Balance Charts and advise on a low-potassium, low-phosphate diet.", correctConditionId: "ckd", rationale: "These are classic CKD symptoms. Fluid balance monitoring and dietary restrictions prevent hyperkalaemia and fluid overload." },
  { symptomText: "Patient is asymptomatic but found to have consistently elevated blood pressure readings during routine checks.", nursingCareText: "Ensure correct cuff sizing and advise on salt restriction (DASH diet). Monitor for orthostatic hypotension.", correctConditionId: "htn", rationale: "Hypertension is often asymptomatic — the 'Silent Killer'. Correct cuff size is essential for accurate readings." },
];

export const SCIENCE_DECK = [
  {
    id: "fluid_bp", title: "Fluid Pressure Dynamics & Sphygmomanometry",
    principle: "Hydrostatic pressure & Bernoulli's Principle: Fluids (blood) flow from areas of high pressure to low pressure. When fluid flow is constricted, velocity increases and turbulence is introduced.",
    clinicalTech: "Manual Blood Pressure Measurement (Sphygmomanometer & Stethoscope).",
    explanation: "Inflating the BP cuff past systolic pressure completely occludes the brachial artery (no flow, silent). As the cuff slowly deflates, pressure equals systolic level, forcing turbulent blood through the partially closed vessel. This turbulence generates audible vibrations called Korotkoff Sounds.",
    quizQuestion: "Why does the nursing student hear Korotkoff sounds only between the systolic and diastolic pressure levels on a manual blood pressure reading?",
    quizOptions: [
      "The artery is completely collapsed and silent at all times.",
      "The blood flow transitions from silent laminar flow to noisy turbulent flow due to partial arterial occlusion, then returns to silent laminar flow once fully open.",
      "The stethoscope diaphragm operates only under maximum air pressure inside the cuff.",
      "The heart stops beating momentarily when the cuff is deflated below systolic pressure.",
    ],
    correctAnswer: 1,
    rationale: "Partial arterial constriction causes turbulent flow which is audible. Complete occlusion (above systolic) or unconstricted laminar flow (below diastolic) is silent.",
  },
  {
    id: "electricity_ecg", title: "Bio-Electricity, Depolarisation & ECG",
    principle: "Electrical conduction & Action potentials: Cell membranes maintain resting potentials. Stimuli open sodium channels, causing depolarization (ion charge shift) that propagates as an electrical wave.",
    clinicalTech: "Electrocardiogram (ECG / EKG) lead monitoring.",
    explanation: "The heart's pacemaker (Sinoatrial Node) initiates a bio-electrical wave. ECG electrodes placed on the skin detect these tiny electrical potential differences. The P-wave represents atrial depolarization, the QRS complex represents rapid ventricular depolarization, and the T-wave represents ventricular repolarisation.",
    quizQuestion: "In a standard 12-lead ECG, what biological event does the QRS complex wave represent, and what is its clinical significance?",
    quizOptions: [
      "Slow relaxation of the atria to permit venous filling.",
      "Electrical depolarization of the ventricles, triggering mechanical contraction (systole) to pump blood to the lungs and body.",
      "Mechanical closing of the heart's tricuspid and mitral valves.",
      "The resting electrical resistance of the skin tissue under the electrodes.",
    ],
    correctAnswer: 1,
    rationale: "The QRS represents ventricular depolarization, which triggers the contraction of the massive lower heart chambers. Mismatches signal cardiac arrhythmias or blockages.",
  },
  {
    id: "gas_oxy", title: "Gas Laws, Boyle's Law & Oxygen Therapy",
    principle: "Boyle's Law: P1V1 = P2V2. At a constant temperature, the pressure of a given mass of gas is inversely proportional to its volume.",
    clinicalTech: "Oxygen cylinder flowmeters, regulators, and high-pressure ventilators.",
    explanation: "Oxygen gas is compressed under extremely high pressure inside cylinders to fit a massive volume into a small storage space. Opening the flowmeter regulator expands the gas volume, dropping its pressure to a safe atmospheric level suitable for patient inhalation.",
    quizQuestion: "According to Boyle's Law, what happens to the oxygen gas molecules when a ward cylinder pressure regulator is opened to deliver O2 to a patient?",
    quizOptions: [
      "The gas volume increases as the molecules expand into the low-pressure atmosphere, causing the pressure inside the delivery line to decrease.",
      "The gas transitions into a liquid phase due to the rapid heating of the metal nozzle.",
      "The molecular weight of the oxygen atoms increases under vacuum.",
      "The absolute number of oxygen molecules inside the sealed cylinder increases.",
    ],
    correctAnswer: 0,
    rationale: "When the regulator opens, the gas expands into a much larger volume which proportionally decreases its high storage pressure to safe breathing levels.",
  },
  {
    id: "optics_lens", title: "Refraction, Lens Power & Ophthalmoscopy",
    principle: "Refraction: Light bends when passing between media of different optical densities. The degree of bending depends on the refractive index difference and the angle of incidence.",
    clinicalTech: "Ophthalmoscope examination & visual acuity testing (Snellen chart).",
    explanation: "The eye's cornea and lens refract light rays to focus an image on the retina. An ophthalmoscope projects a light beam through the pupil and uses a lens system to view the retina, optic disc, and blood vessels. The Snellen chart tests visual acuity at a standard 6-metre distance.",
    quizQuestion: "Why does a patient with myopia (short-sightedness) require a concave (diverging) lens correction?",
    quizOptions: [
      "Their eyeball is too short, causing light to focus behind the retina.",
      "Their eyeball is too long, causing light to focus in front of the retina; a diverging lens spreads the light rays to extend the focal point back onto the retina.",
      "Their cornea is completely opaque and blocks all light transmission.",
      "Their retina has detached and no lens can restore vision.",
    ],
    correctAnswer: 1,
    rationale: "In myopia, the elongated eyeball causes light to converge in front of the retina. A concave lens diverges the rays, pushing the focal point back onto the retina.",
  },
  {
    id: "levers_mobility", title: "Levers, Fulcrums & Safe Manual Handling",
    principle: "Lever Principle: A rigid bar rotating around a fulcrum. Mechanical advantage = load arm / effort arm. The human musculoskeletal system operates as a system of third-class levers.",
    clinicalTech: "Safe patient handling & hoist transfer procedures.",
    explanation: "When manual handling, the spine acts as a lever with the sacrum as the fulcrum. Bending from the waist dramatically shortens the effort arm and lengthens the load arm, multiplying compressive forces on lumbar discs. Using a hoist or bending at the knees redistributes the mechanical advantage safely.",
    quizQuestion: "Why is bending from the waist to lift a patient considered unsafe according to lever mechanics?",
    quizOptions: [
      "The spine is a second-class lever and cannot support any weight.",
      "Bending from the waist lengthens the load arm and shortens the effort arm, massively increasing the compressive force on lumbar discs. Bending at the knees keeps the load closer to the fulcrum.",
      "The human body contains no lever systems.",
      "Patients are weightless and therefore no lever principles apply.",
    ],
    correctAnswer: 1,
    rationale: "Bending at the waist creates a mechanical disadvantage that can multiply disc pressure by up to 10x. The Manual Handling Operations Regulations 1992 mandate biomechanically safe techniques.",
  },
];

export const LEARNING_MODULES = [
  { id: "atlas", title: "Interactive Anatomy Atlas", icon: "Body", specArea: "Area 8-9", skCodes: ["SK1", "SK17"], poCodes: ["PO8"], description: "Explore body systems with clickable SVG organs and clinical nursing notes." },
  { id: "ppe", title: "PPE Sequencer", icon: "Shield", specArea: "Area 7", skCodes: ["SK7"], poCodes: ["PO7"], description: "Master the correct donning and doffing sequence for personal protective equipment." },
  { id: "hazard", title: "Clinical Hazard Hunt", icon: "Alert", specArea: "Area 3", skCodes: ["SK7", "SK18"], poCodes: ["PO3", "PO7"], description: "Identify safety hazards in a clinical environment and learn the correct remediation." },
  { id: "patho", title: "Pathophysiology Matcher", icon: "Stethoscope", specArea: "Area 9", skCodes: ["SK1", "SK17"], poCodes: ["PO8"], description: "Match patient symptoms to chronic conditions and nursing interventions." },
  { id: "sciencedeck", title: "Sci-Health Formula Deck", icon: "Flask", specArea: "Area 8", skCodes: ["SK1", "SK17"], poCodes: ["PO4", "PO8"], description: "Learn the physics and biology behind clinical technology with interactive flashcards." },
];