export const SK_CODES = {
  "SK1": "Perform and record clinical observations (vital signs, NEWS2)",
  "SK2": "Conduct structured ABCDE assessment",
  "SK3": "Develop care plans using SMART goals framework",
  "SK4": "Conduct clinical risk assessments (falls, pressure, VTE)",
  "SK5": "Maintain accurate fluid balance charts",
  "SK6": "Use SBAR communication for clinical handover",
  "SK7": "Apply infection prevention and control measures",
  "SK8": "Respond to safeguarding concerns (Care Act 2014)",
  "SK9": "Deliver person-centred care (CS1)",
  "SK10": "Communicate effectively using clinical terminology (CS2)",
  "SK11": "Work within MDT boundaries (CS3)",
  "SK12": "Reflect on clinical practice (CS4)",
  "SK13": "Research and apply evidence-based practice (CS5)",
  "SK14": "Present clinical information professionally (CS6)",
  "SK15": "Assist with activities of daily living",
  "SK16": "Administer medications safely (under supervision)",
  "SK17": "Manage deteriorating patient using escalation protocols",
  "SK18": "Complete accurate clinical documentation",
};

export const PERFORMANCE_OUTCOMES = {
  "PO1": "Core Area 1 — The Healthcare Sector",
  "PO2": "Core Area 2 — Health, Safety & Environmental Regulations",
  "PO3": "Core Area 3 — Managing Information & Data",
  "PO4": "Core Area 4 — Good Scientific & Clinical Practice",
  "PO5": "Core Area 5 — Providing Person-Centred Care",
  "PO6": "Core Area 6 — Health & Wellbeing",
  "PO7": "Core Area 7 — Safeguarding",
  "PO8": "Core Areas 8–9 — Science Concepts in Health",
  "PO9": "OS Part A — Supporting Healthcare (Mandatory Core)",
  "PO10": "OS Part B — Supporting the Adult Nursing Team",
};

export const SPEC_AREAS = [
  { code: "Area 1", title: "The Healthcare Sector", volume: "Core Paper 1" },
  { code: "Area 2", title: "Health, Safety & Environmental Regulations", volume: "Core Paper 1" },
  { code: "Area 3", title: "Managing Information & Data", volume: "Core Paper 1" },
  { code: "Area 4", title: "Good Scientific & Clinical Practice", volume: "Core Paper 1" },
  { code: "Area 5", title: "Providing Person-Centred Care", volume: "Core Paper 1" },
  { code: "Area 6", title: "Health & Wellbeing", volume: "Core Paper 1" },
  { code: "Area 7", title: "Safeguarding", volume: "Core Paper 1" },
  { code: "Area 8", title: "Core Science Concepts", volume: "Core Paper 2" },
  { code: "Area 9", title: "Further Science Concepts in Health", volume: "Core Paper 2" },
];

// THEORY_MODULES now live in theoryContent.js (full 9-area coverage with knowledge checks)
export { THEORY_MODULES } from "@/lib/theoryContent";

const _LEGACY_THEORY_MODULES = [
  {
    title: "The Healthcare Sector",
    spec_area: "Area 1",
    volume: "Core Paper 1",
    section: "Core Area 1 — The Healthcare Sector",
    content: `## The T Level Technical Qualification in Health\n\nT Levels are two-year Level 3 study programmes for students aged 16–19, combining classroom theory, practical learning, and a minimum **315-hour industry placement**. Developed with industry experts, they prepare students for skilled employment, apprenticeships, or higher education.\n\n## Qualification Metrics\n\n- **Qualification Number (QN):** 610/7438/X\n- **First Teaching:** September 2026\n- **Total Guided Learning Hours (GLH):** 1080 hours (510 Core)\n- **Total Qualification Time (TQT):** 1800 hours (870 Core)\n\nTwo mandatory components, equally weighted:\n1. **Core Component (50%)** — Core Paper 1 (36%), Core Paper 2 (24%), Employer Set Project (40%). Graded A*–E.\n2. **Occupational Specialism (50%)** — OS Core (65%) + OS Pathway (35%). Graded Pass, Merit, Distinction.\n\n## Area 1: The Healthcare Sector\n\nThis area covers the structure and organisation of the UK healthcare sector, the role of the NHS, private and voluntary providers, and career pathways in health.\n\n### Key Topics\n- Structure of the NHS (primary, secondary, tertiary care)\n- Role of private and voluntary sector providers\n- Job roles, career pathways and the healthcare workforce\n- The NHS Constitution and its values\n- Healthcare regulation and professional bodies (NMC, GMC, HCPC)\n\n### Threshold Competence\nUpon completion, students demonstrate 'threshold competence' — the core knowledge and skills to enter healthcare support roles such as Senior Healthcare Support Worker, Therapy Assistant, or Mental Health Support Worker.`,
    sk_codes: ["SK9"],
    performance_outcomes: ["PO1", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 1", "NHS Constitution", "NHS England Career Framework"],
    estimated_duration: 15,
    order_index: 1,
  },
  {
    title: "Health, Safety & Environmental Regulations",
    spec_area: "Area 2",
    volume: "Core Paper 1",
    section: "Core Area 2 — Health, Safety & Environmental Regulations",
    content: `## Area 2: Health, Safety & Environmental Regulations\n\nThis area covers the legislation, regulations and guidance that govern health, safety and environmental practice in healthcare settings.\n\n### Key Legislation\n- **Health and Safety at Work Act 1974 (HASAWA):** Employers must provide a safe working environment; employees must take reasonable care of their own and others' safety.\n- **Manual Handling Operations Regulations 1992:** Risk reduction protocols for repositioning individuals or transferring heavy stock (hierarchy: avoid, assess, reduce).\n- **Control of Substances Hazardous to Health (COSHH) 2002:** Safe management and exposure limitation for hazardous cleaning agents, medications, or clinical waste.\n- **Reporting of Injuries, Diseases and Dangerous Occurrences Regulations (RIDDOR) 2013:** Systematic reporting of serious workplace accidents, occupational illnesses, or equipment failures to the HSE.\n- **Provision and Use of Work Equipment Regulations (PUWER) 1998:** Safe use and maintenance of work equipment.\n\n### Risk Assessment\n- Identify hazards, evaluate who might be harmed and how, implement controls, record findings, and review.\n- Risk = Likelihood × Severity.\n\n### Environmental Considerations\n- Safe disposal of clinical waste (sharps, pharmaceutical, infectious waste streams).\n- Sustainability and environmental impact of healthcare practice.\n\n### Clinical Governance\nA system through which NHS organisations are accountable for continuously improving the quality of services. Key pillars: risk management, clinical audit, evidence-based practice, patient involvement, staffing, education, and clinical effectiveness.`,
    sk_codes: ["SK7", "SK18"],
    performance_outcomes: ["PO2", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 2", "HASAWA 1974", "HSE: COSHH & RIDDOR", "NHS England: Clinical Governance"],
    estimated_duration: 20,
    order_index: 2,
  },
  {
    title: "Managing Information & Data",
    spec_area: "Area 3",
    volume: "Core Paper 1",
    section: "Core Area 3 — Managing Information & Data",
    content: `## Area 3: Managing Information & Data\n\nThis area covers how information and data are managed, protected, and used in healthcare settings.\n\n### Information Governance\n- **Data Protection Act 2018 & UK GDPR:** Lawful, fair, transparent, and accurate processing of sensitive patient health data.\n- **Caldicott Principles:** Rules governing the sharing of confidential information — all data exchanges must be justified, necessary, and restricted to minimal data sets.\n- **NHS Data Security and Protection Standards:** Mandatory for all organisations handling NHS patient data.\n\n### The 8 Caldicott Principles\n1. Justify the purpose of using confidential information.\n2. Use the minimum necessary confidential information.\n3. Access to confidential information should be on a strict need-to-know basis.\n4. Everyone should understand their responsibilities.\n5. Understand and comply with the law.\n6. The duty to share information can be as important as the duty to protect confidentiality.\n7. The duty to share information for direct care can be as important as the duty to protect confidentiality.\n8. Inform patients and service users about how their information is used.\n\n### Data Quality & Accuracy\n- Accurate, timely, and complete clinical records.\n- Use of standardised classification systems (ICD-10/11, SNOMED CT).\n- Audit trails for all data access and amendment.\n\n### Confidentiality & Disclosure\n- Patient consent for information sharing.\n- Exceptions: where there is a legal requirement, or a safeguarding/public interest justification.\n- Never discuss patient information in public areas or on social media.`,
    sk_codes: ["SK8", "SK18"],
    performance_outcomes: ["PO3", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 3", "Data Protection Act 2018", "NHS Caldicott Guardian Principles"],
    estimated_duration: 15,
    order_index: 3,
  },
  {
    title: "Providing Person-Centred Care & Safeguarding",
    spec_area: "Area 5",
    volume: "Core Paper 1",
    section: "Core Area 5 — Providing Person-Centred Care",
    content: `## Area 5: Providing Person-Centred Care\n\nThis area covers person-centred care — working in partnership with individuals to plan and deliver care that respects their needs, preferences, and rights.\n\n### Core Principles\n- Working in partnership with individuals and their families.\n- Respecting individual dignity, choices, beliefs, and preferences.\n- Promoting independence and wellbeing.\n- Holistic assessment covering physical, psychological, social, and spiritual needs.\n\n### The Nursing Process\n1. **Assessment** — holistic data collection.\n2. **Diagnosis** — identify actual and potential problems.\n3. **Planning** — set SMART goals, agree interventions.\n4. **Implementation** — deliver care.\n5. **Evaluation** — review outcomes, revise plan.\n\n### SMART Goals\n- Specific, Measurable, Achievable, Relevant, Time-bound.\n\n### Safeguarding (covered in Area 7)\n- **Care Act 2014:** Six key principles — Empowerment, Prevention, Proportionality, Protection, Partnership, Accountability.\n- **The Prevent Duty Guidance 2023:** Identify early behavioural indicators of radicalisation.\n- Safeguarding children: Children Act 1989/2004.\n- Recognising signs of abuse: physical, emotional, sexual, financial, neglect, discriminatory, organisational, self-neglect, modern slavery, domestic abuse.\n\n### Consent\n- **Mental Capacity Act 2005:** Presumption of capacity; right to make unwise decisions; best interests; least restrictive option.\n- Consent must be voluntary, informed, and capacity-based.`,
    sk_codes: ["SK8", "SK9", "SK18"],
    performance_outcomes: ["PO5", "PO6"],
    references: ["T Level Health Specification — Core Paper 1, Area 5", "Care Act 2014", "Mental Capacity Act 2005", "NMC Code: Prioritise People"],
    estimated_duration: 18,
    order_index: 4,
  },
  {
    title: "Core Science Concepts",
    spec_area: "Area 8",
    volume: "Core Paper 2",
    section: "Core Area 8 — Core Science Concepts",
    content: `## Area 8: Core Science Concepts\n\nThis area covers the core scientific concepts that underpin health and clinical practice.\n\n### Cell Theory\n1. All living organisms are composed of one or more functional cells.\n2. Cells are the basic structural and organisational unit of life.\n3. All cells arise from pre-existing cells through division.\n\n### Eukaryotic Cell Ultrastructure\n- **Cell Surface Membrane:** Fluid mosaic model; controls selective transport and displays cell surface antigens.\n- **Nucleus:** Houses genetic material (DNA) and controls gene expression.\n- **Mitochondria:** Double-membraned; site of aerobic respiration producing ATP.\n- **Rough Endoplasmic Reticulum (RER):** Ribosome-studded; protein translation, packaging, and transport.\n- **Golgi Apparatus:** Modifies, packages, and sorts proteins for secretion.\n- **Lysosomes:** Contain digestive enzymes for intracellular waste breakdown.\n\n### Biochemistry\n- **Triglyceride** = 1 Glycerol + 3 Fatty Acids.\n- **Proteins:** Primary → secondary → tertiary → quaternary structure.\n- **Carbohydrates:** Prime metabolic fuel; stored as glycogen.\n- **Lipids:** Amphipathic phospholipids form bilayers (hydrophilic head, hydrophobic tail).\n- **Enzymes:** Biological catalysts lowering activation energy; affected by temperature, pH, and substrate concentration.\n\n### Genetics\n- DNA structure (double helix), replication, transcription, translation.\n- Mendelian inheritance and genetic disorders relevant to healthcare.\n\n### Chemistry for Health\n- pH and the acid-base balance.\n- Solutions, concentrations, and dilutions used in drug administration.\n- Moles and molar solutions.`,
    sk_codes: ["SK17"],
    performance_outcomes: ["PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 8", "Clinical Skills.net: Biochemistry Fundamentals"],
    estimated_duration: 20,
    order_index: 5,
  },
  {
    title: "Further Science Concepts in Health",
    spec_area: "Area 9",
    volume: "Core Paper 2",
    section: "Core Area 9 — Further Science Concepts in Health",
    content: `## Area 9: Further Science Concepts in Health\n\nThis area covers further scientific concepts that build on Core Area 8 and apply them to health and clinical practice.\n\n### Pathogens & Disease Transmission\nPathogens are disease-causing microorganisms. Transmission routes:\n- **Direct:** physical touch, bodily fluids, droplet inhalation.\n- **Indirect:** contaminated surfaces, vector bites, faecal-oral ingestion.\n\n**Healthcare-Associated Infections (HCAIs):** Infections acquired during clinical care, including MRSA and *Clostridium difficile*.\n\n### Immunology\n- **Non-Specific (Innate) Defenses:** Skin, mucous membranes, stomach acid, inflammation, phagocytosis.\n- **Specific (Adaptive) Immune Response:** T-cells (cell-mediated) and B-cells (humoral antibody synthesis). Immunological memory underpins vaccinations.\n\n### Homeostasis\nMaintains stable internal variables (core temperature, blood glucose, blood pressure, osmoregulation) via **negative feedback loops**. Failure leads to chronic disease.\n\n### Anatomy & Physiology\n- Body systems: cardiovascular, respiratory, nervous, digestive, urinary, musculoskeletal, endocrine, reproductive, integumentary, lymphatic/immune.\n- Key organ structure and function relevant to nursing practice.\n\n### Disease Classification Systems\n- **ICD (International Classification of Diseases):** Codes physical and mental health conditions.\n- **DSM:** Standardises criteria for psychiatric diagnoses.\n- **SNOMED CT:** Common clinical vocabulary for electronic health records.\n\n### Physics for Health\n- Pressure and fluid dynamics (blood pressure, IV flow rates).\n- Electricity and magnetism (ECG, defibrillation, MRI principles).\n- Radiation and imaging (X-ray, CT).`,
    sk_codes: ["SK7", "SK17"],
    performance_outcomes: ["PO7", "PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 9", "NHS England: IPC", "WHO: Disease Classification"],
    estimated_duration: 20,
    order_index: 6,
  },
];

export const KNOWLEDGE_ARTICLES = [
  {
    title: "ABCDE Assessment Approach",
    category: "clinical_procedure",
    content: `## ABCDE Assessment\n\nThe ABCDE approach is a systematic method for assessing and treating acutely unwell patients.\n\n### A — Airway\nAssess patency. Look for signs of obstruction, listen for stridor/gurgling. Consider airway adjuncts (OPA/NPA) if compromised.\n\n### B — Breathing\nAssess respiratory rate, effort, chest movement, oxygen saturation. Administer high-flow oxygen if hypoxic.\n\n### C — Circulation\nAssess heart rate, blood pressure, capillary refill, skin colour/temperature. Establish IV access. Consider fluid resuscitation.\n\n### D — Disability\nAssess conscious level using AVPU or GCS. Check pupils, blood glucose.\n\n### E — Exposure\nFully expose the patient to identify rashes, wounds, bleeding. Maintain dignity and warmth.`,
    sk_codes: ["SK2", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["Resuscitation Council UK: ABCDE Approach", "Clinical Skills.net: ABCDE Assessment", "NHS England: Deteriorating Patient"],
    source: "Clinical Skills.net",
  },
  {
    title: "NEWS2 (National Early Warning Score)",
    category: "clinical_procedure",
    content: `## NEWS2 Scoring System\n\nNEWS2 is a tool for standardising the assessment of acute illness severity. It aggregates scores across 7 physiological parameters:\n\n1. Respiratory rate\n2. Oxygen saturation (SpO₂)\n3. Use of supplemental oxygen\n4. Systolic blood pressure\n5. Pulse rate\n6. Level of consciousness (AVPU: Alert, Voice, Pain, Unresponsive)\n7. Temperature\n\n### Escalation Bands\n\n- **Score 0–4 (Low):** Routine monitoring. Minimum 12 hourly if single-parameter trigger, 4–6 hourly otherwise.\n- **Score 5–6 (Medium):** Urgent ward-based review by registered nurse/clinician. Inform registrar.\n- **Score 7+ (High):** Emergency assessment by clinical team with critical care competencies. ICU outreach.`,
    sk_codes: ["SK1", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["Royal College of Physicians: NEWS2 Guidance", "NHS England: Deteriorating Patient Recognition", "Clinical Skills.net: NEWS2"],
    source: "NHS England",
  },
  {
    title: "SBAR Communication Framework",
    category: "clinical_procedure",
    content: `## SBAR Handover Communication\n\nSBAR is a structured method for communicating clinical information clearly and efficiently.\n\n### S — Situation\nState your name, role, patient name, location, and the current concern briefly.\n\n### B — Background\nProvide relevant clinical history: diagnosis, recent events, current observations.\n\n### A — Assessment\nShare your clinical assessment: vital signs, NEWS2 score, what you think is happening.\n\n### R — Recommendation\nState what you need: review, escalation, specific intervention, timeframe.`,
    sk_codes: ["SK6", "SK10"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["NHS England: SBAR Communication Tool", "Clinical Skills.net: Clinical Handover", "RCN: Handover Best Practice"],
    source: "NHS England",
  },
  {
    title: "Infection Prevention and Control (IPC)",
    category: "governance",
    content: `## Infection Prevention and Control\n\nStandard precautions are the basic level of infection control that should be practised for all patients.\n\n### Hand Hygiene\nThe '5 Moments for Hand Hygiene' (WHO):\n1. Before touching a patient\n2. Before clean/aseptic procedures\n3. After body fluid exposure risk\n4. After touching a patient\n5. After touching patient surroundings\n\n### PPE\n- Gloves and aprons for standard care\n- Fluid-repellent surgical masks, eye protection, gowns for aerosol-generating procedures\n- Always perform hand hygiene before and after PPE use\n\n### HCAIs\n- MRSA: Screen on admission, isolate positive cases, use contact precautions\n- C. difficile: Isolate, use soap and water (not alcohol gel) for hand hygiene`,
    sk_codes: ["SK7"],
    performance_outcomes: ["PO7"],
    references: ["NHS England: IPC Manual", "WHO: 5 Moments for Hand Hygiene", "Clinical Skills.net: IPC Procedures"],
    source: "NHS England",
  },
  {
    title: "Pressure Ulcer Prevention — Waterlow Assessment",
    category: "clinical_procedure",
    content: `## Waterlow Risk Assessment\n\nThe Waterlow score assesses pressure ulcer risk across multiple factors:\n\n- Build/weight (BMI)\n- Skin type (visual risk areas)\n- Sex and age\n- Continence\n- Mobility\n- Special risks (tissue malnutrition, neurological deficit, major surgery/trauma)\n- Medication\n\n### Risk Bands\n- **10+**: At risk\n- **15+**: High risk\n- **20+**: Very high risk\n\n### Interventions\n- Reposition every 2 hours (or more frequently for high risk)\n- Use pressure-relieving mattresses/cushions\n- Keep skin clean and dry\n- Ensure adequate nutrition and hydration\n- Document all repositioning and skin assessments`,
    sk_codes: ["SK4", "SK15"],
    performance_outcomes: ["PO4", "PO6", "PO9"],
    references: ["Clinical Skills.net: Pressure Ulcer Prevention", "NHS England: Tissue Viability", "NICE CG179: Pressure Ulcers"],
    source: "Clinical Skills.net",
  },
  {
    title: "Falls Risk Assessment — Morse Fall Scale",
    category: "clinical_procedure",
    content: `## Morse Fall Scale\n\nThe Morse Fall Scale assesses fall risk based on six variables:\n\n1. History of falling (25 pts)\n2. Secondary diagnosis (15 pts)\n3. Ambulatory aid (0–30 pts)\n4. IV therapy/heparin lock (20 pts)\n5. Gait/transferring (0–20 pts)\n6. Mental status (0–15 pts)\n\n### Risk Levels\n- **0–24**: Low risk — standard fall prevention measures\n- **25–50**: Moderate risk — yellow wristband, bed alarm consideration\n- **51+**: High risk — red wristband, hourly rounding, bed alarm, referral to falls team\n\n### Prevention Strategies\n- Ensure call bell within reach\n- Keep bed in lowest position\n- Non-slip footwear\n- Adequate lighting\n- Remove trip hazards`,
    sk_codes: ["SK4"],
    performance_outcomes: ["PO4", "PO6"],
    references: ["Clinical Skills.net: Falls Assessment", "NICE CG161: Falls Assessment", "NHS England: Falls Prevention"],
    source: "Clinical Skills.net",
  },
  {
    title: "Safe Patient Identification and Consent",
    category: "clinical_procedure",
    content: `## Safe Patient Identification and Consent\n\nCorrect identification and valid consent are essential before every observation, intervention or transfer.\n\n### Before the procedure\n1. Introduce yourself and explain your role.\n2. Use at least two approved identifiers, such as full name, date of birth and NHS or hospital number.\n3. Check the wristband against the prescription, request or care record.\n4. Explain the purpose, expected benefit, possible discomfort and available choices.\n5. Confirm that the person understands and agrees before proceeding.\n\n### Person-centred practice\nUse accessible language, communication aids or an interpreter when required. Give the person time to ask questions and respect a refusal. Consent is an ongoing process and may be withdrawn.\n\n### Escalate when\nStop and seek support if identifiers do not match, capacity is uncertain, the procedure changes, or the person appears coerced or distressed. Document the discussion and action taken.`,
    sk_codes: ["SK3", "SK6", "SK9"],
    performance_outcomes: ["PO4", "PO5", "PO6"],
    references: ["NHS England: Identity Checks", "NMC Code: Prioritise People", "Mental Capacity Act 2005"],
    source: "NHS England",
  },
  {
    title: "Clinical Governance and Quality Improvement",
    category: "governance",
    content: `## Clinical Governance and Quality Improvement\n\nClinical governance is the framework through which health organisations are accountable for continuously improving quality and safeguarding high standards of care.\n\n### Core elements\n- Evidence-based practice and clinical effectiveness\n- Risk management, incident reporting and learning\n- Audit, service evaluation and quality improvement\n- Education, supervision and staff competence\n- Patient experience, involvement and accessible feedback\n- Information governance and accurate records\n\n### Improvement cycle\nIdentify a problem, establish a measurable baseline, plan a small change, test it, review the data and decide whether to adopt, adapt or stop the change. A just culture examines systems and contributing factors while maintaining professional accountability.\n\n### Learner application\nFollow local policies, work within competence, report hazards promptly, participate honestly in debriefs and use feedback to improve practice.`,
    sk_codes: ["SK9", "SK10", "SK18"],
    performance_outcomes: ["PO6", "PO7", "PO9"],
    references: ["NHS England: Patient Safety Strategy", "CQC: Fundamental Standards", "NHS England: Quality Improvement"],
    source: "NHS England",
  },
  {
    title: "Incident Reporting, Duty of Candour and Learning",
    category: "governance",
    content: `## Incident Reporting, Duty of Candour and Learning\n\nAn incident includes an event or omission that caused, or could have caused, harm. Near misses should also be reported because they reveal risks before harm occurs.\n\n### Immediate priorities\n1. Make the person safe and summon appropriate clinical help.\n2. Preserve relevant evidence and record objective facts.\n3. Inform the registered practitioner or manager according to local policy.\n4. Complete the incident report promptly; do not copy blame or speculation into the clinical record.\n\n### Openness\nDuty of candour requires organisations and professionals to be open and honest when specified safety incidents occur. The person should receive a clear explanation, an apology, information about further enquiries and appropriate support.\n\n### Learning response\nReview human, environmental, equipment, communication and system factors. Actions should be specific, owned, measurable and reviewed for effectiveness.`,
    sk_codes: ["SK6", "SK9", "SK18"],
    performance_outcomes: ["PO6", "PO7", "PO9"],
    references: ["CQC Regulation 20: Duty of Candour", "NHS England: Patient Safety Incident Response Framework", "NMC Code"],
    source: "CQC",
  },
  {
    title: "Consent, Capacity and Best-Interest Decisions",
    category: "legislation",
    content: `## Consent, Capacity and Best-Interest Decisions\n\nValid consent must be voluntary, informed and given by a person with capacity for the specific decision at the time it is required.\n\n### Mental Capacity Act principles\n1. Presume capacity unless established otherwise.\n2. Provide all practicable support to help the person decide.\n3. An unwise decision does not by itself prove lack of capacity.\n4. Any act for a person lacking capacity must be in their best interests.\n5. Choose the least restrictive effective option.\n\n### Capacity assessment\nThe person must be able to understand, retain, use or weigh relevant information and communicate the decision. Capacity is decision-specific and may fluctuate.\n\n### Your role\nUse accessible communication, involve appropriate registered staff, document observations accurately and never assume that diagnosis, age or appearance determines capacity.`,
    sk_codes: ["SK3", "SK6", "SK9"],
    performance_outcomes: ["PO5", "PO6"],
    references: ["Mental Capacity Act 2005", "Mental Capacity Act Code of Practice", "NHS: Consent to Treatment"],
    source: "UK Legislation",
  },
  {
    title: "Confidentiality, Data Protection and Record Keeping",
    category: "legislation",
    content: `## Confidentiality, Data Protection and Record Keeping\n\nHealth information is confidential and must be handled lawfully, fairly and securely. Access only the information needed for your role and share it only for a justified purpose.\n\n### Safe information handling\n- Confirm identity before discussing or releasing information.\n- Keep screens, passwords, printed records and conversations secure.\n- Use approved systems and follow local retention and disposal policies.\n- Record contemporaneously, accurately and objectively; date, time and identify each entry.\n- Correct errors transparently rather than deleting or disguising them.\n\n### Sharing information\nUse the minimum necessary information. Seek consent where appropriate, but recognise that safeguarding or serious-risk concerns may justify proportionate sharing. Escalate uncertainty to the information governance or safeguarding lead.\n\n### Key legislation\nThe UK GDPR and Data Protection Act 2018 govern personal data. The common law duty of confidentiality and professional standards also apply.`,
    sk_codes: ["SK6", "SK9", "SK10"],
    performance_outcomes: ["PO5", "PO6", "PO7"],
    references: ["Data Protection Act 2018", "UK GDPR", "NHS England: Records Management Code of Practice"],
    source: "NHS England",
  },
  {
    title: "Cardiovascular and Respiratory Systems",
    category: "anatomy_physiology",
    content: `## Cardiovascular and Respiratory Systems\n\nThese systems work together to deliver oxygen to tissues and remove carbon dioxide.\n\n### Cardiovascular anatomy\nThe four-chambered heart pumps blood through pulmonary and systemic circulations. Valves maintain one-way flow. Arteries carry blood away from the heart, veins return it and capillaries allow exchange with tissues.\n\n### Respiratory anatomy\nAir travels through the upper airway, trachea and bronchi to alveoli. Across the thin alveolar-capillary membrane, oxygen diffuses into blood and carbon dioxide diffuses into the alveoli.\n\n### Integrated physiology\nVentilation moves air, perfusion supplies pulmonary blood flow and haemoglobin transports oxygen. Heart rate, stroke volume, respiratory rate and vessel tone adjust to activity and illness.\n\n### Clinical links\nObserve respiratory effort, rate, oxygen saturation, pulse, blood pressure, skin colour and capillary refill together rather than interpreting one value in isolation.`,
    sk_codes: ["SK1", "SK2", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["NHS: How the Heart Works", "NHS: Lungs and Breathing", "OpenStax Anatomy and Physiology"],
    source: "NHS",
  },
  {
    title: "Musculoskeletal and Nervous Systems",
    category: "anatomy_physiology",
    content: `## Musculoskeletal and Nervous Systems\n\nThe skeletal, muscular and nervous systems combine to support posture, protect organs, create movement and coordinate responses.\n\n### Skeletal system\nBones provide support, mineral storage and blood-cell production. Joints permit controlled movement; cartilage reduces friction and ligaments connect bone to bone.\n\n### Muscular system\nSkeletal muscle contracts when motor neurones stimulate muscle fibres. Tendons connect muscle to bone. Agonist and antagonist muscle groups coordinate movement and joint stability.\n\n### Nervous system\nThe central nervous system comprises the brain and spinal cord. Peripheral sensory pathways carry information towards it, while motor pathways carry commands to muscles and glands. Autonomic pathways regulate functions such as heart rate and digestion.\n\n### Clinical links\nAssess symmetry, strength, sensation, balance, pain, range of movement and functional ability. Sudden unilateral weakness, facial droop or speech change requires immediate escalation.`,
    sk_codes: ["SK2", "SK4", "SK15"],
    performance_outcomes: ["PO4", "PO6"],
    references: ["NHS: Brain and Nerves", "NHS: Bones, Joints and Muscles", "OpenStax Anatomy and Physiology"],
    source: "NHS",
  },
  {
    title: "Sepsis — Dysregulated Response to Infection",
    category: "pathophysiology",
    content: `## Sepsis — Dysregulated Response to Infection\n\nSepsis is life-threatening organ dysfunction caused by a dysregulated response to infection. Inflammation, endothelial injury and abnormal clotting can impair microcirculation and tissue oxygen delivery.\n\n### Possible clinical pattern\n- New confusion or altered behaviour\n- Increased respiratory rate and work of breathing\n- Tachycardia, hypotension or prolonged capillary refill\n- Fever or abnormally low temperature\n- Reduced urine output, mottled skin or rising oxygen requirement\n\n### Why deterioration occurs\nVasodilation and capillary leakage reduce effective circulating volume. Cellular oxygen use becomes impaired and organ function may worsen rapidly.\n\n### Learner priorities\nUse ABCDE, record a complete set of observations, calculate NEWS2, identify likely infection sources and escalate immediately according to local sepsis guidance. Do not delay escalation while waiting for every sign to appear.`,
    sk_codes: ["SK1", "SK2", "SK6", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["NICE NG51: Sepsis", "UK Sepsis Trust: Clinical Tools", "NHS England: Deterioration"],
    source: "NICE",
  },
  {
    title: "Heart Failure and Fluid Overload",
    category: "pathophysiology",
    content: `## Heart Failure and Fluid Overload\n\nHeart failure occurs when the heart cannot pump or fill effectively enough to meet the body's needs. Compensatory mechanisms initially support circulation but can increase workload and fluid retention.\n\n### Left-sided effects\nRaised pressure behind the left ventricle contributes to pulmonary congestion, causing breathlessness, orthopnoea, reduced oxygen saturation and fine inspiratory crackles.\n\n### Right-sided effects\nSystemic venous congestion can cause peripheral oedema, raised jugular venous pressure, abdominal swelling and weight gain.\n\n### Compensation\nSympathetic activation increases heart rate and vasoconstriction. Renal sodium and water retention increases circulating volume but may worsen congestion.\n\n### Monitoring links\nObserve breathing, oxygen saturation, pulse, blood pressure, oedema, weight, fluid balance and urine output. Position for comfort and escalate new or worsening deterioration promptly.`,
    sk_codes: ["SK1", "SK2", "SK4", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["NICE NG106: Chronic Heart Failure", "British Heart Foundation: Heart Failure", "NHS: Heart Failure"],
    source: "NICE",
  },
  {
    title: "Understanding Clinical Abbreviations and Measurements",
    category: "terminology",
    content: `## Understanding Clinical Abbreviations and Measurements\n\nClinical shorthand saves time but can introduce risk. Use only locally approved abbreviations and write in full whenever meaning could be unclear.\n\n### Common observations\n- **RR:** respiratory rate, measured in breaths per minute\n- **SpO₂:** peripheral oxygen saturation, recorded as a percentage\n- **HR:** heart rate, measured in beats per minute\n- **BP:** blood pressure, recorded in mmHg\n- **Temp:** temperature, usually recorded in degrees Celsius\n- **AVPU:** Alert, responds to Voice, responds to Pain, Unresponsive\n- **NEWS2:** National Early Warning Score 2\n\n### Medicines and routes\nPO means by mouth, IV intravenous, IM intramuscular and SC subcutaneous. Avoid ambiguous dose abbreviations, trailing zeros and unclear decimal points.\n\n### Safe communication\nRead back unfamiliar terms, include units, use approved terminology and clarify rather than guessing.`,
    sk_codes: ["SK1", "SK6", "SK10"],
    performance_outcomes: ["PO4", "PO6"],
    references: ["NHS England: Safe Use of Abbreviations", "Royal College of Physicians: NEWS2", "NMC Code"],
    source: "NHS England",
  },
  {
    title: "Medical Word Building: Prefixes, Roots and Suffixes",
    category: "terminology",
    content: `## Medical Word Building\n\nMany clinical terms combine a prefix, a root describing a body structure or process, and a suffix describing a condition or procedure.\n\n### Useful prefixes\n- **brady-:** slow; bradycardia means a slow heart rate\n- **tachy-:** fast; tachypnoea means rapid breathing\n- **hypo-:** below or deficient; hypoglycaemia means low blood glucose\n- **hyper-:** above or excessive; hypertension means high blood pressure\n\n### Useful roots and suffixes\n- **cardi/o:** heart\n- **neur/o:** nerve\n- **haem/haemat/o:** blood\n- **-itis:** inflammation\n- **-ectomy:** surgical removal\n- **-algia:** pain\n- **-ology:** study of\n\n### Applying terminology\nBreak unfamiliar words into parts, confirm the meaning in an approved source and explain it to patients in plain language. Similar-looking terms can have very different meanings, so never infer a medication or diagnosis from the word alone.`,
    sk_codes: ["SK6", "SK10"],
    performance_outcomes: ["PO5", "PO6"],
    references: ["NHS Health A to Z", "OpenStax Medical Terminology", "NMC Code"],
    source: "NHS",
  },
];

export const PREBUILT_SCENARIOS = [
  {
    name: "Activities of Daily Living — Nurse Call Bell",
    description: "A group ward simulation where patients randomly use their call bells and named learners respond to person-centred activities of daily living before completing an SBAR handover.",
    difficulty: "guided",
    estimated_duration: 30,
    patient_name: "Multiple ward patients",
    patient_age: 70,
    patient_condition: "Stable ward patients requiring support with activities of daily living",
    patient_comorbidities: "Varies by allocated patient",
    patient_medications: "Refer to each patient's medication record",
    patient_allergies: "Refer to each patient's wristband and record",
    bed_number: "Multiple beds",
    initial_vitals: { rr: 16, spo2: 97, supplemental_o2: false, sbp: 124, hr: 78, avpu: "A", temp: 36.7 },
    initial_news2: 0,
    category: "activities_daily_living",
    call_bell_speed: "normal",
    adl_task_source: "pregenerated",
    adl_tasks: [],
    sk_codes: ["SK6", "SK7", "SK9", "SK15"],
    performance_outcomes: ["PO4", "PO6", "PO7", "PO9"],
    debrief_rationale: "Learners should respond promptly, introduce themselves, confirm identity and consent, follow the individual care plan, preserve dignity and independence, use appropriate infection prevention and moving-and-handling practice, document care, and communicate outcomes using SBAR.",
    is_custom: false,
  },
  {
    name: "Post-Op Deteriorating Patient",
    description: "A 68-year-old patient 6 hours post-hip replacement showing signs of deterioration. Assess, recognise deterioration, and escalate appropriately.",
    difficulty: "intermediate",
    estimated_duration: 20,
    patient_name: "Margaret Thompson",
    patient_age: 68,
    patient_condition: "Day 0 post-operative — right total hip replacement",
    patient_comorbidities: "Hypertension, Type 2 Diabetes, Osteoarthritis",
    patient_medications: "Paracetamol, Amlodipine, Metformin, Tramadol PRN, Enoxaparin (VTE prophylaxis)",
    patient_allergies: "Penicillin (rash)",
    bed_number: "Bed 3",
    initial_vitals: { rr: 22, spo2: 92, supplemental_o2: true, sbp: 95, hr: 110, avpu: "A", temp: 37.8 },
    initial_news2: 7,
    category: "deterioration",
    sk_codes: ["SK1", "SK2", "SK5", "SK6", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    debrief_rationale: "Margaret is showing signs of post-operative deterioration with a NEWS2 of 7 (HIGH). Key learning: early recognition of deterioration, appropriate escalation using SBAR, and the importance of VTE prophylaxis monitoring post-orthopaedic surgery.",
    is_custom: false,
  },
  {
    name: "MRSA Admission — Infection Control",
    description: "New admission to the ward has been flagged as MRSA positive. Implement appropriate infection control measures and manage the patient safely.",
    difficulty: "guided",
    estimated_duration: 15,
    patient_name: "James Wilson",
    patient_age: 54,
    patient_condition: "MRSA-positive admission for IV antibiotic therapy",
    patient_comorbidities: "Chronic kidney disease, Peripheral vascular disease",
    patient_medications: "Vancomycin (MRSA treatment), Ramipril, Furosemide",
    patient_allergies: "None known",
    bed_number: "Bed 1",
    initial_vitals: { rr: 18, spo2: 97, supplemental_o2: false, sbp: 128, hr: 82, avpu: "A", temp: 36.8 },
    initial_news2: 0,
    category: "infection_control",
    sk_codes: ["SK7", "SK9", "SK18"],
    performance_outcomes: ["PO7", "PO6"],
    debrief_rationale: "James requires source isolation in a side room with contact precautions. Key learning: correct PPE donning/doffing, hand hygiene using soap and water (not alcohol gel for C. diff but alcohol is fine for MRSA), waste management, and maintaining dignity while isolated.",
    is_custom: false,
  },
  {
    name: "Fluid Overload — Heart Failure",
    description: "An elderly patient with heart failure is showing signs of fluid overload. Assess and manage fluid balance appropriately.",
    difficulty: "intermediate",
    estimated_duration: 18,
    patient_name: "Dorothy Patel",
    patient_age: 79,
    patient_condition: "Acute decompensated heart failure — fluid overload",
    patient_comorbidities: "Heart failure (HFrEF), Atrial fibrillation, CKD stage 3",
    patient_medications: "Furosemide, Bisoprolol, Ramipril, Apixaban",
    patient_allergies: "Sulphonamides",
    bed_number: "Bed 2",
    initial_vitals: { rr: 24, spo2: 90, supplemental_o2: true, sbp: 168, hr: 96, avpu: "A", temp: 36.5 },
    initial_news2: 5,
    category: "fluid_management",
    sk_codes: ["SK1", "SK2", "SK4", "SK5", "SK15"],
    performance_outcomes: ["PO4", "PO9"],
    debrief_rationale: "Dorothy presents with fluid overload secondary to heart failure decompensation. Key learning: accurate fluid balance monitoring, recognising signs of overload (bibasal crackles, peripheral oedema, raised JVP), positioning upright, administering prescribed diuretics, and escalating to medical team.",
    is_custom: false,
  },
  {
    name: "Falls Risk — Confused Elderly Patient",
    description: "An 85-year-old patient with confusion is at high risk of falls. Conduct a falls risk assessment and implement prevention strategies.",
    difficulty: "guided",
    estimated_duration: 15,
    patient_name: "Albert Greene",
    patient_age: 85,
    patient_condition: "Admitted with confusion and recurrent falls",
    patient_comorbidities: "Dementia, Urinary tract infection, Previous stroke",
    patient_medications: "Donepezil, Aspirin, Atorvastatin, Co-codamol",
    patient_allergies: "Codeine (nausea)",
    bed_number: "Bed 4",
    initial_vitals: { rr: 20, spo2: 94, supplemental_o2: false, sbp: 142, hr: 88, avpu: "V", temp: 38.2 },
    initial_news2: 4,
    category: "falls_risk",
    sk_codes: ["SK4", "SK8", "SK9", "SK15"],
    performance_outcomes: ["PO5", "PO6"],
    debrief_rationale: "Albert is at high falls risk with confusion (AVPU = V) and an elevated temperature suggesting infection. Key learning: Morse Fall Scale assessment, implementing falls prevention bundle, investigating delirium causes (UTI), person-centred care for a confused patient, and safeguarding considerations.",
    is_custom: false,
  },
];