export const SK_CODES = {
  "SK1": "Perform and record clinical observations (vital signs, NEWS2)",
  "SK2": "Conduct structured ABCDE assessment",
  "SK3": "Develop care plans using SMART goals framework",
  "SK4": "Conduct clinical risk assessments (falls, pressure, VTE)",
  "SK5": "Maintain accurate fluid balance charts",
  "SK6": "Use SBAR communication for clinical handover",
  "SK7": "Apply infection prevention and control measures",
  "SK8": "Respond to safeguarding concerns (Care Act 2014)",
  "SK9": "Deliver person-centred care (CS1)",
  "SK10": "Communicate effectively using clinical terminology (CS2)",
  "SK11": "Work within MDT boundaries (CS3)",
  "SK12": "Reflect on clinical practice (CS4)",
  "SK13": "Research and apply evidence-based practice (CS5)",
  "SK14": "Present clinical information professionally (CS6)",
  "SK15": "Assist with activities of daily living",
  "SK16": "Administer medications safely (under supervision)",
  "SK17": "Manage deteriorating patient using escalation protocols",
  "SK18": "Complete accurate clinical documentation",
};

export const PERFORMANCE_OUTCOMES = {
  "PO1": "Core Area 1 — The Healthcare Sector",
  "PO2": "Core Area 2 — Health, Safety & Environmental Regulations",
  "PO3": "Core Area 3 — Managing Information & Data",
  "PO4": "Core Area 4 — Good Scientific & Clinical Practice",
  "PO5": "Core Area 5 — Providing Person-Centred Care",
  "PO6": "Core Area 6 — Health & Wellbeing",
  "PO7": "Core Area 7 — Safeguarding",
  "PO8": "Core Areas 8–9 — Science Concepts in Health",
  "PO9": "OS Part A — Supporting Healthcare (Mandatory Core)",
  "PO10": "OS Part B — Supporting the Adult Nursing Team",
};

export const SPEC_AREAS = [
  { code: "Area 1", title: "The Healthcare Sector", volume: "Core Paper 1" },
  { code: "Area 2", title: "Health, Safety & Environmental Regulations", volume: "Core Paper 1" },
  { code: "Area 3", title: "Managing Information & Data", volume: "Core Paper 1" },
  { code: "Area 4", title: "Good Scientific & Clinical Practice", volume: "Core Paper 1" },
  { code: "Area 5", title: "Providing Person-Centred Care", volume: "Core Paper 1" },
  { code: "Area 6", title: "Health & Wellbeing", volume: "Core Paper 1" },
  { code: "Area 7", title: "Safeguarding", volume: "Core Paper 1" },
  { code: "Area 8", title: "Core Science Concepts", volume: "Core Paper 2" },
  { code: "Area 9", title: "Further Science Concepts in Health", volume: "Core Paper 2" },
];

export const THEORY_MODULES = [
  {
    title: "Overview and Purpose of the T Level Qualification",
    spec_area: "Area 1",
    volume: "Vol 1",
    section: "1. Overview and Purpose",
    content: `## About the T Level Programme\n\nT Levels are two-year Level 3 study programmes that follow the study of GCSEs and Technical Awards, offering an alternative to A Levels and Apprenticeships. They combine classroom theory, practical learning, and a minimum of 315 hours of industry placement with an employer. Developed in collaboration with industry experts, they provide the knowledge and experience needed to progress to highly skilled employment, an apprenticeship, or higher-level study at university.\n\n## Qualification Purpose and Progression\n\nThe primary purpose of the T Level Technical Qualification in Health (Level 3) is to prepare students aged 16–19 for a career in the health sector. Upon completion, students are expected to demonstrate 'threshold competence' — possessing the core knowledge and skills required to enter healthcare support roles.\n\n## Career Pathways\n\nThis qualification aligns to the Level 3 Apprenticeship for Senior Healthcare Support Workers. It supports direct entry into roles such as:\n\n- Community Support Worker\n- Maternity Support Worker\n- Mental Health Support Worker\n- Senior Healthcare Support Worker\n- Therapy Assistant\n\n## Qualification Metrics\n\n- **Qualification Number (QN):** 610/7438/X\n- **First Teaching:** September 2026\n- **Total Guided Learning Hours (GLH):** 1080 hours (510 Core)\n- **Total Qualification Time (TQT):** 1800 hours (870 Core)\n\nThe qualification consists of two mandatory components split equally:\n1. **Core Component (50%)**: Core Paper 1 (36%), Core Paper 2 (24%), Employer Set Project (40%). Graded A*–E.\n2. **Occupational Specialism Component (50%)**: Supporting Healthcare OS Core (65%) + OS Pathway (35%). Graded Pass, Merit, Distinction.`,
    sk_codes: ["SK9"],
    performance_outcomes: ["PO1", "PO9"],
    references: ["T Level Health Specification Vol 1", "NHS England Career Framework"],
    estimated_duration: 15,
    order_index: 1,
  },
  {
    title: "Core Skills (CS1–CS6) and the Healthcare Sector Landscape",
    spec_area: "Area 2",
    volume: "Vol 2",
    section: "3. Core Skills & The Healthcare Sector Landscape",
    content: `## Core Skills Mapping (CS1–CS6)\n\n- **CS1: Person-Centred Care Skills** — Identifying individual needs, goals, preferences, and managing evidence-based risks within customised care plans.\n- **CS2: Communication** — Adapting techniques to overcome barriers, utilising active listening, and presenting clinical observations clearly using professional terminology.\n- **CS3: Team Working** — Understanding Multi-Disciplinary Team (MDT) boundaries, defining escalation pathways, and coordinating cross-setting care collaboration.\n- **CS4: Reflective Evaluation** — Critically evaluating own clinical practice, analysing feedback, and formulating structured action plans for development.\n- **CS5: Researching** — Synthesising evidence from multiple data sources to defend clinical rationale and utilising accurate referencing styles.\n- **CS6: Presenting** — Designing logically structured, professional presentations tailored to clinical or multidisciplinary audiences.\n\n## Historical Trajectory of the UK Healthcare Sector\n\n**1948 Foundations:** The National Health Service (NHS) was founded on 5 July 1948 under Health Minister Aneurin Bevan via the NHS Act 1946, introducing the first completely free service at the point of delivery.\n\n**Systemic Evolutions:** During the 1950s, financial demand forced the introduction of prescription, dental, and optical charges. The 1960s–1970s saw integrated hospital and community structures. The 2010s saw the NHS Long-Term Plan prioritising digital transformation, and the 2020s introduced Integrated Care Systems (ICSs) to synchronise health and social care seamlessly.\n\n## Tiers of Care\n\n- **Primary Care:** First point of contact for assessment and early intervention (e.g., GPs, pharmacists, dental services, walk-in clinics, NHS 111).\n- **Secondary Care:** Specialised, referral-based services usually accessed via primary care (e.g., general hospital services, emergency departments, inpatient units).\n- **Tertiary Care:** Highly specialised, long-term, or acute clinical intervention (e.g., intensive care units, neurosurgery, specialised burns units).`,
    sk_codes: ["SK9", "SK10", "SK11", "SK12", "SK13", "SK14"],
    performance_outcomes: ["PO2"],
    references: ["T Level Health Specification Vol 2", "NHS England: The NHS Constitution", "NHS Long Term Plan 2019"],
    estimated_duration: 20,
    order_index: 2,
  },
  {
    title: "Clinical Safety, Governance, and Legislative Frameworks",
    spec_area: "Area 3",
    volume: "Vol 2",
    section: "4. Clinical Safety, Governance, and Legislative Frameworks",
    content: `## Key National Health and Safety Legislations\n\n- **Health and Safety at Work Act 1974:** Mandates employers secure a safe working environment and employees take reasonable care of their own and others' safety.\n- **Manual Handling Operations Regulations 1992:** Standardises risk reduction protocols when repositioning individuals or transferring heavy mechanical stock.\n- **Control of Substances Hazardous to Health (COSHH) Regulations 2002:** Regulates safe management and exposure limitation for hazardous cleaning agents, specialised medications, or clinical biological waste.\n- **RIDDOR 2013:** Compels systematic reporting of serious workplace accidents, occupational illnesses, or mechanical equipment failures to the HSE.\n\n## Clinical Governance\n\nClinical governance is the system through which NHS organisations are accountable for continuously improving the quality of their services and safeguarding high standards of care. Key pillars include:\n\n- Risk management\n- Clinical audit\n- Evidence-based practice\n- Patient and public involvement\n- Staffing and staff management\n- Education and training\n- Clinical effectiveness`,
    sk_codes: ["SK7", "SK18"],
    performance_outcomes: ["PO3", "PO10"],
    references: ["T Level Health Specification Vol 2", "HSE: Health and Safety at Work Act 1974", "NHS England: Clinical Governance"],
    estimated_duration: 15,
    order_index: 3,
  },
  {
    title: "Data Architecture, Safeguarding, and Public Health",
    spec_area: "Area 5",
    volume: "Vol 2",
    section: "5. Data Architecture, Safeguarding, and Public Health",
    content: `## Information Governance Principles\n\n- **Data Protection Act 2018 & UK GDPR:** Establishes legal compliance regarding the lawful, fair, transparent, and accurate processing of sensitive patient health data.\n- **Caldicott Principles:** Outlines standard rules governing the sharing of confidential information, dictating that all data exchanges must be strictly justified, necessary, and restricted to minimal data sets.\n\n## Safeguarding Frameworks and Abuse Identification\n\n- **Care Act 2014:** Standardises statutory requirements to safeguard adults with care and support needs through six key principles:\n  1. **Empowerment** — People are supported and encouraged to make their own decisions.\n  2. **Prevention** — It is better to take action before harm occurs.\n  3. **Proportionality** — The least intrusive response appropriate to the risk presented.\n  4. **Protection** — Support and representation for those in greatest need.\n  5. **Partnership** — Local solutions through services working with their communities.\n  6. **Accountability** — Accountability and transparency in delivering safeguarding.\n\n- **The Prevent Duty Guidance 2023:** Instructs healthcare personnel to identify early behavioural indicators of radicalisation to support early intervention programmes.`,
    sk_codes: ["SK8", "SK18"],
    performance_outcomes: ["PO5", "PO10"],
    references: ["T Level Health Specification Vol 2", "Care Act 2014", "UK GDPR / Data Protection Act 2018", "NHS Caldicott Guardian Principles"],
    estimated_duration: 18,
    order_index: 4,
  },
  {
    title: "Cellular Biology, Biochemistry, and Enzymatic Kinetics",
    spec_area: "Area 8",
    volume: "Vol 3",
    section: "6. Cellular Biology, Biochemistry, and Enzymatic Kinetics",
    content: `## Postulates of Cell Theory\n\n1. All living organisms are composed of one or more functional cells.\n2. Cells constitute the basic structural and organisational unit of all living entities.\n3. All cells originate exclusively from pre-existing cells through division.\n\n## Ultrastructure of Eukaryotic Organelles\n\n- **Cell Surface Membrane:** Modeled by the fluid mosaic structure; controls selective cellular transport and displays cell surface antigens.\n- **Nucleus:** Houses genetic material (chromosomes/DNA) and dictates activities via gene expression.\n- **Mitochondria:** Double-membraned structures; serve as the site of aerobic respiration to synthesise Adenosine Triphosphate (ATP).\n- **Rough Endoplasmic Reticulum (RER):** Studded with ribosomes; coordinates protein translation, packaging, and internal transport.\n- **Golgi Apparatus:** Modifies, packages, and sorts macromolecular proteins for secretory export.\n\n## Macromolecular Biochemistry\n\n**Equation:** Triglyceride = 1 Glycerol + 3 Fatty Acids\n\nProteins are structurally evaluated from primary amino acid configurations to complex quaternary interactions. Carbohydrates function as prime metabolic fuels, storing energy as glycogen. Lipids form cellular bilayers via amphipathic phospholipids, featuring a hydrophilic head and a hydrophobic tail. Enzymes operate as biological catalysts, accelerating metabolic reactions by lowering activation energy requirements.`,
    sk_codes: ["SK17"],
    performance_outcomes: ["PO8"],
    references: ["T Level Health Specification Vol 3", "NHS England: Cellular Biology Reference", "Clinical Skills.net: Biochemistry Fundamentals"],
    estimated_duration: 20,
    order_index: 5,
  },
  {
    title: "Human Pathophysiology, Homeostasis, and Disease Classification",
    spec_area: "Area 9",
    volume: "Vol 3",
    section: "7. Human Pathophysiology, Homeostasis, and Disease Classification",
    content: `## Pathogenic Transmission Dynamics\n\nPathogens are defined as disease-causing microorganisms. Transmission follows direct routes (physical touch, bodily fluids, droplet inhalation) or indirect vehicles (contaminated surfaces, vector bites, faecal-oral ingestion).\n\n- **Healthcare-Associated Infections (HCAIs):** Infections acquired during clinical care, including Methicillin-Resistant Staphylococcus Aureus (MRSA) and Clostridium difficile (C. diff).\n\n## Immunological Defence Systems\n\n- **Non-Specific Defenses:** The body's initial, generalized response (e.g., skin barriers, mucous membranes, stomach acid, inflammation, and phagocytosis).\n- **Specific Adaptive Immune Response:** Mediated by T-cells (cell-mediated destruction) and B-cells (humoral antibody synthesis). Immunological memory forms the foundational mechanism of clinical vaccinations.\n\n## Homeostatic Regulation and Diagnostic Classification Systems\n\nHomeostasis maintains stable internal variables (core temperature, blood glucose, blood pressure, osmoregulation) through negative feedback loops. Failure disrupts physiological systems, leading to complications like chronic metabolic disease.\n\n- **ICD System:** Codes physical and mental health conditions for epidemiological analysis.\n- **DSM System:** Standardises criteria for psychological and psychiatric diagnoses.\n- **SNOMED CT:** Provides a common clinical vocabulary for electronic health records.`,
    sk_codes: ["SK7", "SK17"],
    performance_outcomes: ["PO7", "PO8"],
    references: ["T Level Health Specification Vol 3", "NHS England: Infection Prevention Control", "Clinical Skills.net: HCAI Management", "WHO: Disease Classification"],
    estimated_duration: 20,
    order_index: 6,
  },
];

export const KNOWLEDGE_ARTICLES = [
  {
    title: "ABCDE Assessment Approach",
    category: "clinical_procedure",
    content: `## ABCDE Assessment\n\nThe ABCDE approach is a systematic method for assessing and treating acutely unwell patients.\n\n### A — Airway\nAssess patency. Look for signs of obstruction, listen for stridor/gurgling. Consider airway adjuncts (OPA/NPA) if compromised.\n\n### B — Breathing\nAssess respiratory rate, effort, chest movement, oxygen saturation. Administer high-flow oxygen if hypoxic.\n\n### C — Circulation\nAssess heart rate, blood pressure, capillary refill, skin colour/temperature. Establish IV access. Consider fluid resuscitation.\n\n### D — Disability\nAssess conscious level using AVPU or GCS. Check pupils, blood glucose.\n\n### E — Exposure\nFully expose the patient to identify rashes, wounds, bleeding. Maintain dignity and warmth.`,
    sk_codes: ["SK2", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["Resuscitation Council UK: ABCDE Approach", "Clinical Skills.net: ABCDE Assessment", "NHS England: Deteriorating Patient"],
    source: "Clinical Skills.net",
  },
  {
    title: "NEWS2 (National Early Warning Score)",
    category: "clinical_procedure",
    content: `## NEWS2 Scoring System\n\nNEWS2 is a tool for standardising the assessment of acute illness severity. It aggregates scores across 7 physiological parameters:\n\n1. Respiratory rate\n2. Oxygen saturation (SpO₂)\n3. Use of supplemental oxygen\n4. Systolic blood pressure\n5. Pulse rate\n6. Level of consciousness (AVPU: Alert, Voice, Pain, Unresponsive)\n7. Temperature\n\n### Escalation Bands\n\n- **Score 0–4 (Low):** Routine monitoring. Minimum 12 hourly if single-parameter trigger, 4–6 hourly otherwise.\n- **Score 5–6 (Medium):** Urgent ward-based review by registered nurse/clinician. Inform registrar.\n- **Score 7+ (High):** Emergency assessment by clinical team with critical care competencies. ICU outreach.`,
    sk_codes: ["SK1", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["Royal College of Physicians: NEWS2 Guidance", "NHS England: Deteriorating Patient Recognition", "Clinical Skills.net: NEWS2"],
    source: "NHS England",
  },
  {
    title: "SBAR Communication Framework",
    category: "clinical_procedure",
    content: `## SBAR Handover Communication\n\nSBAR is a structured method for communicating clinical information clearly and efficiently.\n\n### S — Situation\nState your name, role, patient name, location, and the current concern briefly.\n\n### B — Background\nProvide relevant clinical history: diagnosis, recent events, current observations.\n\n### A — Assessment\nShare your clinical assessment: vital signs, NEWS2 score, what you think is happening.\n\n### R — Recommendation\nState what you need: review, escalation, specific intervention, timeframe.`,
    sk_codes: ["SK6", "SK10"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["NHS England: SBAR Communication Tool", "Clinical Skills.net: Clinical Handover", "RCN: Handover Best Practice"],
    source: "NHS England",
  },
  {
    title: "Infection Prevention and Control (IPC)",
    category: "governance",
    content: `## Infection Prevention and Control\n\nStandard precautions are the basic level of infection control that should be practised for all patients.\n\n### Hand Hygiene\nThe '5 Moments for Hand Hygiene' (WHO):\n1. Before touching a patient\n2. Before clean/aseptic procedures\n3. After body fluid exposure risk\n4. After touching a patient\n5. After touching patient surroundings\n\n### PPE\n- Gloves and aprons for standard care\n- Fluid-repellent surgical masks, eye protection, gowns for aerosol-generating procedures\n- Always perform hand hygiene before and after PPE use\n\n### HCAIs\n- MRSA: Screen on admission, isolate positive cases, use contact precautions\n- C. difficile: Isolate, use soap and water (not alcohol gel) for hand hygiene`,
    sk_codes: ["SK7"],
    performance_outcomes: ["PO7"],
    references: ["NHS England: IPC Manual", "WHO: 5 Moments for Hand Hygiene", "Clinical Skills.net: IPC Procedures"],
    source: "NHS England",
  },
  {
    title: "Pressure Ulcer Prevention — Waterlow Assessment",
    category: "clinical_procedure",
    content: `## Waterlow Risk Assessment\n\nThe Waterlow score assesses pressure ulcer risk across multiple factors:\n\n- Build/weight (BMI)\n- Skin type (visual risk areas)\n- Sex and age\n- Continence\n- Mobility\n- Special risks (tissue malnutrition, neurological deficit, major surgery/trauma)\n- Medication\n\n### Risk Bands\n- **10+**: At risk\n- **15+**: High risk\n- **20+**: Very high risk\n\n### Interventions\n- Reposition every 2 hours (or more frequently for high risk)\n- Use pressure-relieving mattresses/cushions\n- Keep skin clean and dry\n- Ensure adequate nutrition and hydration\n- Document all repositioning and skin assessments`,
    sk_codes: ["SK4", "SK15"],
    performance_outcomes: ["PO4", "PO6", "PO9"],
    references: ["Clinical Skills.net: Pressure Ulcer Prevention", "NHS England: Tissue Viability", "NICE CG179: Pressure Ulcers"],
    source: "Clinical Skills.net",
  },
  {
    title: "Falls Risk Assessment — Morse Fall Scale",
    category: "clinical_procedure",
    content: `## Morse Fall Scale\n\nThe Morse Fall Scale assesses fall risk based on six variables:\n\n1. History of falling (25 pts)\n2. Secondary diagnosis (15 pts)\n3. Ambulatory aid (0–30 pts)\n4. IV therapy/heparin lock (20 pts)\n5. Gait/transferring (0–20 pts)\n6. Mental status (0–15 pts)\n\n### Risk Levels\n- **0–24**: Low risk — standard fall prevention measures\n- **25–50**: Moderate risk — yellow wristband, bed alarm consideration\n- **51+**: High risk — red wristband, hourly rounding, bed alarm, referral to falls team\n\n### Prevention Strategies\n- Ensure call bell within reach\n- Keep bed in lowest position\n- Non-slip footwear\n- Adequate lighting\n- Remove trip hazards`,
    sk_codes: ["SK4"],
    performance_outcomes: ["PO4", "PO6"],
    references: ["Clinical Skills.net: Falls Assessment", "NICE CG161: Falls Assessment", "NHS England: Falls Prevention"],
    source: "Clinical Skills.net",
  },
];

export const PREBUILT_SCENARIOS = [
  {
    name: "Post-Op Deteriorating Patient",
    description: "A 68-year-old patient 6 hours post-hip replacement showing signs of deterioration. Assess, recognise deterioration, and escalate appropriately.",
    difficulty: "intermediate",
    estimated_duration: 20,
    patient_name: "Margaret Thompson",
    patient_age: 68,
    patient_condition: "Day 0 post-operative — right total hip replacement",
    patient_comorbidities: "Hypertension, Type 2 Diabetes, Osteoarthritis",
    patient_medications: "Paracetamol, Amlodipine, Metformin, Tramadol PRN, Enoxaparin (VTE prophylaxis)",
    patient_allergies: "Penicillin (rash)",
    bed_number: "Bed 3",
    initial_vitals: { rr: 22, spo2: 92, supplemental_o2: true, sbp: 95, hr: 110, avpu: "A", temp: 37.8 },
    initial_news2: 7,
    category: "deterioration",
    sk_codes: ["SK1", "SK2", "SK5", "SK6", "SK17"],
    performance_outcomes: ["PO4", "PO9"],
    debrief_rationale: "Margaret is showing signs of post-operative deterioration with a NEWS2 of 7 (HIGH). Key learning: early recognition of deterioration, appropriate escalation using SBAR, and the importance of VTE prophylaxis monitoring post-orthopaedic surgery.",
    is_custom: false,
  },
  {
    name: "MRSA Admission — Infection Control",
    description: "New admission to the ward has been flagged as MRSA positive. Implement appropriate infection control measures and manage the patient safely.",
    difficulty: "guided",
    estimated_duration: 15,
    patient_name: "James Wilson",
    patient_age: 54,
    patient_condition: "MRSA-positive admission for IV antibiotic therapy",
    patient_comorbidities: "Chronic kidney disease, Peripheral vascular disease",
    patient_medications: "Vancomycin (MRSA treatment), Ramipril, Furosemide",
    patient_allergies: "None known",
    bed_number: "Bed 1",
    initial_vitals: { rr: 18, spo2: 97, supplemental_o2: false, sbp: 128, hr: 82, avpu: "A", temp: 36.8 },
    initial_news2: 0,
    category: "infection_control",
    sk_codes: ["SK7", "SK9", "SK18"],
    performance_outcomes: ["PO7", "PO6"],
    debrief_rationale: "James requires source isolation in a side room with contact precautions. Key learning: correct PPE donning/doffing, hand hygiene using soap and water (not alcohol gel for C. diff but alcohol is fine for MRSA), waste management, and maintaining dignity while isolated.",
    is_custom: false,
  },
  {
    name: "Fluid Overload — Heart Failure",
    description: "An elderly patient with heart failure is showing signs of fluid overload. Assess and manage fluid balance appropriately.",
    difficulty: "intermediate",
    estimated_duration: 18,
    patient_name: "Dorothy Patel",
    patient_age: 79,
    patient_condition: "Acute decompensated heart failure — fluid overload",
    patient_comorbidities: "Heart failure (HFrEF), Atrial fibrillation, CKD stage 3",
    patient_medications: "Furosemide, Bisoprolol, Ramipril, Apixaban",
    patient_allergies: "Sulphonamides",
    bed_number: "Bed 2",
    initial_vitals: { rr: 24, spo2: 90, supplemental_o2: true, sbp: 168, hr: 96, avpu: "A", temp: 36.5 },
    initial_news2: 5,
    category: "fluid_management",
    sk_codes: ["SK1", "SK2", "SK4", "SK5", "SK15"],
    performance_outcomes: ["PO4", "PO9"],
    debrief_rationale: "Dorothy presents with fluid overload secondary to heart failure decompensation. Key learning: accurate fluid balance monitoring, recognising signs of overload (bibasal crackles, peripheral oedema, raised JVP), positioning upright, administering prescribed diuretics, and escalating to medical team.",
    is_custom: false,
  },
  {
    name: "Falls Risk — Confused Elderly Patient",
    description: "An 85-year-old patient with confusion is at high risk of falls. Conduct a falls risk assessment and implement prevention strategies.",
    difficulty: "guided",
    estimated_duration: 15,
    patient_name: "Albert Greene",
    patient_age: 85,
    patient_condition: "Admitted with confusion and recurrent falls",
    patient_comorbidities: "Dementia, Urinary tract infection, Previous stroke",
    patient_medications: "Donepezil, Aspirin, Atorvastatin, Co-codamol",
    patient_allergies: "Codeine (nausea)",
    bed_number: "Bed 4",
    initial_vitals: { rr: 20, spo2: 94, supplemental_o2: false, sbp: 142, hr: 88, avpu: "V", temp: 38.2 },
    initial_news2: 4,
    category: "falls_risk",
    sk_codes: ["SK4", "SK8", "SK9", "SK15"],
    performance_outcomes: ["PO5", "PO6"],
    debrief_rationale: "Albert is at high falls risk with confusion (AVPU = V) and an elevated temperature suggesting infection. Key learning: Morse Fall Scale assessment, implementing falls prevention bundle, investigating delirium causes (UTI), person-centred care for a confused patient, and safeguarding considerations.",
    is_custom: false,
  },
];