// Complete T Level Health theory modules — all 9 Core spec areas (Core Paper 1 + Core Paper 2)
// Each module includes 20 knowledge-check questions mapped to the Pearson specification.
// Aligned to: T Level Technical Qualification in Health (QN 610/7438/X), first teaching Sep 2026.

export const THEORY_MODULES = [
  // ───────────────────────────────── AREA 1 ─────────────────────────────────
  {
    title: "The Healthcare Sector",
    spec_area: "Area 1",
    volume: "Core Paper 1",
    section: "Core Area 1 — The Healthcare Sector",
    content: `## The T Level Technical Qualification in Health\n\nT Levels are two-year Level 3 study programmes for students aged 16–19, combining classroom theory, practical learning, and a minimum **315-hour industry placement**. Developed with industry experts, they prepare students for skilled employment, apprenticeships, or higher education.\n\n## Qualification Metrics\n\n- **Qualification Number (QN):** 610/7438/X\n- **First Teaching:** September 2026\n- **Total Guided Learning Hours (GLH):** 1080 hours (510 Core)\n- **Total Qualification Time (TQT):** 1800 hours (870 Core)\n\nTwo mandatory components, equally weighted:\n1. **Core Component (50%)** — Core Paper 1 (36%), Core Paper 2 (24%), Employer Set Project (40%). Graded A*–E.\n2. **Occupational Specialism (50%)** — OS Core (65%) + OS Pathway (35%). Graded Pass, Merit, Distinction.\n\n## Area 1: The Healthcare Sector\n\nThis area covers the structure and organisation of the UK healthcare sector, the role of the NHS, private and voluntary providers, and career pathways in health.\n\n### Key Topics\n- Structure of the NHS (primary, secondary, tertiary care)\n- Role of private and voluntary sector providers\n- Job roles, career pathways and the healthcare workforce\n- The NHS Constitution and its values\n- Healthcare regulation and professional bodies (NMC, GMC, HCPC)\n\n### The NHS\n- Founded in 1948 on the principle of healthcare free at the point of need.\n- Funded through general taxation; commissioned by integrated care boards (ICBs).\n- **Primary care:** GP, pharmacy, dentistry, optometry, community nursing.\n- **Secondary care:** planned hospital care, acute trusts, A&E, maternity.\n- **Tertiary care:** specialist regional/national services (e.g. transplant, neurosurgery).\n\n### The NHS Constitution\nSix values: working together for patients, respect and dignity, commitment to quality of care, compassion, improving lives, everyone counts.\n\n### Regulation & Professional Bodies\n- **CQC** — regulates and inspects health and adult social care providers.\n- **NMC** — regulates nurses and midwives.\n- **GMC** — regulates doctors.\n- **HCPC** — regulates allied health professionals.\n\n### Threshold Competence\nUpon completion, students demonstrate 'threshold competence' — the core knowledge and skills to enter healthcare support roles such as Senior Healthcare Support Worker, Therapy Assistant, or Mental Health Support Worker.`,
    sk_codes: ["SK9"],
    performance_outcomes: ["PO1", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 1", "NHS Constitution (England)", "NHS England Career Framework", "CQC: How We Regulate"],
    estimated_duration: 15,
    order_index: 1,
    knowledge_checks: [
      { question: "What does T Level Health QN 610/7438/X stand for?", options: ["Qualification Number", "Quality Notice", "Quota Nominal", "Quantitative Norm"], correct: "Qualification Number" },
      { question: "What is the minimum industry placement duration for a T Level?", options: ["45 hours", "100 hours", "315 hours", "500 hours"], correct: "315 hours" },
      { question: "Total Qualification Time (TQT) for the Core is:", options: ["510 hours", "870 hours", "1080 hours", "1800 hours"], correct: "870 hours" },
      { question: "What percentage of the Core component is the Employer Set Project?", options: ["20%", "40%", "50%", "65%"], correct: "40%" },
      { question: "Which body inspects and regulates health and adult social care providers in England?", options: ["NMC", "CQC", "GMC", "HCPC"], correct: "CQC" },
      { question: "Which body regulates nurses and midwives?", options: ["GMC", "HCPC", "NMC", "CQC"], correct: "NMC" },
      { question: "GP, pharmacy, dentistry and community nursing are examples of:", options: ["Tertiary care", "Secondary care", "Primary care", "Quaternary care"], correct: "Primary care" },
      { question: "Acute hospital trusts and A&E departments are part of which care tier?", options: ["Primary", "Secondary", "Tertiary", "Community"], correct: "Secondary" },
      { question: "In what year was the NHS founded?", options: ["1908", "1948", "1974", "1998"], correct: "1948" },
      { question: "The NHS is primarily funded through:", options: ["Private insurance", "General taxation", "Patient fees", "Charitable donations"], correct: "General taxation" },
      { question: "Which of these is an NHS Constitution value?", options: ["Compassion", "Profitability", "Competition", "Exclusivity"], correct: "Compassion" },
      { question: "Who commissions NHS services in England?", options: ["Local councils", "Integrated Care Boards", "GMC", "CQC"], correct: "Integrated Care Boards" },
      { question: "T Levels are aimed at students aged:", options: ["11–14", "16–19", "21–25", "25+"], correct: "16–19" },
      { question: "Core Paper 1 contributes what percentage of the Core component?", options: ["24%", "36%", "40%", "50%"], correct: "36%" },
      { question: "The Core component is graded:", options: ["Pass/Merit/Distinction", "A*–E", "1–9", "Gold/Silver/Bronze"], correct: "A*–E" },
      { question: "A Senior Healthcare Support Worker role is an example of:", options: ["Threshold competence", "Consultant grade", "Pre-registration doctor", "Tertiary specialist"], correct: "Threshold competence" },
      { question: "Transplant and neurosurgery are examples of which care tier?", options: ["Primary", "Secondary", "Tertiary", "Self-care"], correct: "Tertiary" },
      { question: "Which body regulates doctors?", options: ["NMC", "GMC", "HCPC", "CQC"], correct: "GMC" },
      { question: "Which body regulates allied health professionals such as physiotherapists?", options: ["GMC", "NMC", "HCPC", "CQC"], correct: "HCPC" },
      { question: "T Levels combine classroom theory, practical learning and:", options: ["A paid salary", "An industry placement", "A university degree", "Online-only study"], correct: "An industry placement" },
    ],
  },

  // ───────────────────────────────── AREA 2 ─────────────────────────────────
  {
    title: "Health, Safety & Environmental Regulations",
    spec_area: "Area 2",
    volume: "Core Paper 1",
    section: "Core Area 2 — Health, Safety & Environmental Regulations",
    content: `## Area 2: Health, Safety & Environmental Regulations\n\nThis area covers the legislation, regulations and guidance that govern health, safety and environmental practice in healthcare settings.\n\n### Key Legislation\n- **Health and Safety at Work Act 1974 (HASAWA):** Employers must provide a safe working environment; employees must take reasonable care of their own and others' safety.\n- **Manual Handling Operations Regulations 1992:** Risk reduction protocols for repositioning individuals or transferring heavy stock (hierarchy: avoid, assess, reduce).\n- **Control of Substances Hazardous to Health (COSHH) 2002:** Safe management and exposure limitation for hazardous cleaning agents, medications, or clinical waste.\n- **Reporting of Injuries, Diseases and Dangerous Occurrences Regulations (RIDDOR) 2013:** Systematic reporting of serious workplace accidents, occupational illnesses, or equipment failures to the HSE.\n- **Provision and Use of Work Equipment Regulations (PUWER) 1998:** Safe use and maintenance of work equipment.\n- **Management of Health and Safety at Work Regulations 1999:** requires employers to carry out risk assessments.\n\n### Risk Assessment\nFive steps: identify hazards; decide who might be harmed and how; evaluate risks and implement controls; record findings; review and update. **Risk = Likelihood × Severity.**\n\n### Environmental Considerations\n- Safe disposal of clinical waste (sharps, pharmaceutical, infectious waste streams).\n- Sustainability and environmental impact of healthcare practice.\n\n### Clinical Governance\nA system through which NHS organisations are accountable for continuously improving the quality of services. Key pillars: risk management, clinical audit, evidence-based practice, patient involvement, staffing, education, and clinical effectiveness.\n\n### Infection Control Legislation\n- Health and Social Care Act 2008: Code of Practice on infection prevention.\n- The Health and Social Care Act 2008 (Regulated Activities) Regulations 2014.`,
    sk_codes: ["SK7", "SK18"],
    performance_outcomes: ["PO2", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 2", "HASAWA 1974", "HSE: COSHH & RIDDOR", "NHS England: Clinical Governance", "Health and Social Care Act 2008"],
    estimated_duration: 20,
    order_index: 2,
    knowledge_checks: [
      { question: "Which Act places a duty on employers to ensure a safe working environment?", options: ["HASAWA 1974", "COSHH 2002", "RIDDOR 2013", "PUWER 1998"], correct: "HASAWA 1974" },
      { question: "RIDDOR 2013 requires reporting of:", options: ["All near misses only", "Serious accidents, diseases and dangerous occurrences", "Staff holidays", "Patient complaints"], correct: "Serious accidents, diseases and dangerous occurrences" },
      { question: "COSHH 2002 relates to:", options: ["Manual handling", "Substances hazardous to health", "Work equipment", "Fire safety"], correct: "Substances hazardous to health" },
      { question: "What is the formula for risk?", options: ["Likelihood + Severity", "Likelihood × Severity", "Likelihood ÷ Severity", "Severity − Likelihood"], correct: "Likelihood × Severity" },
      { question: "The correct manual handling hierarchy is:", options: ["Reduce, Avoid, Assess", "Avoid, Assess, Reduce", "Assess, Avoid, Reduce", "Reduce, Assess, Avoid"], correct: "Avoid, Assess, Reduce" },
      { question: "Which regulation governs safe use and maintenance of work equipment?", options: ["PUWER 1998", "RIDDOR 2013", "COSHH 2002", "HASAWA 1974"], correct: "PUWER 1998" },
      { question: "How many steps are in the HSE risk assessment process?", options: ["3", "4", "5", "7"], correct: "5" },
      { question: "Clinical governance is primarily about:", options: ["Maximising profit", "Continuous quality improvement", "Reducing staff numbers", "Private partnerships"], correct: "Continuous quality improvement" },
      { question: "Which is NOT a pillar of clinical governance?", options: ["Clinical audit", "Risk management", "Marketing", "Evidence-based practice"], correct: "Marketing" },
      { question: "Sharps should be disposed of in:", options: ["Yellow clinical waste bag", "Black domestic bin", "Sharps bin", "Cardboard box"], correct: "Sharps bin" },
      { question: "Who enforces RIDDOR reporting?", options: ["CQC", "HSE", "NMC", "GMC"], correct: "HSE" },
      { question: "Under HASAWA, employees must:", options: ["Take reasonable care of their own and others' safety", "Ignore hazards not in their job description", "Only work when supervised", "Provide their own PPE"], correct: "Take reasonable care of their own and others' safety" },
      { question: "The Management of Health and Safety at Work Regulations 1999 require employers to:", options: ["Pay hazard pay", "Carry out risk assessments", "Provide free meals", "Limit shifts to 4 hours"], correct: "Carry out risk assessments" },
      { question: "Pharmaceutical waste is disposed of via:", options: ["Black bag", "Sharps bin", "Yellow pharmaceutical waste stream", "Down the sink"], correct: "Yellow pharmaceutical waste stream" },
      { question: "Which Act includes a Code of Practice on infection prevention?", options: ["Health and Social Care Act 2008", "HASAWA 1974", "Equality Act 2010", "Care Act 2014"], correct: "Health and Social Care Act 2008" },
      { question: "A dynamic risk assessment is:", options: ["A one-off written assessment", "A continuous on-the-spot assessment", "An annual audit", "A financial review"], correct: "A continuous on-the-spot assessment" },
      { question: "Infectious clinical waste is typically colour-coded:", options: ["Black", "Orange/yellow", "Clear", "Blue"], correct: "Orange/yellow" },
      { question: "PUWER 1998 requires work equipment to be:", options: ["Suitable, maintained and inspected", "Imported cheaply", "Operated without training", "Shared by all staff at once"], correct: "Suitable, maintained and inspected" },
      { question: "Clinical audit is a component of:", options: ["Clinical governance", "RIDDOR", "COSHH", "Manual handling"], correct: "Clinical governance" },
      { question: "Sustainability in healthcare practice relates to which area?", options: ["Area 1", "Area 2", "Area 8", "Area 9"], correct: "Area 2" },
    ],
  },

  // ───────────────────────────────── AREA 3 ─────────────────────────────────
  {
    title: "Managing Information & Data",
    spec_area: "Area 3",
    volume: "Core Paper 1",
    section: "Core Area 3 — Managing Information & Data",
    content: `## Area 3: Managing Information & Data\n\nThis area covers how information and data are managed, protected, and used in healthcare settings.\n\n### Information Governance\n- **Data Protection Act 2018 & UK GDPR:** Lawful, fair, transparent, and accurate processing of sensitive patient health data.\n- **Caldicott Principles:** Rules governing the sharing of confidential information — all data exchanges must be justified, necessary, and restricted to minimal data sets.\n- **NHS Data Security and Protection Standards:** Mandatory for all organisations handling NHS patient data.\n\n### The Caldicott Principles\n1. Justify the purpose of using confidential information.\n2. Use the minimum necessary confidential information.\n3. Access to confidential information should be on a strict need-to-know basis.\n4. Everyone should understand their responsibilities.\n5. Understand and comply with the law.\n6. The duty to share information can be as important as the duty to protect confidentiality.\n7. The duty to share information for direct care can be as important as the duty to protect confidentiality.\n8. Inform patients and service users about how their information is used.\n\n### Data Quality & Accuracy\n- Accurate, timely, and complete clinical records.\n- Use of standardised classification systems (ICD-10/11, SNOMED CT, OPCS-4).\n- Audit trails for all data access and amendment.\n\n### Confidentiality & Disclosure\n- Patient consent for information sharing.\n- Exceptions: where there is a legal requirement, or a safeguarding/public interest justification.\n- Never discuss patient information in public areas or on social media.\n\n### Records Management\n- NHS Records Management Code of Practice 2021.\n- Different record types:纸质 and electronic health records (EPR/EHR).`,
    sk_codes: ["SK8", "SK18"],
    performance_outcomes: ["PO3", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 3", "Data Protection Act 2018 & UK GDPR", "NHS Caldicott Guardian Principles", "NHS Records Management Code of Practice 2021"],
    estimated_duration: 15,
    order_index: 3,
    knowledge_checks: [
      { question: "How many Caldicott Principles are there?", options: ["6", "7", "8", "10"], correct: "8" },
      { question: "Which Act governs data protection in the UK alongside UK GDPR?", options: ["Data Protection Act 2018", "Caldicott Act 1997", "Freedom of Information Act 2000", "Equality Act 2010"], correct: "Data Protection Act 2018" },
      { question: "The first Caldicott Principle is to:", options: ["Share all data freely", "Justify the purpose of using confidential information", "Store data forever", "Avoid electronic records"], correct: "Justify the purpose of using confidential information" },
      { question: "SNOMED CT is a:", options: ["Clinical terminology/vocabulary", "Ward layout", "Drug brand", "Staff roster"], correct: "Clinical terminology/vocabulary" },
      { question: "ICD-10/11 is used to:", options: ["Classify diseases", "Schedule staff", "Order equipment", "Bill patients"], correct: "Classify diseases" },
      { question: "Which is an exception to confidentiality?", options: ["A safeguarding concern", "A gossip magazine request", "Personal curiosity", "Staff convenience"], correct: "A safeguarding concern" },
      { question: "The NHS Data Security and Protection Standards are:", options: ["Optional guidance", "Mandatory for NHS data handlers", "Only for private companies", "Only for doctors"], correct: "Mandatory for NHS data handlers" },
      { question: "The Caldicott Guardian is responsible for:", options: ["Protecting patient confidentiality", "Cleaning wards", "Ordering medication", "Scheduling surgery"], correct: "Protecting patient confidentiality" },
      { question: "Good data quality should be:", options: ["Accurate, timely and complete", "Vague and delayed", "Partial and unverified", "Verbal only"], correct: "Accurate, timely and complete" },
      { question: "An audit trail is used to:", options: ["Track data access and amendments", "Guide visitors", "Measure medication doses", "Plan meals"], correct: "Track data access and amendments" },
      { question: "Patient consent for information sharing must be:", options: ["Informed and voluntary", "Coerced", "Assumed", "From a relative only"], correct: "Informed and voluntary" },
      { question: "Which is a data classification system?", options: ["OPCS-4", "Morse", "Waterlow", "SBAR"], correct: "OPCS-4" },
      { question: "Discussing patient information on social media is:", options: ["Acceptable if anonymous", "Never acceptable", "Acceptable with consent of friends", "Acceptable on private accounts"], correct: "Never acceptable" },
      { question: "UK GDPR requires data processing to be:", options: ["Lawful, fair and transparent", "Secret and unregulated", "Profitable", "Unlimited"], correct: "Lawful, fair and transparent" },
      { question: "The 'minimum necessary' principle means:", options: ["Use the least data needed for the purpose", "Store everything just in case", "Delete after one use", "Share with everyone"], correct: "Use the least data needed for the purpose" },
      { question: "An electronic patient record is also known as:", options: ["EPR/EHR", "ECG", "EPRR", "e-GIF"], correct: "EPR/EHR" },
      { question: "Which document guides NHS records retention?", options: ["Records Management Code of Practice 2021", "Caldicott Report 1997", "HASAWA 1974", "NMC Code"], correct: "Records Management Code of Practice 2021" },
      { question: "A data breach must be:", options: ["Reported and managed promptly", "Ignored if minor", "Discussed only with colleagues", "Hidden from patients"], correct: "Reported and managed promptly" },
      { question: "The need-to-know basis principle limits:", options: ["Access to confidential information", "Number of staff on a ward", "Patient visiting hours", "Medication doses"], correct: "Access to confidential information" },
      { question: "Health data is classed under UK GDPR as:", options: ["Special category data", "Public data", "Anonymous data", "Financial data"], correct: "Special category data" },
    ],
  },

  // ───────────────────────────────── AREA 4 (NEW) ─────────────────────────────────
  {
    title: "Good Scientific & Clinical Practice",
    spec_area: "Area 4",
    volume: "Core Paper 1",
    section: "Core Area 4 — Good Scientific & Clinical Practice",
    content: `## Area 4: Good Scientific & Clinical Practice\n\nThis area covers the principles of good scientific and clinical practice that underpin safe, effective, and ethical healthcare delivery.\n\n### Professional Values & Standards\n- **The 6 Cs** (NHS Compassion in Practice): Care, Compassion, Competence, Communication, Courage, Commitment.\n- **NMC Code:** Prioritise people, practise effectively, preserve safety, promote professionalism and trust.\n- Accountability and duty of candour.\n\n### Evidence-Based Practice\n- Integrating best available research evidence, clinical expertise, and patient values.\n- Hierarchy of evidence: systematic reviews/meta-analyses > RCTs > cohort studies > case-control > expert opinion.\n- Using guidelines (NICE) and clinical standards to inform practice.\n\n### Clinical Skills & Observations\n- Accurate measurement and recording of vital signs (NEWS2).\n- Aseptic non-touch technique (ANTT) for invasive procedures.\n- Safe administration of medicines (the 'rights': right patient, drug, dose, route, time, documentation).\n\n### Quality Improvement\n- Plan-Do-Study-Act (PDSA) cycles.\n- Clinical audit: comparing practice against agreed standards and implementing change.\n- Reflective practice to support continuous professional development (CPD).\n\n### Standard Operating Procedures (SOPs)\n- Written instructions to ensure consistent, safe, repeatable clinical and laboratory procedures.\n\n### Laboratory & Scientific Practice\n- Health and safety in laboratory settings.\n- Use of standardised equipment and calibrated instruments.\n- Accurate measurement, recording and reporting of results.\n- Documentation and traceability of samples and results.`,
    sk_codes: ["SK1", "SK16", "SK18"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 4", "NMC Code", "NICE Evidence Standards", "NHS England: The 6 Cs", "ANTT: Aseptic Non-Touch Technique"],
    estimated_duration: 18,
    order_index: 4,
    knowledge_checks: [
      { question: "How many of the '6 Cs' are there in NHS practice?", options: ["4", "5", "6", "7"], correct: "6" },
      { question: "Which is NOT one of the 6 Cs?", options: ["Care", "Compassion", "Competition", "Courage"], correct: "Competition" },
      { question: "Evidence-based practice integrates research evidence, clinical expertise and:", options: ["Patient values", "Cost", "Hospital policy alone", "Tradition"], correct: "Patient values" },
      { question: "Which sits at the top of the hierarchy of evidence?", options: ["Expert opinion", "Case study", "Systematic review/meta-analysis", "Anecdote"], correct: "Systematic review/meta-analysis" },
      { question: "ANTT stands for:", options: ["Aseptic Non-Touch Technique", "Aseptic Nursing Treatment Tool", "Assessment of Need and Treatment", "Antibiotic Non-Tolerant Test"], correct: "Aseptic Non-Touch Technique" },
      { question: "Which is one of the 'rights' of medication administration?", options: ["Right patient", "Right ward", "Right colour", "Right mood"], correct: "Right patient" },
      { question: "The NMC Code priority 'practise effectively' means:", options: ["Work alone always", "Use best available evidence", "Avoid documentation", "Prioritise speed over safety"], correct: "Use best available evidence" },
      { question: "PDSA stands for:", options: ["Plan-Do-Study-Act", "Predict-Do-Stop-Assess", "Plan-Document-Share-Audit", "Prepare-Do-Standardise-Assure"], correct: "Plan-Do-Study-Act" },
      { question: "Clinical audit compares practice against:", options: ["Agreed standards", "Random opinions", "Last year's budget", "Social media"], correct: "Agreed standards" },
      { question: "Which organisation publishes clinical guidelines in England?", options: ["NICE", "CQC", "HMRC", "DVLA"], correct: "NICE" },
      { question: "Duty of candour requires clinicians to:", options: ["Be open and honest when things go wrong", "Avoid patients", "Work silently", "Refuse to document errors"], correct: "Be open and honest when things go wrong" },
      { question: "An SOP is:", options: ["A standard operating procedure", "A specialist out-patient", "A safety override protocol", "A statistical outcome profile"], correct: "A standard operating procedure" },
      { question: "Reflective practice supports:", options: ["Continuous professional development", "Avoiding work", "Hiding mistakes", "Reducing hours"], correct: "Continuous professional development" },
      { question: "Which is a vital sign measured in NEWS2?", options: ["Respiratory rate", "Blood glucose only", "Height", "Weight"], correct: "Respiratory rate" },
      { question: "A calibrated instrument is one that:", options: ["Is set against a known standard", "Is brand new", "Is disposable", "Requires no maintenance"], correct: "Is set against a known standard" },
      { question: "Traceability of samples means:", options: ["Samples can be tracked through every stage", "Samples are destroyed immediately", "Samples are shared publicly", "Samples are unlabelled"], correct: "Samples can be tracked through every stage" },
      { question: "Which is a professional value in the NMC Code?", options: ["Promote professionalism and trust", "Maximise profit", "Avoid teamwork", "Skip documentation"], correct: "Promote professionalism and trust" },
      { question: "A randomised controlled trial (RCT) sits where in the evidence hierarchy?", options: ["Above cohort studies", "Below expert opinion", "At the very bottom", "Outside the hierarchy"], correct: "Above cohort studies" },
      { question: "Competence in the 6 Cs refers to:", options: ["Having the skills and knowledge to deliver care", "Competition between staff", "Completing tasks quickly", "Computer literacy only"], correct: "Having the skills and knowledge to deliver care" },
      { question: "The 'right documentation' in medicines administration refers to:", options: ["Recording the drug, dose, time, route and signer", "Recording only the patient name", "No recording needed", "Recording in pencil"], correct: "Recording the drug, dose, time, route and signer" },
    ],
  },

  // ───────────────────────────────── AREA 5 ─────────────────────────────────
  {
    title: "Providing Person-Centred Care",
    spec_area: "Area 5",
    volume: "Core Paper 1",
    section: "Core Area 5 — Providing Person-Centred Care",
    content: `## Area 5: Providing Person-Centred Care\n\nThis area covers person-centred care — working in partnership with individuals to plan and deliver care that respects their needs, preferences, and rights.\n\n### Core Principles\n- Working in partnership with individuals and their families.\n- Respecting individual dignity, choices, beliefs, and preferences.\n- Promoting independence and wellbeing.\n- Holistic assessment covering physical, psychological, social, and spiritual needs.\n\n### The Nursing Process\n1. **Assessment** — holistic data collection.\n2. **Diagnosis** — identify actual and potential problems.\n3. **Planning** — set SMART goals, agree interventions.\n4. **Implementation** — deliver care.\n5. **Evaluation** — review outcomes, revise plan.\n\n### SMART Goals\n- Specific, Measurable, Achievable, Relevant, Time-bound.\n\n### Consent & Capacity\n- **Mental Capacity Act 2005:** Presumption of capacity; right to make unwise decisions; best interests; least restrictive option.\n- Consent must be voluntary, informed, and capacity-based.\n\n### Equality, Diversity & Inclusion\n- **Equality Act 2010:** protected characteristics.\n- Reasonable adjustments for disabled individuals.\n- Culturally competent, anti-discriminatory practice.\n\n### Communication\n- Therapeutic communication: active listening, empathy, non-verbal cues.\n- Addressing barriers: sensory impairment, language, cognitive impairment, learning disability.\n\n### Promoting Wellbeing & Independence\n- Encouraging self-care and autonomy.\n- Social prescribing and community support.`,
    sk_codes: ["SK8", "SK9", "SK18"],
    performance_outcomes: ["PO5", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 5", "Mental Capacity Act 2005", "Equality Act 2010", "NMC Code: Prioritise People", "NHS England: Person-Centred Care"],
    estimated_duration: 18,
    order_index: 5,
    knowledge_checks: [
      { question: "Person-centred care means working in:", options: ["Partnership with individuals", "Isolation", "Compliance only", "Silence"], correct: "Partnership with individuals" },
      { question: "Which Act presumes capacity unless proven otherwise?", options: ["Mental Capacity Act 2005", "Care Act 2014", "Equality Act 2010", "Children Act 2004"], correct: "Mental Capacity Act 2005" },
      { question: "SMART goals are:", options: ["Specific, Measurable, Achievable, Relevant, Time-bound", "Simple, Meaningful, Accurate, Recorded, Tested", "Standard, Medical, Assessed, Reviewed, Treated", "Safe, Modern, Adaptable, Reliable, Tested"], correct: "Specific, Measurable, Achievable, Relevant, Time-bound" },
      { question: "How many stages are in the nursing process?", options: ["3", "4", "5", "7"], correct: "5" },
      { question: "Which is a protected characteristic under the Equality Act 2010?", options: ["Age", "Eye colour", "Shoe size", "Favourite food"], correct: "Age" },
      { question: "Holistic assessment considers physical, psychological, social and:", options: ["Spiritual needs", "Financial income", "Political views", "Fashion sense"], correct: "Spiritual needs" },
      { question: "Valid consent must be voluntary, informed and:", options: ["Capacity-based", "Witnessed by a doctor", "Written only", "Permanent"], correct: "Capacity-based" },
      { question: "Under the Mental Capacity Act, an unwise decision:", options: ["Does not by itself prove incapacity", "Always proves incapacity", "Is illegal", "Requires restraint"], correct: "Does not by itself prove incapacity" },
      { question: "The 'least restrictive option' principle supports:", options: ["Maximising autonomy", "Maximum restraint", "Constant sedation", "Locking doors"], correct: "Maximising autonomy" },
      { question: "Reasonable adjustments are required for:", options: ["Disabled individuals", "All visitors", "Staff only", "Doctors only"], correct: "Disabled individuals" },
      { question: "Active listening is a component of:", options: ["Therapeutic communication", "Medication administration", "Hand hygiene", "Wound dressing"], correct: "Therapeutic communication" },
      { question: "Which is a communication barrier?", options: ["Sensory impairment", "Good lighting", "Quiet room", "Written notes"], correct: "Sensory impairment" },
      { question: "The first stage of the nursing process is:", options: ["Assessment", "Diagnosis", "Planning", "Evaluation"], correct: "Assessment" },
      { question: "Promoting independence supports:", options: ["Wellbeing and autonomy", "Dependency", "Restraint", "Isolation"], correct: "Wellbeing and autonomy" },
      { question: "Culturally competent practice means:", options: ["Respecting cultural beliefs and preferences", "Ignoring culture", "Imposing personal beliefs", "Treating everyone identically regardless of need"], correct: "Respecting cultural beliefs and preferences" },
      { question: "Anti-discriminatory practice requires:", options: ["Challenging discrimination", "Ignoring discrimination", "Joining in discrimination", "Accepting discrimination"], correct: "Challenging discrimination" },
      { question: "Social prescribing refers to:", options: ["Non-medical community support referrals", "Prescribing medication", "Prescribing rest", "Prescribing surgery"], correct: "Non-medical community support referrals" },
      { question: "Best interests decisions under the MCA must consider:", options: ["The person's wishes and values", "Cost alone", "Staff convenience", "Hospital targets"], correct: "The person's wishes and values" },
      { question: "Dignity in care includes:", options: ["Respecting privacy and choices", "Ignoring preferences", "Rushing care", "Public discussion of conditions"], correct: "Respecting privacy and choices" },
      { question: "Empathy in communication means:", options: ["Understanding and sharing another's feelings", "Giving medical advice only", "Completing paperwork", "Avoiding eye contact"], correct: "Understanding and sharing another's feelings" },
    ],
  },

  // ───────────────────────────────── AREA 6 (NEW) ─────────────────────────────────
  {
    title: "Health & Wellbeing",
    spec_area: "Area 6",
    volume: "Core Paper 1",
    section: "Core Area 6 — Health & Wellbeing",
    content: `## Area 6: Health & Wellbeing\n\nThis area covers the factors that influence health and wellbeing across the life course, and how healthcare workers promote and support positive outcomes.\n\n### Determinants of Health\n- **Biological:** genetics, age, sex.\n- **Behavioural/lifestyle:** diet, physical activity, smoking, alcohol, substance use.\n- **Social and economic:** income, education, employment, housing, social support.\n- **Environmental:** pollution, access to green space, safe communities.\n\n### Health Inequalities\n- Differences in health outcomes between groups.\n- Marmot Review: fair society, healthy lives; reducing the gradient.\n- Life expectancy and healthy life expectancy gaps.\n\n### Promoting Health & Wellbeing\n- **Health promotion:** enabling people to increase control over their health.\n- **Disease prevention:** primary (preventing onset), secondary (early detection), tertiary (managing established disease).\n- Behaviour change models: COM-B (Capability, Opportunity, Motivation).\n\n### Key Public Health Topics\n- Smoking cessation, alcohol reduction, healthy weight, immunisation, screening, mental wellbeing.\n\n### Mental Health & Wellbeing\n- Mental health parity with physical health.\n- Risk factors and protective factors.\n- Five Ways to Wellbeing: Connect, Be active, Take notice, Keep learning, Give.\n\n### Life Stages\n- Health needs vary across the life course: infancy, childhood, adolescence, adulthood, older age.\n- Person-centred approaches appropriate to each stage.`,
    sk_codes: ["SK9", "SK15"],
    performance_outcomes: ["PO6", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 6", "Marmot Review (Institute of Health Equity)", "WHO: Health Promotion", "NHS: Five Ways to Wellbeing"],
    estimated_duration: 16,
    order_index: 6,
    knowledge_checks: [
      { question: "Which is a social determinant of health?", options: ["Education", "Eye colour", "Blood group", "Heart rate"], correct: "Education" },
      { question: "Primary disease prevention aims to:", options: ["Prevent disease onset", "Detect disease early", "Manage established disease", "Provide end-of-life care"], correct: "Prevent disease onset" },
      { question: "Secondary prevention focuses on:", options: ["Early detection and intervention", "Preventing onset", "Palliative care", "Surgery"], correct: "Early detection and intervention" },
      { question: "The Marmot Review addressed:", options: ["Health inequalities", "Hospital finances", "Staff rotas", "Building design"], correct: "Health inequalities" },
      { question: "Which is one of the Five Ways to Wellbeing?", options: ["Be active", "Earn more", "Sleep less", "Work harder"], correct: "Be active" },
      { question: "How many Five Ways to Wellbeing are there?", options: ["3", "4", "5", "7"], correct: "5" },
      { question: "Health promotion is about:", options: ["Enabling people to increase control over their health", "Treating disease only", "Reducing hospital beds", "Increasing medication"], correct: "Enabling people to increase control over their health" },
      { question: "Tertiary prevention involves:", options: ["Managing established disease", "Preventing onset", "Screening", "Vaccination"], correct: "Managing established disease" },
      { question: "Which is a behavioural determinant of health?", options: ["Smoking", "Income", "Housing", "Sex"], correct: "Smoking" },
      { question: "Healthy life expectancy differs from life expectancy by:", options: ["Years lived in good health", "Years in hospital only", "Years working", "Years in education"], correct: "Years lived in good health" },
      { question: "COM-B stands for:", options: ["Capability, Opportunity, Motivation", "Care, Outcomes, Monitoring, Behaviour", "Clinical, Operational, Medical, Benefit", "Community, Outreach, Mental, Body"], correct: "Capability, Opportunity, Motivation" },
      { question: "Which is an environmental determinant of health?", options: ["Air pollution", "Genetics", "Age", "Blood type"], correct: "Air pollution" },
      { question: "Immunisation is an example of which prevention level?", options: ["Primary", "Secondary", "Tertiary", "Quaternary"], correct: "Primary" },
      { question: "Screening programmes are an example of:", options: ["Secondary prevention", "Primary prevention", "Tertiary prevention", "Palliative care"], correct: "Secondary prevention" },
      { question: "Mental health should have parity of esteem with:", options: ["Physical health", "Financial health", "Hospital budgets", "Staffing levels"], correct: "Physical health" },
      { question: "Which is a protective factor for mental wellbeing?", options: ["Social support", "Social isolation", "Substance misuse", "Long-term unemployment"], correct: "Social support" },
      { question: "Determinants of health include biological, behavioural, social and:", options: ["Environmental", "Astrological", "Meteorological", "Geological only"], correct: "Environmental" },
      { question: "Health needs across the life course means:", options: ["Needs vary at different life stages", "Everyone needs identical care", "Only older people need care", "Only children need care"], correct: "Needs vary at different life stages" },
      { question: "Which is a lifestyle risk factor?", options: ["Excess alcohol", "Gender", "Ageing", "Genetic inheritance"], correct: "Excess alcohol" },
      { question: "'Give' as one of the Five Ways to Wellbeing refers to:", options: ["Giving time or help to others", "Giving up on goals", "Giving medication", "Giving advice only"], correct: "Giving time or help to others" },
    ],
  },

  // ───────────────────────────────── AREA 7 (NEW) ─────────────────────────────────
  {
    title: "Safeguarding",
    spec_area: "Area 7",
    volume: "Core Paper 1",
    section: "Core Area 7 — Safeguarding",
    content: `## Area 7: Safeguarding\n\nThis area covers safeguarding children and adults at risk — recognising, responding to, and preventing abuse and neglect.\n\n### Key Legislation\n- **Care Act 2014:** Six safeguarding principles — Empowerment, Prevention, Proportionality, Protection, Partnership, Accountability.\n- **Children Act 1989/2004:** paramountcy of the child's welfare; duty to safeguard children.\n- **The Prevent Duty Guidance (2023):** identify early indicators of radicalisation; challenge extremist ideology.\n- **Mental Capacity Act 2005 & Deprivation of Liberty Safeguards (DoLS).**\n- **Modern Slavery Act 2015.**\n\n### Types of Abuse\nPhysical, emotional/psychological, sexual, financial, neglect, discriminatory, organisational, self-neglect, modern slavery, domestic abuse.\n\n### Adult Safeguarding\nAn adult at risk is someone aged 18+ with care and support needs who may be unable to protect themselves.\n\n### Child Safeguarding\n- All staff have a duty to safeguard children.\n- Safeguarding lead in every organisation.\n- Referrals to children's social care / MASH.\n\n### Recognising Signs\n- Unexplained injuries, changes in behaviour, fear, withdrawal, poor hygiene, unexplained financial changes.\n\n### Responding\n- Listen, reassure, don't investigate; record; report to safeguarding lead.\n\n### Information Sharing\n- The duty to share information to protect can override confidentiality (Caldicott Principle 6).`,
    sk_codes: ["SK8", "SK10", "SK18"],
    performance_outcomes: ["PO7", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 7", "Care Act 2014", "Children Act 1989/2004", "Prevent Duty Guidance 2023", "Modern Slavery Act 2015"],
    estimated_duration: 18,
    order_index: 7,
    knowledge_checks: [
      { question: "How many safeguarding principles are in the Care Act 2014?", options: ["4", "5", "6", "7"], correct: "6" },
      { question: "Which is a Care Act 2014 safeguarding principle?", options: ["Empowerment", "Efficiency", "Economy", "Excellence"], correct: "Empowerment" },
      { question: "The Children Act makes the welfare of the child:", options: ["Paramount", "Secondary", "Optional", "Confidential only"], correct: "Paramount" },
      { question: "Which Act addresses radicalisation and extremism?", options: ["Prevent Duty Guidance 2023", "COSHH 2002", "PUWER 1998", "HASAWA 1974"], correct: "Prevent Duty Guidance 2023" },
      { question: "Which is a type of abuse?", options: ["Financial", "Festive", "Formal", "Friendly"], correct: "Financial" },
      { question: "An adult at risk is aged:", options: ["Under 16", "Under 18", "18 or over", "65 or over only"], correct: "18 or over" },
      { question: "Which Act addresses modern slavery?", options: ["Modern Slavery Act 2015", "Care Act 2014", "Children Act 1989", "Equality Act 2010"], correct: "Modern Slavery Act 2015" },
      { question: "When responding to a safeguarding disclosure, you should:", options: ["Listen, reassure, record, report — not investigate", "Investigate thoroughly yourself", "Confront the alleged abuser", "Tell no one"], correct: "Listen, reassure, record, report — not investigate" },
      { question: "DoLS stands for:", options: ["Deprivation of Liberty Safeguards", "Duty of Local Safeguarding", "Direct Observation of Lifestyle Signs", "Disclosure of Localised Standards"], correct: "Deprivation of Liberty Safeguards" },
      { question: "Which is a recognised sign of abuse?", options: ["Unexplained injuries", "Happy mood", "Stable weight", "Good hygiene"], correct: "Unexplained injuries" },
      { question: "Self-neglect is:", options: ["A recognised type of abuse", "A criminal offence by the victim", "Always a lifestyle choice to respect", "Not a safeguarding concern"], correct: "A recognised type of abuse" },
      { question: "Domestic abuse can include:", options: ["Physical, emotional, sexual and financial abuse", "Only physical violence", "Only financial control", "Only verbal arguments"], correct: "Physical, emotional, sexual and financial abuse" },
      { question: "Who has a duty to safeguard children?", options: ["All staff", "Only doctors", "Only social workers", "Only nurses"], correct: "All staff" },
      { question: "The safeguarding lead is:", options: ["A designated person in every organisation", "A government minister", "A police role only", "A voluntary role with no authority"], correct: "A designated person in every organisation" },
      { question: "Caldicott Principle 6 means the duty to share information to protect:", options: ["Can override confidentiality", "Never overrides confidentiality", "Is illegal", "Only applies to children"], correct: "Can override confidentiality" },
      { question: "Which is an example of organisational abuse?", options: ["Poor institutional care practices", "A single rude comment", "An accidental fall", "A missed appointment"], correct: "Poor institutional care practices" },
      { question: "Discriminatory abuse is based on:", options: ["A protected characteristic", "A medical diagnosis", "A random factor", "An accident"], correct: "A protected characteristic" },
      { question: "Neglect involves:", options: ["Failure to meet basic needs", "Active violence", "Theft of money", "Verbal insults"], correct: "Failure to meet basic needs" },
      { question: "MASH stands for:", options: ["Multi-Agency Safeguarding Hub", "Medical Assessment of Safety Hazards", "Mandatory Adult Safety Helpline", "Minor Ailment Service Hub"], correct: "Multi-Agency Safeguarding Hub" },
      { question: "When recording a safeguarding concern, you should:", options: ["Record factually, promptly and objectively", "Record your opinions only", "Wait a week", "Record verbally only"], correct: "Record factually, promptly and objectively" },
    ],
  },

  // ───────────────────────────────── AREA 8 ─────────────────────────────────
  {
    title: "Core Science Concepts",
    spec_area: "Area 8",
    volume: "Core Paper 2",
    section: "Core Area 8 — Core Science Concepts",
    content: `## Area 8: Core Science Concepts\n\nThis area covers the core scientific concepts that underpin health and clinical practice.\n\n### Cell Theory\n1. All living organisms are composed of one or more functional cells.\n2. Cells are the basic structural and organisational unit of life.\n3. All cells arise from pre-existing cells through division.\n\n### Eukaryotic Cell Ultrastructure\n- **Cell Surface Membrane:** Fluid mosaic model; controls selective transport and displays cell surface antigens.\n- **Nucleus:** Houses genetic material (DNA) and controls gene expression.\n- **Mitochondria:** Double-membraned; site of aerobic respiration producing ATP.\n- **Rough Endoplasmic Reticulum (RER):** Ribosome-studded; protein translation, packaging, and transport.\n- **Golgi Apparatus:** Modifies, packages, and sorts proteins for secretion.\n- **Lysosomes:** Contain digestive enzymes for intracellular waste breakdown.\n\n### Biochemistry\n- **Triglyceride** = 1 Glycerol + 3 Fatty Acids.\n- **Proteins:** Primary → secondary → tertiary → quaternary structure.\n- **Carbohydrates:** Prime metabolic fuel; stored as glycogen.\n- **Lipids:** Amphipathic phospholipids form bilayers (hydrophilic head, hydrophobic tail).\n- **Enzymes:** Biological catalysts lowering activation energy; affected by temperature, pH, and substrate concentration.\n\n### Genetics\n- DNA structure (double helix), replication, transcription, translation.\n- Mendelian inheritance and genetic disorders relevant to healthcare.\n\n### Chemistry for Health\n- pH and the acid-base balance.\n- Solutions, concentrations, and dilutions used in drug administration.\n- Moles and molar solutions.`,
    sk_codes: ["SK17"],
    performance_outcomes: ["PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 8", "Clinical Skills.net: Biochemistry Fundamentals", "NHS: Cell Biology Reference"],
    estimated_duration: 20,
    order_index: 8,
    knowledge_checks: [
      { question: "How many tenets make up cell theory?", options: ["2", "3", "4", "5"], correct: "3" },
      { question: "All cells arise from:", options: ["Pre-existing cells", "Spontaneous generation", "Air", "Light"], correct: "Pre-existing cells" },
      { question: "Which organelle is the site of aerobic respiration?", options: ["Mitochondria", "Nucleus", "Golgi", "Lysosome"], correct: "Mitochondria" },
      { question: "A triglyceride consists of 1 glycerol and how many fatty acids?", options: ["1", "2", "3", "4"], correct: "3" },
      { question: "The cell membrane is described by which model?", options: ["Fluid mosaic", "Solid lattice", "Rigid shell", "Sponge model"], correct: "Fluid mosaic" },
      { question: "Enzymes act as biological catalysts by lowering:", options: ["Activation energy", "Temperature", "pH", "Substrate concentration"], correct: "Activation energy" },
      { question: "DNA replication, transcription and translation are part of:", options: ["Gene expression", "Digestion", "Respiration", "Photosynthesis"], correct: "Gene expression" },
      { question: "Phospholipids have a hydrophilic head and a hydrophobic:", options: ["Tail", "Nucleus", "Membrane", "Core"], correct: "Tail" },
      { question: "Which stores glucose as glycogen in humans?", options: ["Liver and muscle", "Brain only", "Skin", "Bone"], correct: "Liver and muscle" },
      { question: "Which is a protein structure level?", options: ["Tertiary", "Cuboidal", "Hexagonal", "Radial"], correct: "Tertiary" },
      { question: "The nucleus houses which genetic material?", options: ["DNA", "RNA only", "Lipids", "Glycogen"], correct: "DNA" },
      { question: "RER is studded with which structures?", options: ["Ribosomes", "Lysosomes", "Vacuoles", "Centrioles"], correct: "Ribosomes" },
      { question: "The Golgi apparatus modifies, packages and sorts:", options: ["Proteins", "DNA", "Carbohydrates only", "Water"], correct: "Proteins" },
      { question: "Lysosomes contain:", options: ["Digestive enzymes", "DNA", "Chlorophyll", "Insulin"], correct: "Digestive enzymes" },
      { question: "A solution with a pH below 7 is:", options: ["Acidic", "Alkaline", "Neutral", "Buffered"], correct: "Acidic" },
      { question: "A mole is a measure of:", options: ["Amount of substance", "Volume", "Length", "Temperature"], correct: "Amount of substance" },
      { question: "Enzyme activity is affected by temperature, pH and:", options: ["Substrate concentration", "Light colour", "Sound", "Humidity"], correct: "Substrate concentration" },
      { question: "Carbohydrates are the body's prime:", options: ["Metabolic fuel", "Structural protein", "Genetic material", "Enzyme"], correct: "Metabolic fuel" },
      { question: "Mendelian inheritance describes:", options: ["Patterns of genetic inheritance", "Digestion", "Cell division only", "Evolution"], correct: "Patterns of genetic inheritance" },
      { question: "ATP is produced mainly during:", options: ["Aerobic respiration", "Diffusion", "Osmosis", "Transcription"], correct: "Aerobic respiration" },
    ],
  },

  // ───────────────────────────────── AREA 9 ─────────────────────────────────
  {
    title: "Further Science Concepts in Health",
    spec_area: "Area 9",
    volume: "Core Paper 2",
    section: "Core Area 9 — Further Science Concepts in Health",
    content: `## Area 9: Further Science Concepts in Health\n\nThis area covers further scientific concepts that build on Core Area 8 and apply them to health and clinical practice.\n\n### Pathogens & Disease Transmission\nPathogens are disease-causing microorganisms. Transmission routes:\n- **Direct:** physical touch, bodily fluids, droplet inhalation.\n- **Indirect:** contaminated surfaces, vector bites, faecal-oral ingestion.\n\n**Healthcare-Associated Infections (HCAIs):** Infections acquired during clinical care, including MRSA and *Clostridium difficile*.\n\n### Immunology\n- **Non-Specific (Innate) Defenses:** Skin, mucous membranes, stomach acid, inflammation, phagocytosis.\n- **Specific (Adaptive) Immune Response:** T-cells (cell-mediated) and B-cells (humoral antibody synthesis). Immunological memory underpins vaccinations.\n\n### Homeostasis\nMaintains stable internal variables (core temperature, blood glucose, blood pressure, osmoregulation) via **negative feedback loops**. Failure leads to chronic disease.\n\n### Anatomy & Physiology\n- Body systems: cardiovascular, respiratory, nervous, digestive, urinary, musculoskeletal, endocrine, reproductive, integumentary, lymphatic/immune.\n- Key organ structure and function relevant to nursing practice.\n\n### Disease Classification Systems\n- **ICD (International Classification of Diseases):** Codes physical and mental health conditions.\n- **DSM:** Standardises criteria for psychiatric diagnoses.\n- **SNOMED CT:** Common clinical vocabulary for electronic health records.\n\n### Physics for Health\n- Pressure and fluid dynamics (blood pressure, IV flow rates).\n- Electricity and magnetism (ECG, defibrillation, MRI principles).\n- Radiation and imaging (X-ray, CT).`,
    sk_codes: ["SK7", "SK17"],
    performance_outcomes: ["PO7", "PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 9", "NHS England: IPC", "WHO: Disease Classification", "Clinical Skills.net: Anatomy & Physiology"],
    estimated_duration: 20,
    order_index: 9,
    knowledge_checks: [
      { question: "Which is a direct transmission route?", options: ["Droplet inhalation", "Contaminated surface", "Vector bite", "Faecal-oral"], correct: "Droplet inhalation" },
      { question: "MRSA is an example of a:", options: ["Healthcare-associated infection", "Genetic disorder", "Vitamin deficiency", "Broken bone"], correct: "Healthcare-associated infection" },
      { question: "Which is a non-specific (innate) defence?", options: ["Skin", "T-cells", "B-cells", "Antibodies"], correct: "Skin" },
      { question: "Antibodies are produced by which cells?", options: ["B-cells", "Red blood cells", "Platelets", "T-cells"], correct: "B-cells" },
      { question: "Homeostasis maintains stable internal conditions via which mechanism?", options: ["Negative feedback loops", "Positive feedback only", "Random changes", "Digestion"], correct: "Negative feedback loops" },
      { question: "Which is a body system?", options: ["Cardiovascular", "Chemical", "Geometric", "Financial"], correct: "Cardiovascular" },
      { question: "ICD is used to classify:", options: ["Diseases", "Medication doses", "Staff", "Equipment"], correct: "Diseases" },
      { question: "DSM is used to standardise:", options: ["Psychiatric diagnoses", "Surgical tools", "Lab equipment", "Diet plans"], correct: "Psychiatric diagnoses" },
      { question: "Blood pressure measurement uses which physics concept?", options: ["Pressure", "Electromagnetism", "Radiation", "Optics"], correct: "Pressure" },
      { question: "ECG and defibrillation use principles of:", options: ["Electricity", "Optics", "Thermodynamics", "Acoustics"], correct: "Electricity" },
      { question: "Immunological memory underpins:", options: ["Vaccinations", "Digestion", "Respiration", "Circulation"], correct: "Vaccinations" },
      { question: "T-cells are responsible for:", options: ["Cell-mediated immunity", "Carrying oxygen", "Clotting blood", "Filtering urea"], correct: "Cell-mediated immunity" },
      { question: "Which is an indirect transmission route?", options: ["Contaminated surface", "Bodily fluids", "Droplet inhalation", "Physical touch"], correct: "Contaminated surface" },
      { question: "Osmoregulation regulates:", options: ["Water balance", "Body posture", "Heart rate", "Vision"], correct: "Water balance" },
      { question: "CT imaging uses which technology?", options: ["X-ray/radiation", "Ultrasound only", "Sound waves only", "Magnetism only"], correct: "X-ray/radiation" },
      { question: "Which is a specific (adaptive) immune component?", options: ["T-cells", "Skin", "Stomach acid", "Inflammation"], correct: "T-cells" },
      { question: "Negative feedback failure can lead to:", options: ["Chronic disease", "Improved health", "Faster reflexes", "Better vision"], correct: "Chronic disease" },
      { question: "SNOMED CT is used in:", options: ["Electronic health records", "Cooking", "Architecture", "Astronomy"], correct: "Electronic health records" },
      { question: "IV flow rates depend on which physics concept?", options: ["Fluid dynamics/pressure", "Magnetism", "Radiation", "Optics"], correct: "Fluid dynamics/pressure" },
      { question: "Phagocytosis is part of which defence system?", options: ["Innate/non-specific", "Adaptive/specific", "Digestive", "Nervous"], correct: "Innate/non-specific" },
    ],
  },
];

// Normalise knowledge_checks for display (handles array or JSON string)
export function getKnowledgeChecks(module) {
  if (!module?.knowledge_checks) return [];
  if (Array.isArray(module.knowledge_checks)) return module.knowledge_checks;
  try {
    const parsed = JSON.parse(module.knowledge_checks);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}