/**
 * Celebrity Ward Patient Directory
 * Clinical Suite A (Beds A1–A3) and Clinical Suite B (Beds B1–B4)
 * Aligned to T Level Health (Adult Nursing) Specification
 */

export const WARD_PATIENTS = [
  {
    id: "elvis",
    bedDesignation: "A1",
    suite: "A",
    name: "Elvis Presley",
    age: 42,
    dob: "08/01/1935",
    nhs_number: "485 777 3301",
    pronouns: "He/Him",
    condition: "Acute severe COPD exacerbation, constipation, Type 2 Diabetes",
    comorbidities: "COPD, Type 2 Diabetes Mellitus, Severe constipation, Obesity",
    allergies: "Codeine (respiratory depression risk)",
    medications: "Salbutamol inhaler (PRN), Tiotropium, Prednisolone 30mg OD, Metformin 1g BD, Enoxaparin 40mg SC OD, Laxido sachets PRN",
    admission_reason: "Admitted via A&E with 3-day history of increasing breathlessness, wheeze, and productive cough. Hypoxic on air. Also reporting no bowel movement for 5 days.",
    initial_vitals: { rr: 26, spo2: 89, supplemental_o2: false, sbp: 145, dbp: 92, hr: 102, avpu: "A", temp: 37.8, cbg: 15.2 },
    initial_news2: 8,
    persona: "Southern US drawl, polite but anxious. Uses phrases like 'Aw, shucks' and 'Thank ya, thank ya very much.' Worried about his health but tries to stay positive. Self-conscious about his weight.",
    assessment_focus: [
      { code: "SHS3.4", label: "NEWS2 Scoring & Deterioration Recognition" },
      { code: "ANS1.1", label: "Bristol Stool Form Scale (Types 1–7)" },
      { code: "SHK3.18", label: "Blood Glucose Monitoring — CBG 15.2 mmol/L" },
      { code: "SHK3.24", label: "SBAR Escalation (NEWS2 ≥ 5, SpO₂ 3 = RED)" },
    ],
    learning_objectives: [
      "Calculate NEWS2 score and identify hypoxic drive risk in COPD (target SpO₂ 88–92%)",
      "Identify Bristol Stool Type 1 and document bowel/continence assessment",
      "Recognise CBG 15.2 mmol/L as above acceptable range — escalate via SBAR",
      "Understand why high-flow O₂ is contraindicated in hypercapnic COPD",
    ],
    consent_phrase: "Elvis, my name is [Student Name] and I'm a student nurse working under the supervision of the registered nurse. Before I carry out any observations, I'd like to explain what I'll be doing and ask for your permission. Is that okay with you?",
    clinical_notes: "COPD patient — DO NOT exceed 28% Venturi mask unless directed by doctor. SpO₂ target: 88–92%. Risk of hypercapnic respiratory failure with high-flow O₂. NEWS2 = 8 → URGENT escalation required.",
    escalation_threshold: 8,
    sskin_risk: false,
    falls_risk: false,
    safeguarding_flag: false,
    pressure_ulcer_risk: false,
    debrief_rationale: "Elvis scored NEWS2 = 8, a single RED parameter (SpO₂ < 91%). This mandates immediate senior escalation using SBAR. The hypoxic drive principle is critical — only 28% Venturi O₂ or equivalent. CBG of 15.2 requires reporting. Bristol Stool Type 1 (separate hard lumps) indicates severe constipation.",
  },
  {
    id: "dolly",
    bedDesignation: "A2",
    suite: "A",
    name: "Dolly Parton",
    age: 78,
    dob: "19/01/1946",
    nhs_number: "612 834 5502",
    pronouns: "She/Her",
    condition: "Post-operative left hip repair (Day 1), rheumatoid arthritis, delicate ageing skin",
    comorbidities: "Rheumatoid arthritis, osteoporosis, previous falls, hypertension",
    allergies: "NKDA",
    medications: "Paracetamol 1g QDS, Codeine PRN, Methotrexate (hold post-op), Alendronate, Enoxaparin 40mg SC OD, Omeprazole 20mg OD",
    admission_reason: "Elective left total hip replacement following a fall at home. Post-operative Day 1. Rheumatoid arthritis with fragile skin — high pressure ulcer risk. Pain NRS 6/10 at rest.",
    initial_vitals: { rr: 16, spo2: 97, supplemental_o2: false, sbp: 118, dbp: 74, hr: 72, avpu: "A", temp: 36.6, cbg: null },
    initial_news2: 0,
    persona: "Warm, cheerful, Southern charm. Very talkative. Uses phrases like 'Honey' and 'Sweetheart.' Optimistic but winces when moved. Proud and independent — hates asking for help. Refers to her rhinestone pyjamas.",
    assessment_focus: [
      { code: "ANS3.1", label: "SSKIN Bundle — Surface, Skin Inspection, Keep Moving, Incontinence, Nutrition" },
      { code: "ANK3.3", label: "Waterlow / Braden Risk Assessment" },
      { code: "ANK3.3", label: "EPUAP Pressure Ulcer Grading (6 categories)" },
      { code: "ANS2.1", label: "ADLs: Dressing, mobility frame/hoist, NRS pain scoring" },
    ],
    learning_objectives: [
      "Complete Waterlow score — identify category (likely Very High Risk ≥ 20 given age, post-op, RA, fragile skin)",
      "Implement full SSKIN bundle documentation",
      "Assist with ADLs sensitively — promote dignity and independence",
      "Use NRS to assess and document pain before and after repositioning",
    ],
    consent_phrase: "Dolly, my name is [Student Name] and I'm a student nurse working with the team today. I'd like to do a skin inspection as part of your pressure area care — this means I'll gently check your skin at the pressure points. Is that okay, sweetheart?",
    clinical_notes: "Day 1 post-op. High skin integrity risk — ageing skin, RA medication (Methotrexate), reduced mobility. 2-hourly repositioning. Rheumatoid joints — handle gently, avoid forced movement. Do not use Waterlow >20 mattress already ordered. Document all skin inspections with body map.",
    escalation_threshold: 5,
    sskin_risk: true,
    falls_risk: true,
    safeguarding_flag: false,
    pressure_ulcer_risk: true,
    debrief_rationale: "Dolly's Waterlow score should be ≥ 20 (Very High Risk) given age 78, post-surgical, RA, fragile skin, and reduced mobility. The SSKIN bundle must be implemented. Students should demonstrate person-centred communication and preserve dignity throughout ADL assistance. Pain must be assessed with NRS before mobilisation.",
  },
  {
    id: "gordon",
    bedDesignation: "A3",
    suite: "A",
    name: "Gordon Ramsay",
    age: 57,
    dob: "08/11/1966",
    nhs_number: "738 921 6603",
    pronouns: "He/Him",
    condition: "Acute Crohn's disease flare, severe abdominal pain, recent weight loss",
    comorbidities: "Crohn's disease (established), malnutrition (MUST score ≥ 2 expected), dehydration",
    allergies: "Metronidazole (nausea/vomiting)",
    medications: "Prednisolone 40mg OD, Azathioprine 150mg OD, Infliximab (infusion due), Mesalazine, IV Hartmann's solution at 125ml/hr, Codeine PRN",
    admission_reason: "Admitted with 10-day history of severe abdominal cramping, 8+ liquid stools daily, nausea, and unintentional weight loss of 6kg in 5 weeks. C-reactive protein (CRP) elevated. Dehydrated.",
    initial_vitals: { rr: 20, spo2: 98, supplemental_o2: false, sbp: 105, dbp: 65, hr: 98, avpu: "A", temp: 37.4, cbg: null },
    initial_news2: 3,
    persona: "Blunt, impatient, uses expletive-adjacent phrases like 'Bloody hell' and 'Are you having a laugh?' Very anxious underneath but masks it with aggression. Deeply food-focused — upset he can't eat. Responds well to confidence and professionalism. Will calm down if student is assertive and knowledgeable.",
    assessment_focus: [
      { code: "ANK1.1", label: "MUST Screening Tool — calculate BMI, recent weight loss, acute disease effect" },
      { code: "ANK2.2", label: "Fluid Balance Charting — inputs vs outputs" },
      { code: "SHK2.2", label: "Communication under stress — NHS 6 Cs, professional boundaries" },
      { code: "ANS1.1", label: "Stool Specimen SOP — Bristol Stool Scale (watery Type 7)" },
    ],
    learning_objectives: [
      "Calculate MUST score — likely Score 2 (High Risk) requiring dietitian referral",
      "Accurately complete a 24-hour fluid balance chart and identify negative fluid balance",
      "Demonstrate professional communication with an anxious/aggressive patient (CS2)",
      "Follow SOP for stool specimen collection — label correctly, maintain dignity",
    ],
    consent_phrase: "Mr Ramsay, I understand you're feeling very unwell and frustrated — that's completely understandable. My name is [Student Name]. I'd like to do a quick nutritional screening assessment and check your fluid chart. Is now an okay time?",
    clinical_notes: "High-output stoma/diarrhoea — fluid balance critical. MUST score required urgently — refer to dietitian if ≥ 2. IV fluids running — check site and rate hourly. Stool specimen required for MC&S, C. diff toxin. Patient may be distressed — maintain professional boundaries. Nil by mouth for potential scope.",
    escalation_threshold: 5,
    sskin_risk: false,
    falls_risk: false,
    safeguarding_flag: false,
    pressure_ulcer_risk: false,
    debrief_rationale: "Gordon's MUST score: unintentional weight loss >5kg in 3 months (Score 2) = High Risk. Fluid balance: negative balance from high-output diarrhoea. NEWS2 = 3 (low score but watch hypotension SBP 105). Students must manage a challenging communication dynamic while maintaining the NHS 6 Cs. Stool specimen SOP must be followed correctly.",
  },
  {
    id: "ozzy",
    bedDesignation: "B1",
    suite: "B",
    name: "Ozzy Osbourne",
    age: 75,
    dob: "03/12/1948",
    nhs_number: "864 112 7704",
    pronouns: "He/Him",
    condition: "Post-fall, advanced Parkinson's Disease, mild acute delirium",
    comorbidities: "Advanced Parkinson's Disease (tremors, bradykinesia, rigidity), postural hypotension, mild cognitive impairment",
    allergies: "NKDA",
    medications: "Levodopa/Carbidopa (Sinemet) 25/100mg TDS — CRITICAL: on-time dosing essential, Ropinirole, Omeprazole, Paracetamol PRN, Thiamine IV",
    admission_reason: "Found on floor at home by carer. Suspected mechanical fall — no loss of consciousness. C-spine cleared. Mild acute delirium — confused about place and time. BP postural dip noted. Parkinson's medication MUST be given on time.",
    initial_vitals: { rr: 18, spo2: 96, supplemental_o2: false, sbp: 110, dbp: 70, hr: 68, avpu: "C", temp: 36.4, cbg: null },
    initial_news2: 2,
    persona: "Heavy accent, speaks slowly and softly with some word-finding difficulty. Confused but lucid in moments. Sometimes thinks he is at home in Bel Air. Responds to his name. Can become distressed if rushed. Call him 'Ozzy' — not 'Mr Osbourne'.",
    assessment_focus: [
      { code: "ANK1.1", label: "FRAT — Falls Risk Assessment Tool (5-criteria screen for >65s)" },
      { code: "SHS1.8", label: "Moving & Handling — TILE Model, slide sheets, passive hoist" },
      { code: "SHK2.20", label: "Delirium vs. Dementia differentiation under MCA 2005" },
      { code: "ANK2.8", label: "Safeguarding — vulnerability assessment, dignity in personal care" },
    ],
    learning_objectives: [
      "Complete FRAT — 5 criteria: prior falls, medications, cognitive impairment, self-care, patient perception",
      "Differentiate acute delirium (sudden onset, fluctuating) from dementia (gradual, progressive)",
      "Apply TILE model for safe moving and handling — identify risks",
      "Assess mental capacity using MCA 2005 two-stage test for each decision",
    ],
    consent_phrase: "Ozzy? Hi, my name is [Student Name] and I'm a nurse here at the hospital. You've had a fall and we're looking after you. I'd like to check how you're feeling and make sure you're comfortable. Is that okay?",
    clinical_notes: "CRITICAL — Sinemet MUST be administered on time (off episodes severely debilitating). AVPU = C (Confusion) — document baseline and monitor for deterioration. FRAT required. Falls bundle: bed low, call bell in reach, non-slip footwear. MCA assessment needed if any treatment decisions arise. Safeguarding referral — consider if fall was result of neglect.",
    escalation_threshold: 5,
    sskin_risk: false,
    falls_risk: true,
    safeguarding_flag: true,
    pressure_ulcer_risk: false,
    debrief_rationale: "Ozzy presents with acute delirium (sudden onset confusion, acute trigger = fall, fluctuating — NOT chronic dementia). FRAT should return HIGH score. TILE model must be applied for all manual handling. Sinemet timing is critical — delayed doses = loss of motor control, aspiration risk. MCA applies to any treatment decision — assess each one individually.",
  },
  {
    id: "ladygaga",
    bedDesignation: "B2",
    suite: "B",
    name: "Lady Gaga",
    age: 38,
    dob: "28/03/1986",
    nhs_number: "921 445 8805",
    pronouns: "She/Her",
    condition: "Severe fibromyalgia flare, generalised hyperalgesia, atopic eczema with skin breakdown",
    comorbidities: "Fibromyalgia syndrome, Atopic eczema (lower limbs), anxiety disorder, PTSD",
    allergies: "Latex (anaphylaxis — use nitrile gloves only)",
    medications: "Pregabalin 150mg BD, Duloxetine 60mg OD, Paracetamol 1g QDS, Ibuprofen PRN (monitor renal function), Dermovate cream topical (prescribed), Epaderm ointment 500g (emollient)",
    admission_reason: "Admitted with severe widespread pain (NRS 9/10), hyperalgesia (extreme sensitivity to touch), and bilateral lower limb skin breakdown with eczema flare. Unable to self-care independently at home.",
    initial_vitals: { rr: 15, spo2: 99, supplemental_o2: false, sbp: 122, dbp: 78, hr: 84, avpu: "A", temp: 36.8, cbg: null },
    initial_news2: 0,
    persona: "Creative, articulate, and philosophical. Speaks openly about pain and mental health. Uses artistic metaphors. Grateful for person-centred care. Very sensitive to touch — flinches. Anxious if not warned before touching. Appreciates being asked how she'd like to be cared for.",
    assessment_focus: [
      { code: "ANK1.1", label: "PAINAD / VAS Non-verbal & Verbal Pain Scoring" },
      { code: "ANS3.2", label: "Topical barrier creams, emollients, simple non-impregnated dressings" },
      { code: "ANK3.4", label: "Skin Condition Treatment — eczema, skin breakdown" },
      { code: "SHS2.1", label: "Person-Centred Care, dynamic consent, communication adaptation" },
    ],
    learning_objectives: [
      "Use VAS and NRS to document pain levels — repeat pre and post analgesia",
      "Apply emollient (Epaderm) correctly — direction of hair growth, pat not rub",
      "Select and apply appropriate non-impregnated dressings to lower limb skin breakdown",
      "Demonstrate dynamic consent — ask before every touch, explain each step",
    ],
    consent_phrase: "Hello, is it okay if I call you by your first name? I'm [Student Name], a student nurse. I understand you have hyperalgesia which means touch can be very painful. Before I do anything at all, I will always explain what I'm going to do and ask your permission first. Is that okay?",
    clinical_notes: "LATEX ALLERGY — only nitrile gloves. Hyperalgesia: announce every touch, approach slowly, minimal pressure. Emollient application technique critical — always apply in direction of hair growth to prevent folliculitis. Dressing lower limbs — use foam or non-adherent dressings (avoid adhesive). PTSD — be aware of trauma-informed care approach.",
    escalation_threshold: 5,
    sskin_risk: true,
    falls_risk: false,
    safeguarding_flag: false,
    pressure_ulcer_risk: false,
    debrief_rationale: "Lady Gaga's care requires exemplary person-centred communication and dynamic consent throughout (CS1, CS2). Pain must be assessed with both verbal (NRS) and non-verbal cues. Emollient application technique matters clinically — incorrect direction increases folliculitis risk. Students must recognise latex allergy and use only nitrile gloves. Fibromyalgia requires a holistic, multidisciplinary approach.",
  },
];

/** Map bed designation to patient */
export function getPatientForBed(bedDesignation) {
  return WARD_PATIENTS.find(p => p.bedDesignation === bedDesignation) || null;
}

/** Get all patients for a given suite */
export function getPatientsForSuite(suite) {
  return WARD_PATIENTS.filter(p => p.suite === suite);
}

/** NEWS2 colour band */
export function news2Band(score) {
  if (score === 0) return { label: "Low", color: "text-clinical-green", bg: "bg-clinical-green/10", border: "border-clinical-green/30" };
  if (score <= 4) return { label: "Low-Medium", color: "text-clinical-amber", bg: "bg-clinical-amber/10", border: "border-clinical-amber/30" };
  if (score <= 6) return { label: "Medium", color: "text-orange-600", bg: "bg-orange-50", border: "border-orange-300" };
  return { label: "HIGH — Escalate", color: "text-clinical-red", bg: "bg-clinical-red/10", border: "border-clinical-red/30" };
}