// Area 9 — Further Science Concepts in Health (3 sub-modules)

export const AREA9_MODULES = [
  {
    title: "Pathogens, Transmission & HCAIs",
    spec_area: "Area 9",
    volume: "Core Paper 2",
    section: "Core Area 9.1 — Pathogens & Transmission",
    content: `## Pathogens & Disease Transmission\n\nPathogens are disease-causing microorganisms. Transmission routes:\n- **Direct:** physical touch, bodily fluids, droplet inhalation.\n- **Indirect:** contaminated surfaces, vector bites, faecal-oral ingestion.\n\n## Healthcare-Associated Infections (HCAIs)\n\nInfections acquired during clinical care, including MRSA and *Clostridium difficile*. Prevented through hand hygiene, asepsis, and prudent antimicrobial use.\n\n## Breaking the Chain of Transmission\n\nHand hygiene, PPE, isolation, decontamination, and safe waste disposal interrupt transmission at multiple points.`,
    sk_codes: ["SK7", "SK17"],
    performance_outcomes: ["PO7", "PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 9", "NHS England: IPC"],
    estimated_duration: 10,
    order_index: 25,
    knowledge_checks: [
      { question: "Which is a direct transmission route?", options: ["Droplet inhalation", "Contaminated surface", "Vector bite", "Faecal-oral"], correct: "Droplet inhalation" },
      { question: "MRSA is an example of a:", options: ["Healthcare-associated infection", "Genetic disorder", "Vitamin deficiency", "Broken bone"], correct: "Healthcare-associated infection" },
      { question: "Which is an indirect transmission route?", options: ["Contaminated surface", "Bodily fluids", "Droplet inhalation", "Physical touch"], correct: "Contaminated surface" },
      { question: "HCAIs are infections acquired:", options: ["During clinical care", "Before birth", "Only in the community", "Only from animals"], correct: "During clinical care" },
      { question: "Which is a direct transmission route?", options: ["Physical touch", "Contaminated surface", "Vector bite", "Faecal-oral ingestion"], correct: "Physical touch" },
      { question: "Faecal-oral transmission is an example of:", options: ["Indirect transmission", "Direct transmission", "Genetic inheritance", "Aseptic technique"], correct: "Indirect transmission" },
      { question: "Hand hygiene primarily breaks the chain of transmission by:", options: ["Removing transient organisms", "Sterilising equipment", "Improving lighting", "Reducing noise"], correct: "Removing transient organisms" },
      { question: "*Clostridium difficile* is an example of a:", options: ["Healthcare-associated infection", "Vitamin", "Enzyme", "Vaccine"], correct: "Healthcare-associated infection" },
      { question: "Vector bites are an example of:", options: ["Indirect transmission", "Direct transmission", "Aseptic technique", "Negative feedback"], correct: "Indirect transmission" },
      { question: "Prudent antimicrobial use helps prevent:", options: ["Antimicrobial resistance and HCAIs", "Vaccination", "Homeostasis", "Phagocytosis"], correct: "Antimicrobial resistance and HCAIs" },
    ],
  },
  {
    title: "Immunology & Homeostasis",
    spec_area: "Area 9",
    volume: "Core Paper 2",
    section: "Core Area 9.2 — Immunology & Homeostasis",
    content: `## Immunology\n\n- **Non-Specific (Innate) Defenses:** Skin, mucous membranes, stomach acid, inflammation, phagocytosis.\n- **Specific (Adaptive) Immune Response:** T-cells (cell-mediated) and B-cells (humoral antibody synthesis). Immunological memory underpins vaccinations.\n\n## Homeostasis\n\nMaintains stable internal variables (core temperature, blood glucose, blood pressure, osmoregulation) via **negative feedback loops**. Failure leads to chronic disease.\n\n## Osmoregulation\n\nOsmoregulation regulates water balance in the body.`,
    sk_codes: ["SK7", "SK17"],
    performance_outcomes: ["PO7", "PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 9", "Clinical Skills.net: Anatomy & Physiology"],
    estimated_duration: 10,
    order_index: 26,
    knowledge_checks: [
      { question: "Which is a non-specific (innate) defence?", options: ["Skin", "T-cells", "B-cells", "Antibodies"], correct: "Skin" },
      { question: "Antibodies are produced by which cells?", options: ["B-cells", "Red blood cells", "Platelets", "T-cells"], correct: "B-cells" },
      { question: "Homeostasis maintains stable internal conditions via which mechanism?", options: ["Negative feedback loops", "Positive feedback only", "Random changes", "Digestion"], correct: "Negative feedback loops" },
      { question: "Immunological memory underpins:", options: ["Vaccinations", "Digestion", "Respiration", "Circulation"], correct: "Vaccinations" },
      { question: "T-cells are responsible for:", options: ["Cell-mediated immunity", "Carrying oxygen", "Clotting blood", "Filtering urea"], correct: "Cell-mediated immunity" },
      { question: "Which is a specific (adaptive) immune component?", options: ["T-cells", "Skin", "Stomach acid", "Inflammation"], correct: "T-cells" },
      { question: "Negative feedback failure can lead to:", options: ["Chronic disease", "Improved health", "Faster reflexes", "Better vision"], correct: "Chronic disease" },
      { question: "Osmoregulation regulates:", options: ["Water balance", "Body posture", "Heart rate", "Vision"], correct: "Water balance" },
      { question: "Phagocytosis is part of which defence system?", options: ["Innate/non-specific", "Adaptive/specific", "Digestive", "Nervous"], correct: "Innate/non-specific" },
      { question: "B-cells are responsible for:", options: ["Humoral antibody synthesis", "Cell-mediated immunity", "Carrying oxygen", "Clotting blood"], correct: "Humoral antibody synthesis" },
    ],
  },
  {
    title: "Anatomy, Disease Classification & Physics for Health",
    spec_area: "Area 9",
    volume: "Core Paper 2",
    section: "Core Area 9.3 — Anatomy & Physics",
    content: `## Anatomy & Physiology\n\nBody systems: cardiovascular, respiratory, nervous, digestive, urinary, musculoskeletal, endocrine, reproductive, integumentary, lymphatic/immune. Key organ structure and function relevant to nursing practice.\n\n## Disease Classification Systems\n\n- **ICD (International Classification of Diseases):** Codes physical and mental health conditions.\n- **DSM:** Standardises criteria for psychiatric diagnoses.\n- **SNOMED CT:** Common clinical vocabulary for electronic health records.\n\n## Physics for Health\n\n- Pressure and fluid dynamics (blood pressure, IV flow rates).\n- Electricity and magnetism (ECG, defibrillation, MRI principles).\n- Radiation and imaging (X-ray, CT).`,
    sk_codes: ["SK7", "SK17"],
    performance_outcomes: ["PO7", "PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 9", "WHO: Disease Classification", "Clinical Skills.net: Anatomy & Physiology"],
    estimated_duration: 10,
    order_index: 27,
    knowledge_checks: [
      { question: "Which is a body system?", options: ["Cardiovascular", "Chemical", "Geometric", "Financial"], correct: "Cardiovascular" },
      { question: "ICD is used to classify:", options: ["Diseases", "Medication doses", "Staff", "Equipment"], correct: "Diseases" },
      { question: "DSM is used to standardise:", options: ["Psychiatric diagnoses", "Surgical tools", "Lab equipment", "Diet plans"], correct: "Psychiatric diagnoses" },
      { question: "Blood pressure measurement uses which physics concept?", options: ["Pressure", "Electromagnetism", "Radiation", "Optics"], correct: "Pressure" },
      { question: "ECG and defibrillation use principles of:", options: ["Electricity", "Optics", "Thermodynamics", "Acoustics"], correct: "Electricity" },
      { question: "CT imaging uses which technology?", options: ["X-ray/radiation", "Ultrasound only", "Sound waves only", "Magnetism only"], correct: "X-ray/radiation" },
      { question: "SNOMED CT is used in:", options: ["Electronic health records", "Cooking", "Architecture", "Astronomy"], correct: "Electronic health records" },
      { question: "IV flow rates depend on which physics concept?", options: ["Fluid dynamics/pressure", "Magnetism", "Radiation", "Optics"], correct: "Fluid dynamics/pressure" },
      { question: "MRI principles rely on:", options: ["Magnetism", "Radiation", "Sound waves", "Chemical combustion"], correct: "Magnetism" },
      { question: "Which is a body system?", options: ["Integumentary", "Industrial", "Financial", "Geographical"], correct: "Integumentary" },
    ],
  },
];