// Area 3 — Managing Information & Data (3 sub-modules)

export const AREA3_MODULES = [
  {
    title: "Information Governance & Data Protection",
    spec_area: "Area 3",
    volume: "Core Paper 1",
    section: "Core Area 3.1 — Information Governance",
    content: `## Information Governance\n\n- **Data Protection Act 2018 & UK GDPR:** Lawful, fair, transparent, and accurate processing of sensitive patient health data.\n- **NHS Data Security and Protection Standards:** Mandatory for all organisations handling NHS patient data.\n\n## UK GDPR Principles\n\nProcessing must be lawful, fair and transparent; purpose-limited; adequate and minimal; accurate; stored securely; and accountable.\n\nHealth data is classed as **special category data**, requiring extra protection and a lawful basis plus an additional condition for processing.\n\n## Data Breaches\n\nA data breach (loss, theft, or unauthorised disclosure of personal data) must be reported and managed promptly — internally and, where required, to the ICO within 72 hours.`,
    sk_codes: ["SK8", "SK18"],
    performance_outcomes: ["PO3", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 3", "Data Protection Act 2018 & UK GDPR", "NHS Data Security and Protection Standards"],
    estimated_duration: 10,
    order_index: 7,
    knowledge_checks: [
      { question: "Which Act governs data protection in the UK alongside UK GDPR?", options: ["Data Protection Act 2018", "Caldicott Act 1997", "Freedom of Information Act 2000", "Equality Act 2010"], correct: "Data Protection Act 2018" },
      { question: "UK GDPR requires data processing to be:", options: ["Lawful, fair and transparent", "Secret and unregulated", "Profitable", "Unlimited"], correct: "Lawful, fair and transparent" },
      { question: "The NHS Data Security and Protection Standards are:", options: ["Optional guidance", "Mandatory for NHS data handlers", "Only for private companies", "Only for doctors"], correct: "Mandatory for NHS data handlers" },
      { question: "Health data is classed under UK GDPR as:", options: ["Special category data", "Public data", "Anonymous data", "Financial data"], correct: "Special category data" },
      { question: "A data breach must be:", options: ["Reported and managed promptly", "Ignored if minor", "Discussed only with colleagues", "Hidden from patients"], correct: "Reported and managed promptly" },
      { question: "Where required, a serious data breach is reported to the ICO within:", options: ["24 hours", "72 hours", "7 days", "30 days"], correct: "72 hours" },
      { question: "The 'minimum necessary' principle means:", options: ["Use the least data needed for the purpose", "Store everything just in case", "Delete after one use", "Share with everyone"], correct: "Use the least data needed for the purpose" },
      { question: "Accountability under UK GDPR means the organisation must:", options: ["Take responsibility for and demonstrate compliance", "Avoid keeping records", "Share all data publicly", "Process data without limits"], correct: "Take responsibility for and demonstrate compliance" },
      { question: "Purpose limitation means data is collected for:", options: ["Specified, explicit purposes", "Any future use", "Selling to third parties", "Unlimited marketing"], correct: "Specified, explicit purposes" },
      { question: "Discussing patient information on social media is:", options: ["Acceptable if anonymous", "Never acceptable", "Acceptable with consent of friends", "Acceptable on private accounts"], correct: "Never acceptable" },
    ],
  },
  {
    title: "Caldicott Principles & Confidentiality",
    spec_area: "Area 3",
    volume: "Core Paper 1",
    section: "Core Area 3.2 — Caldicott & Confidentiality",
    content: `## The Caldicott Principles\n\n1. Justify the purpose of using confidential information.\n2. Use the minimum necessary confidential information.\n3. Access to confidential information should be on a strict need-to-know basis.\n4. Everyone should understand their responsibilities.\n5. Understand and comply with the law.\n6. The duty to share information can be as important as the duty to protect confidentiality.\n7. The duty to share information for direct care can be as important as the duty to protect confidentiality.\n8. Inform patients and service users about how their information is used.\n\n## The Caldicott Guardian\n\nEach NHS organisation has a Caldicott Guardian — a senior person responsible for protecting patient confidentiality and governing information sharing.\n\n## Confidentiality & Disclosure\n\n- Patient consent for information sharing.\n- Exceptions: where there is a legal requirement, or a safeguarding/public interest justification.\n- Never discuss patient information in public areas or on social media.`,
    sk_codes: ["SK8", "SK18"],
    performance_outcomes: ["PO3", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 3", "NHS Caldicott Guardian Principles"],
    estimated_duration: 10,
    order_index: 8,
    knowledge_checks: [
      { question: "How many Caldicott Principles are there?", options: ["6", "7", "8", "10"], correct: "8" },
      { question: "The first Caldicott Principle is to:", options: ["Share all data freely", "Justify the purpose of using confidential information", "Store data forever", "Avoid electronic records"], correct: "Justify the purpose of using confidential information" },
      { question: "The Caldicott Guardian is responsible for:", options: ["Protecting patient confidentiality", "Cleaning wards", "Ordering medication", "Scheduling surgery"], correct: "Protecting patient confidentiality" },
      { question: "Which is an exception to confidentiality?", options: ["A safeguarding concern", "A gossip magazine request", "Personal curiosity", "Staff convenience"], correct: "A safeguarding concern" },
      { question: "Patient consent for information sharing must be:", options: ["Informed and voluntary", "Coerced", "Assumed", "From a relative only"], correct: "Informed and voluntary" },
      { question: "The need-to-know basis principle limits:", options: ["Access to confidential information", "Number of staff on a ward", "Patient visiting hours", "Medication doses"], correct: "Access to confidential information" },
      { question: "Caldicott Principle 6 means the duty to share information to protect:", options: ["Can override confidentiality", "Never overrides confidentiality", "Is illegal", "Only applies to children"], correct: "Can override confidentiality" },
      { question: "Principle 8 requires organisations to:", options: ["Inform patients how their information is used", "Hide all data use", "Charge for data access", "Delete all records yearly"], correct: "Inform patients how their information is used" },
      { question: "Every NHS organisation must have a:", options: ["Caldicott Guardian", "Marketing director", "Private investor", "Catering manager for data"], correct: "Caldicott Guardian" },
      { question: "Confidential patient information should be discussed:", options: ["In private, on a need-to-know basis", "In public corridors", "On social media", "With any visitor"], correct: "In private, on a need-to-know basis" },
    ],
  },
  {
    title: "Data Quality, Records & Classification Systems",
    spec_area: "Area 3",
    volume: "Core Paper 1",
    section: "Core Area 3.3 — Data Quality & Records",
    content: `## Data Quality & Accuracy\n\n- Accurate, timely, and complete clinical records.\n- Use of standardised classification systems (ICD-10/11, SNOMED CT, OPCS-4).\n- Audit trails for all data access and amendment.\n\n## Records Management\n\n- NHS Records Management Code of Practice 2021.\n- Different record types: paper and electronic health records (EPR/EHR).\n- Records must be retained for defined periods and then securely destroyed.\n\n## Classification Systems\n\n- **ICD-10/11:** classifies diseases.\n- **SNOMED CT:** clinical terminology/vocabulary for electronic health records.\n- **OPCS-4:** classifies surgical procedures and interventions.`,
    sk_codes: ["SK8", "SK18"],
    performance_outcomes: ["PO3", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 3", "NHS Records Management Code of Practice 2021"],
    estimated_duration: 10,
    order_index: 9,
    knowledge_checks: [
      { question: "SNOMED CT is a:", options: ["Clinical terminology/vocabulary", "Ward layout", "Drug brand", "Staff roster"], correct: "Clinical terminology/vocabulary" },
      { question: "ICD-10/11 is used to:", options: ["Classify diseases", "Schedule staff", "Order equipment", "Bill patients"], correct: "Classify diseases" },
      { question: "Which is a data classification system?", options: ["OPCS-4", "Morse", "Waterlow", "SBAR"], correct: "OPCS-4" },
      { question: "Good data quality should be:", options: ["Accurate, timely and complete", "Vague and delayed", "Partial and unverified", "Verbal only"], correct: "Accurate, timely and complete" },
      { question: "An audit trail is used to:", options: ["Track data access and amendments", "Guide visitors", "Measure medication doses", "Plan meals"], correct: "Track data access and amendments" },
      { question: "An electronic patient record is also known as:", options: ["EPR/EHR", "ECG", "EPRR", "e-GIF"], correct: "EPR/EHR" },
      { question: "Which document guides NHS records retention?", options: ["Records Management Code of Practice 2021", "Caldicott Report 1997", "HASAWA 1974", "NMC Code"], correct: "Records Management Code of Practice 2021" },
      { question: "OPCS-4 classifies:", options: ["Surgical procedures and interventions", "Diseases", "Staff rotas", "Medication brands"], correct: "Surgical procedures and interventions" },
      { question: "Records must be retained for defined periods and then:", options: ["Securely destroyed", "Sold", "Shared publicly", "Left in corridors"], correct: "Securely destroyed" },
      { question: "An audit trail supports:", options: ["Accountability and data integrity", "Faster patient meals", "Ward decoration", "Staff holidays"], correct: "Accountability and data integrity" },
    ],
  },
];