// Area 1 — The Healthcare Sector (3 sub-modules)

export const AREA1_MODULES = [
  {
    title: "The T Level Qualification & Sector Structure",
    spec_area: "Area 1",
    volume: "Core Paper 1",
    section: "Core Area 1.1 — The T Level Qualification",
    content: `## The T Level Technical Qualification in Health\n\nT Levels are two-year Level 3 study programmes for students aged 16–19, combining classroom theory, practical learning, and a minimum **315-hour industry placement**. Developed with industry experts, they prepare students for skilled employment, apprenticeships, or higher education.\n\n## Qualification Metrics\n\n- **Qualification Number (QN):** 610/7438/X\n- **First Teaching:** September 2026\n- **Total Guided Learning Hours (GLH):** 1080 hours (510 Core)\n- **Total Qualification Time (TQT):** 1800 hours (870 Core)\n\nTwo mandatory components, equally weighted:\n1. **Core Component (50%)** — Core Paper 1 (36%), Core Paper 2 (24%), Employer Set Project (40%). Graded A*–E.\n2. **Occupational Specialism (50%)** — OS Core (65%) + OS Pathway (35%). Graded Pass, Merit, Distinction.\n\n## Structure of the UK Healthcare Sector\n\nThe sector spans NHS services, private providers, voluntary organisations, and social care. Students must understand how these interconnect and the career pathways they offer.\n\n### Threshold Competence\nUpon completion, students demonstrate 'threshold competence' — the core knowledge and skills to enter healthcare support roles such as Senior Healthcare Support Worker, Therapy Assistant, or Mental Health Support Worker.`,
    sk_codes: ["SK9"],
    performance_outcomes: ["PO1", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 1", "NHS Constitution (England)", "NHS England Career Framework"],
    estimated_duration: 12,
    order_index: 1,
    knowledge_checks: [
      { question: "What does T Level Health QN 610/7438/X stand for?", options: ["Qualification Number", "Quality Notice", "Quota Nominal", "Quantitative Norm"], correct: "Qualification Number" },
      { question: "What is the minimum industry placement duration for a T Level?", options: ["45 hours", "100 hours", "315 hours", "500 hours"], correct: "315 hours" },
      { question: "Total Qualification Time (TQT) for the Core is:", options: ["510 hours", "870 hours", "1080 hours", "1800 hours"], correct: "870 hours" },
      { question: "What percentage of the Core component is the Employer Set Project?", options: ["20%", "40%", "50%", "65%"], correct: "40%" },
      { question: "T Levels are aimed at students aged:", options: ["11–14", "16–19", "21–25", "25+"], correct: "16–19" },
      { question: "Core Paper 1 contributes what percentage of the Core component?", options: ["24%", "36%", "40%", "50%"], correct: "36%" },
      { question: "The Core component is graded:", options: ["Pass/Merit/Distinction", "A*–E", "1–9", "Gold/Silver/Bronze"], correct: "A*–E" },
      { question: "A Senior Healthcare Support Worker role is an example of:", options: ["Threshold competence", "Consultant grade", "Pre-registration doctor", "Tertiary specialist"], correct: "Threshold competence" },
      { question: "T Levels combine classroom theory, practical learning and:", options: ["A paid salary", "An industry placement", "A university degree", "Online-only study"], correct: "An industry placement" },
      { question: "The Occupational Specialism is graded:", options: ["A*–E", "Pass, Merit, Distinction", "1–9", "Ungraded"], correct: "Pass, Merit, Distinction" },
    ],
  },
  {
    title: "The NHS — Tiers of Care & Commissioning",
    spec_area: "Area 1",
    volume: "Core Paper 1",
    section: "Core Area 1.2 — The NHS",
    content: `## The NHS\n\n- Founded in 1948 on the principle of healthcare free at the point of need.\n- Funded through general taxation; commissioned by integrated care boards (ICBs).\n\n## Tiers of Care\n\n- **Primary care:** GP, pharmacy, dentistry, optometry, community nursing — first contact, usually in the community.\n- **Secondary care:** planned hospital care, acute trusts, A&E, maternity — specialist care accessed via referral.\n- **Tertiary care:** specialist regional/national services (e.g. transplant, neurosurgery).\n\n## Commissioning\n\nIntegrated Care Boards (ICBs) plan and commission most NHS services locally, working within Integrated Care Systems (ICSs) to join up health and social care.\n\n## The NHS Constitution\n\nSix values: working together for patients, respect and dignity, commitment to quality of care, compassion, improving lives, everyone counts.`,
    sk_codes: ["SK9"],
    performance_outcomes: ["PO1", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 1", "NHS Constitution (England)", "NHS England: Integrated Care Systems"],
    estimated_duration: 10,
    order_index: 2,
    knowledge_checks: [
      { question: "In what year was the NHS founded?", options: ["1908", "1948", "1974", "1998"], correct: "1948" },
      { question: "The NHS is primarily funded through:", options: ["Private insurance", "General taxation", "Patient fees", "Charitable donations"], correct: "General taxation" },
      { question: "GP, pharmacy, dentistry and community nursing are examples of:", options: ["Tertiary care", "Secondary care", "Primary care", "Quaternary care"], correct: "Primary care" },
      { question: "Acute hospital trusts and A&E departments are part of which care tier?", options: ["Primary", "Secondary", "Tertiary", "Community"], correct: "Secondary" },
      { question: "Transplant and neurosurgery are examples of which care tier?", options: ["Primary", "Secondary", "Tertiary", "Self-care"], correct: "Tertiary" },
      { question: "Who commissions NHS services in England?", options: ["Local councils", "Integrated Care Boards", "GMC", "CQC"], correct: "Integrated Care Boards" },
      { question: "Which of these is an NHS Constitution value?", options: ["Compassion", "Profitability", "Competition", "Exclusivity"], correct: "Compassion" },
      { question: "How many values are listed in the NHS Constitution?", options: ["4", "5", "6", "7"], correct: "6" },
      { question: "Integrated Care Systems (ICSs) aim to:", options: ["Join up health and social care", "Replace GPs", "Privatise the NHS", "Reduce hospital beds"], correct: "Join up health and social care" },
      { question: "Access to secondary care is usually via:", options: ["Self-referral only", "A GP referral", "Walking in", "Online voting"], correct: "A GP referral" },
    ],
  },
  {
    title: "Regulation, Professional Bodies & Career Pathways",
    spec_area: "Area 1",
    volume: "Core Paper 1",
    section: "Core Area 1.3 — Regulation & Careers",
    content: `## Regulation & Professional Bodies\n\n- **CQC** — regulates and inspects health and adult social care providers.\n- **NMC** — regulates nurses and midwives.\n- **GMC** — regulates doctors.\n- **HCPC** — regulates allied health professionals (e.g. physiotherapists, radiographers, paramedics).\n\n## Why Regulation Matters\n\nRegulation protects the public by setting standards of education, conduct and competence. Registered professionals must meet these standards to practise and can be struck off for serious misconduct.\n\n## Career Pathways\n\nThe NHS Career Framework has nine levels, from support roles (Levels 2–4) through registered practitioners (Level 5+) to consultant and director-level roles (Levels 8+). T Level graduates typically enter at support-worker level and can progress through further study and apprenticeships.`,
    sk_codes: ["SK9"],
    performance_outcomes: ["PO1", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 1", "CQC: How We Regulate", "NHS England Career Framework"],
    estimated_duration: 10,
    order_index: 3,
    knowledge_checks: [
      { question: "Which body inspects and regulates health and adult social care providers in England?", options: ["NMC", "CQC", "GMC", "HCPC"], correct: "CQC" },
      { question: "Which body regulates nurses and midwives?", options: ["GMC", "HCPC", "NMC", "CQC"], correct: "NMC" },
      { question: "Which body regulates doctors?", options: ["NMC", "GMC", "HCPC", "CQC"], correct: "GMC" },
      { question: "Which body regulates allied health professionals such as physiotherapists?", options: ["GMC", "NMC", "HCPC", "CQC"], correct: "HCPC" },
      { question: "The main purpose of professional regulation is to:", options: ["Protect the public", "Increase profits", "Limit workforce", "Replace training"], correct: "Protect the public" },
      { question: "A professional found guilty of serious misconduct can be:", options: ["Struck off the register", "Given a pay rise", "Promoted", "Ignored"], correct: "Struck off the register" },
      { question: "The NHS Career Framework has how many levels?", options: ["5", "7", "9", "12"], correct: "9" },
      { question: "T Level graduates typically enter the workforce at:", options: ["Consultant level", "Support-worker level", "Director level", "Pre-registration doctor"], correct: "Support-worker level" },
      { question: "A paramedic is regulated by the:", options: ["HCPC", "GMC", "NMC", "CQC"], correct: "HCPC" },
      { question: "Registered professionals must meet standards of:", options: ["Education, conduct and competence", "Profitability", "Marketing", "Hospital size"], correct: "Education, conduct and competence" },
    ],
  },
];