// Area 6 — Health & Wellbeing (3 sub-modules)

export const AREA6_MODULES = [
  {
    title: "Determinants of Health & Health Inequalities",
    spec_area: "Area 6",
    volume: "Core Paper 1",
    section: "Core Area 6.1 — Determinants & Inequalities",
    content: `## Determinants of Health\n\n- **Biological:** genetics, age, sex.\n- **Behavioural/lifestyle:** diet, physical activity, smoking, alcohol, substance use.\n- **Social and economic:** income, education, employment, housing, social support.\n- **Environmental:** pollution, access to green space, safe communities.\n\n## Health Inequalities\n\n- Differences in health outcomes between groups.\n- **Marmot Review:** fair society, healthy lives; reducing the gradient.\n- Life expectancy and healthy life expectancy gaps.\n\n## Healthy Life Expectancy\n\nHealthy life expectancy differs from life expectancy by counting only years lived in good health.`,
    sk_codes: ["SK9", "SK15"],
    performance_outcomes: ["PO6", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 6", "Marmot Review (Institute of Health Equity)"],
    estimated_duration: 10,
    order_index: 16,
    knowledge_checks: [
      { question: "Which is a social determinant of health?", options: ["Education", "Eye colour", "Blood group", "Heart rate"], correct: "Education" },
      { question: "The Marmot Review addressed:", options: ["Health inequalities", "Hospital finances", "Staff rotas", "Building design"], correct: "Health inequalities" },
      { question: "Which is a behavioural determinant of health?", options: ["Smoking", "Income", "Housing", "Sex"], correct: "Smoking" },
      { question: "Healthy life expectancy differs from life expectancy by:", options: ["Years lived in good health", "Years in hospital only", "Years working", "Years in education"], correct: "Years lived in good health" },
      { question: "Which is an environmental determinant of health?", options: ["Air pollution", "Genetics", "Age", "Blood type"], correct: "Air pollution" },
      { question: "Determinants of health include biological, behavioural, social and:", options: ["Environmental", "Astrological", "Meteorological", "Geological only"], correct: "Environmental" },
      { question: "Which is a biological determinant of health?", options: ["Genetics", "Income", "Education", "Housing"], correct: "Genetics" },
      { question: "The Marmot Review's aim was to:", options: ["Reduce the health gradient", "Increase private healthcare", "Reduce hospital staffing", "Limit screening"], correct: "Reduce the health gradient" },
      { question: "Income and employment are examples of:", options: ["Social and economic determinants", "Biological determinants", "Environmental determinants", "Genetic determinants"], correct: "Social and economic determinants" },
      { question: "Health inequalities describe differences in:", options: ["Health outcomes between groups", "Hospital architecture", "Staff uniforms", "Catering menus"], correct: "Health outcomes between groups" },
    ],
  },
  {
    title: "Health Promotion & Disease Prevention",
    spec_area: "Area 6",
    volume: "Core Paper 1",
    section: "Core Area 6.2 — Health Promotion & Prevention",
    content: `## Promoting Health & Wellbeing\n\n- **Health promotion:** enabling people to increase control over their health.\n- **Disease prevention:**\n  - Primary (preventing onset)\n  - Secondary (early detection)\n  - Tertiary (managing established disease)\n- Behaviour change models: COM-B (Capability, Opportunity, Motivation).\n\n## Key Public Health Topics\n\nSmoking cessation, alcohol reduction, healthy weight, immunisation, screening, mental wellbeing.\n\n## Prevention Examples\n\n- Immunisation = primary prevention.\n- Screening programmes = secondary prevention.\n- Cardiac rehabilitation = tertiary prevention.`,
    sk_codes: ["SK9", "SK15"],
    performance_outcomes: ["PO6", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 6", "WHO: Health Promotion"],
    estimated_duration: 10,
    order_index: 17,
    knowledge_checks: [
      { question: "Primary disease prevention aims to:", options: ["Prevent disease onset", "Detect disease early", "Manage established disease", "Provide end-of-life care"], correct: "Prevent disease onset" },
      { question: "Secondary prevention focuses on:", options: ["Early detection and intervention", "Preventing onset", "Palliative care", "Surgery"], correct: "Early detection and intervention" },
      { question: "Tertiary prevention involves:", options: ["Managing established disease", "Preventing onset", "Screening", "Vaccination"], correct: "Managing established disease" },
      { question: "Health promotion is about:", options: ["Enabling people to increase control over their health", "Treating disease only", "Reducing hospital beds", "Increasing medication"], correct: "Enabling people to increase control over their health" },
      { question: "COM-B stands for:", options: ["Capability, Opportunity, Motivation", "Care, Outcomes, Monitoring, Behaviour", "Clinical, Operational, Medical, Benefit", "Community, Outreach, Mental, Body"], correct: "Capability, Opportunity, Motivation" },
      { question: "Immunisation is an example of which prevention level?", options: ["Primary", "Secondary", "Tertiary", "Quaternary"], correct: "Primary" },
      { question: "Screening programmes are an example of:", options: ["Secondary prevention", "Primary prevention", "Tertiary prevention", "Palliative care"], correct: "Secondary prevention" },
      { question: "Which is a lifestyle risk factor?", options: ["Excess alcohol", "Gender", "Ageing", "Genetic inheritance"], correct: "Excess alcohol" },
      { question: "Cardiac rehabilitation is an example of:", options: ["Tertiary prevention", "Primary prevention", "Secondary prevention", "Screening"], correct: "Tertiary prevention" },
      { question: "COM-B is a model of:", options: ["Behaviour change", "Waste disposal", "Drug calculation", "Wound care"], correct: "Behaviour change" },
    ],
  },
  {
    title: "Mental Wellbeing & Life-Course Health",
    spec_area: "Area 6",
    volume: "Core Paper 1",
    section: "Core Area 6.3 — Mental Wellbeing & Life Stages",
    content: `## Mental Health & Wellbeing\n\n- Mental health parity with physical health.\n- Risk factors and protective factors.\n- **Five Ways to Wellbeing:** Connect, Be active, Take notice, Keep learning, Give.\n\n## Life Stages\n\nHealth needs vary across the life course: infancy, childhood, adolescence, adulthood, older age. Person-centred approaches should be appropriate to each stage.\n\n## Parity of Esteem\n\nMental health should have parity of esteem with physical health — equal priority in access, funding and quality of care.`,
    sk_codes: ["SK9", "SK15"],
    performance_outcomes: ["PO6", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 6", "NHS: Five Ways to Wellbeing"],
    estimated_duration: 10,
    order_index: 18,
    knowledge_checks: [
      { question: "Which is one of the Five Ways to Wellbeing?", options: ["Be active", "Earn more", "Sleep less", "Work harder"], correct: "Be active" },
      { question: "How many Five Ways to Wellbeing are there?", options: ["3", "4", "5", "7"], correct: "5" },
      { question: "Mental health should have parity of esteem with:", options: ["Physical health", "Financial health", "Hospital budgets", "Staffing levels"], correct: "Physical health" },
      { question: "Which is a protective factor for mental wellbeing?", options: ["Social support", "Social isolation", "Substance misuse", "Long-term unemployment"], correct: "Social support" },
      { question: "Health needs across the life course means:", options: ["Needs vary at different life stages", "Everyone needs identical care", "Only older people need care", "Only children need care"], correct: "Needs vary at different life stages" },
      { question: "'Give' as one of the Five Ways to Wellbeing refers to:", options: ["Giving time or help to others", "Giving up on goals", "Giving medication", "Giving advice only"], correct: "Giving time or help to others" },
      { question: "'Take notice' as a Way to Wellbeing refers to:", options: ["Being aware of the present moment", "Filing incident reports", "Taking medication", "Monitoring vital signs"], correct: "Being aware of the present moment" },
      { question: "Parity of esteem means:", options: ["Equal priority for mental and physical health", "Equal pay for all staff", "Equal ward sizes", "Equal visiting hours"], correct: "Equal priority for mental and physical health" },
      { question: "Which is a life stage?", options: ["Adolescence", "Asthma", "Asepsis", "Audit"], correct: "Adolescence" },
      { question: "'Keep learning' as a Way to Wellbeing supports:", options: ["Mental stimulation and growth", "Drug calculation", "Waste disposal", "Manual handling"], correct: "Mental stimulation and growth" },
    ],
  },
];