// Area 5 — Providing Person-Centred Care (3 sub-modules)

export const AREA5_MODULES = [
  {
    title: "Person-Centred Principles & the Nursing Process",
    spec_area: "Area 5",
    volume: "Core Paper 1",
    section: "Core Area 5.1 — Person-Centred Principles",
    content: `## Core Principles\n\n- Working in partnership with individuals and their families.\n- Respecting individual dignity, choices, beliefs, and preferences.\n- Promoting independence and wellbeing.\n- Holistic assessment covering physical, psychological, social, and spiritual needs.\n\n## The Nursing Process\n\n1. **Assessment** — holistic data collection.\n2. **Diagnosis** — identify actual and potential problems.\n3. **Planning** — set SMART goals, agree interventions.\n4. **Implementation** — deliver care.\n5. **Evaluation** — review outcomes, revise plan.\n\n## SMART Goals\n\nSpecific, Measurable, Achievable, Relevant, Time-bound.`,
    sk_codes: ["SK8", "SK9", "SK18"],
    performance_outcomes: ["PO5", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 5", "NMC Code: Prioritise People", "NHS England: Person-Centred Care"],
    estimated_duration: 10,
    order_index: 13,
    knowledge_checks: [
      { question: "Person-centred care means working in:", options: ["Partnership with individuals", "Isolation", "Compliance only", "Silence"], correct: "Partnership with individuals" },
      { question: "SMART goals are:", options: ["Specific, Measurable, Achievable, Relevant, Time-bound", "Simple, Meaningful, Accurate, Recorded, Tested", "Standard, Medical, Assessed, Reviewed, Treated", "Safe, Modern, Adaptable, Reliable, Tested"], correct: "Specific, Measurable, Achievable, Relevant, Time-bound" },
      { question: "How many stages are in the nursing process?", options: ["3", "4", "5", "7"], correct: "5" },
      { question: "Holistic assessment considers physical, psychological, social and:", options: ["Spiritual needs", "Financial income", "Political views", "Fashion sense"], correct: "Spiritual needs" },
      { question: "The first stage of the nursing process is:", options: ["Assessment", "Diagnosis", "Planning", "Evaluation"], correct: "Assessment" },
      { question: "The final stage of the nursing process is:", options: ["Evaluation", "Assessment", "Diagnosis", "Planning"], correct: "Evaluation" },
      { question: "Promoting independence supports:", options: ["Wellbeing and autonomy", "Dependency", "Restraint", "Isolation"], correct: "Wellbeing and autonomy" },
      { question: "Dignity in care includes:", options: ["Respecting privacy and choices", "Ignoring preferences", "Rushing care", "Public discussion of conditions"], correct: "Respecting privacy and choices" },
      { question: "SMART goals should be:", options: ["Time-bound", "Vague", "Unwritten", "Unlimited"], correct: "Time-bound" },
      { question: "Holistic care means considering the:", options: ["Whole person", "Physical symptoms only", "Diagnosis only", "Cost only"], correct: "Whole person" },
    ],
  },
  {
    title: "Consent, Capacity & Equality",
    spec_area: "Area 5",
    volume: "Core Paper 1",
    section: "Core Area 5.2 — Consent & Equality",
    content: `## Consent & Capacity\n\n- **Mental Capacity Act 2005:** Presumption of capacity; right to make unwise decisions; best interests; least restrictive option.\n- Consent must be voluntary, informed, and capacity-based.\n\n## Equality, Diversity & Inclusion\n\n- **Equality Act 2010:** protected characteristics.\n- Reasonable adjustments for disabled individuals.\n- Culturally competent, anti-discriminatory practice.\n\n## Best Interests\n\nWhere a person lacks capacity, decisions made in their best interests must consider their wishes, values, beliefs, and the least restrictive option.`,
    sk_codes: ["SK8", "SK9", "SK18"],
    performance_outcomes: ["PO5", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 5", "Mental Capacity Act 2005", "Equality Act 2010"],
    estimated_duration: 10,
    order_index: 14,
    knowledge_checks: [
      { question: "Which Act presumes capacity unless proven otherwise?", options: ["Mental Capacity Act 2005", "Care Act 2014", "Equality Act 2010", "Children Act 2004"], correct: "Mental Capacity Act 2005" },
      { question: "Which is a protected characteristic under the Equality Act 2010?", options: ["Age", "Eye colour", "Shoe size", "Favourite food"], correct: "Age" },
      { question: "Valid consent must be voluntary, informed and:", options: ["Capacity-based", "Witnessed by a doctor", "Written only", "Permanent"], correct: "Capacity-based" },
      { question: "Under the Mental Capacity Act, an unwise decision:", options: ["Does not by itself prove incapacity", "Always proves incapacity", "Is illegal", "Requires restraint"], correct: "Does not by itself prove incapacity" },
      { question: "The 'least restrictive option' principle supports:", options: ["Maximising autonomy", "Maximum restraint", "Constant sedation", "Locking doors"], correct: "Maximising autonomy" },
      { question: "Reasonable adjustments are required for:", options: ["Disabled individuals", "All visitors", "Staff only", "Doctors only"], correct: "Disabled individuals" },
      { question: "Culturally competent practice means:", options: ["Respecting cultural beliefs and preferences", "Ignoring culture", "Imposing personal beliefs", "Treating everyone identically regardless of need"], correct: "Respecting cultural beliefs and preferences" },
      { question: "Anti-discriminatory practice requires:", options: ["Challenging discrimination", "Ignoring discrimination", "Joining in discrimination", "Accepting discrimination"], correct: "Challenging discrimination" },
      { question: "Best interests decisions under the MCA must consider:", options: ["The person's wishes and values", "Cost alone", "Staff convenience", "Hospital targets"], correct: "The person's wishes and values" },
      { question: "How many protected characteristics are in the Equality Act 2010?", options: ["7", "9", "11", "13"], correct: "9" },
    ],
  },
  {
    title: "Communication & Promoting Wellbeing",
    spec_area: "Area 5",
    volume: "Core Paper 1",
    section: "Core Area 5.3 — Communication & Wellbeing",
    content: `## Communication\n\n- Therapeutic communication: active listening, empathy, non-verbal cues.\n- Addressing barriers: sensory impairment, language, cognitive impairment, learning disability.\n\n## Promoting Wellbeing & Independence\n\n- Encouraging self-care and autonomy.\n- Social prescribing and community support.\n\n## Empathy\n\nEmpathy means understanding and sharing another's feelings — distinct from sympathy (feeling for) and from giving advice.`,
    sk_codes: ["SK8", "SK9", "SK18"],
    performance_outcomes: ["PO5", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 5", "NHS England: Person-Centred Care"],
    estimated_duration: 10,
    order_index: 15,
    knowledge_checks: [
      { question: "Active listening is a component of:", options: ["Therapeutic communication", "Medication administration", "Hand hygiene", "Wound dressing"], correct: "Therapeutic communication" },
      { question: "Which is a communication barrier?", options: ["Sensory impairment", "Good lighting", "Quiet room", "Written notes"], correct: "Sensory impairment" },
      { question: "Empathy in communication means:", options: ["Understanding and sharing another's feelings", "Giving medical advice only", "Completing paperwork", "Avoiding eye contact"], correct: "Understanding and sharing another's feelings" },
      { question: "Social prescribing refers to:", options: ["Non-medical community support referrals", "Prescribing medication", "Prescribing rest", "Prescribing surgery"], correct: "Non-medical community support referrals" },
      { question: "Non-verbal communication includes:", options: ["Body language and facial expression", "Written reports only", "Drug charts", "Blood pressure readings"], correct: "Body language and facial expression" },
      { question: "A learning disability is an example of a:", options: ["Communication consideration", "Medication route", "Waste stream", "Vital sign"], correct: "Communication consideration" },
      { question: "Promoting self-care supports:", options: ["Independence and autonomy", "Dependency", "Restraint", "Isolation"], correct: "Independence and autonomy" },
      { question: "Social prescribing connects people to:", options: ["Community support", "Surgery", "Medication", "Hospital admissions"], correct: "Community support" },
      { question: "Therapeutic communication aims to:", options: ["Build trust and understanding", "Replace clinical assessment", "Speed up discharge", "Reduce documentation"], correct: "Build trust and understanding" },
      { question: "A language barrier can be reduced by:", options: ["Using an interpreter", "Speaking louder", "Ignoring the patient", "Using jargon"], correct: "Using an interpreter" },
    ],
  },
];