// Area 7 — Safeguarding (3 sub-modules)

export const AREA7_MODULES = [
  {
    title: "Safeguarding Legislation & Principles",
    spec_area: "Area 7",
    volume: "Core Paper 1",
    section: "Core Area 7.1 — Legislation & Principles",
    content: `## Key Legislation\n\n- **Care Act 2014:** Six safeguarding principles — Empowerment, Prevention, Proportionality, Protection, Partnership, Accountability.\n- **Children Act 1989/2004:** paramountcy of the child's welfare; duty to safeguard children.\n- **The Prevent Duty Guidance (2023):** identify early indicators of radicalisation; challenge extremist ideology.\n- **Mental Capacity Act 2005 & Deprivation of Liberty Safeguards (DoLS).**\n- **Modern Slavery Act 2015.**\n\n## The Six Principles\n\nEmpowerment, Prevention, Proportionality, Protection, Partnership, Accountability.\n\n## Who Is at Risk?\n\nAn adult at risk is someone aged 18+ with care and support needs who may be unable to protect themselves. All staff have a duty to safeguard children.`,
    sk_codes: ["SK8", "SK10", "SK18"],
    performance_outcomes: ["PO7", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 7", "Care Act 2014", "Children Act 1989/2004", "Prevent Duty Guidance 2023", "Modern Slavery Act 2015"],
    estimated_duration: 10,
    order_index: 19,
    knowledge_checks: [
      { question: "How many safeguarding principles are in the Care Act 2014?", options: ["4", "5", "6", "7"], correct: "6" },
      { question: "Which is a Care Act 2014 safeguarding principle?", options: ["Empowerment", "Efficiency", "Economy", "Excellence"], correct: "Empowerment" },
      { question: "The Children Act makes the welfare of the child:", options: ["Paramount", "Secondary", "Optional", "Confidential only"], correct: "Paramount" },
      { question: "Which Act addresses radicalisation and extremism?", options: ["Prevent Duty Guidance 2023", "COSHH 2002", "PUWER 1998", "HASAWA 1974"], correct: "Prevent Duty Guidance 2023" },
      { question: "Which Act addresses modern slavery?", options: ["Modern Slavery Act 2015", "Care Act 2014", "Children Act 1989", "Equality Act 2010"], correct: "Modern Slavery Act 2015" },
      { question: "DoLS stands for:", options: ["Deprivation of Liberty Safeguards", "Duty of Local Safeguarding", "Direct Observation of Lifestyle Signs", "Disclosure of Localised Standards"], correct: "Deprivation of Liberty Safeguards" },
      { question: "An adult at risk is aged:", options: ["Under 16", "Under 18", "18 or over", "65 or over only"], correct: "18 or over" },
      { question: "Who has a duty to safeguard children?", options: ["All staff", "Only doctors", "Only social workers", "Only nurses"], correct: "All staff" },
      { question: "The safeguarding principle 'Proportionality' means:", options: ["Responding in the least intrusive way appropriate", "Always removing the person", "Ignoring low-level concerns", "Only acting at crisis point"], correct: "Responding in the least intrusive way appropriate" },
      { question: "The 'Prevention' principle means:", options: ["Acting before harm occurs", "Waiting for harm", "Punishing after harm", "Ignoring risk"], correct: "Acting before harm occurs" },
    ],
  },
  {
    title: "Recognising & Responding to Abuse",
    spec_area: "Area 7",
    volume: "Core Paper 1",
    section: "Core Area 7.2 — Recognising & Responding",
    content: `## Types of Abuse\n\nPhysical, emotional/psychological, sexual, financial, neglect, discriminatory, organisational, self-neglect, modern slavery, domestic abuse.\n\n## Recognising Signs\n\n- Unexplained injuries, changes in behaviour, fear, withdrawal, poor hygiene, unexplained financial changes.\n\n## Responding\n\n- Listen, reassure, don't investigate; record; report to safeguarding lead.\n\n## The Safeguarding Lead\n\nA designated person in every organisation with responsibility for safeguarding concerns and referrals.\n\n## MASH\n\nMulti-Agency Safeguarding Hub — coordinates safeguarding referrals across agencies.`,
    sk_codes: ["SK8", "SK10", "SK18"],
    performance_outcomes: ["PO7", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 7", "Care Act 2014"],
    estimated_duration: 10,
    order_index: 20,
    knowledge_checks: [
      { question: "Which is a type of abuse?", options: ["Financial", "Festive", "Formal", "Friendly"], correct: "Financial" },
      { question: "When responding to a safeguarding disclosure, you should:", options: ["Listen, reassure, record, report — not investigate", "Investigate thoroughly yourself", "Confront the alleged abuser", "Tell no one"], correct: "Listen, reassure, record, report — not investigate" },
      { question: "Which is a recognised sign of abuse?", options: ["Unexplained injuries", "Happy mood", "Stable weight", "Good hygiene"], correct: "Unexplained injuries" },
      { question: "Self-neglect is:", options: ["A recognised type of abuse", "A criminal offence by the victim", "Always a lifestyle choice to respect", "Not a safeguarding concern"], correct: "A recognised type of abuse" },
      { question: "Domestic abuse can include:", options: ["Physical, emotional, sexual and financial abuse", "Only physical violence", "Only financial control", "Only verbal arguments"], correct: "Physical, emotional, sexual and financial abuse" },
      { question: "The safeguarding lead is:", options: ["A designated person in every organisation", "A government minister", "A police role only", "A voluntary role with no authority"], correct: "A designated person in every organisation" },
      { question: "Which is an example of organisational abuse?", options: ["Poor institutional care practices", "A single rude comment", "An accidental fall", "A missed appointment"], correct: "Poor institutional care practices" },
      { question: "Discriminatory abuse is based on:", options: ["A protected characteristic", "A medical diagnosis", "A random factor", "An accident"], correct: "A protected characteristic" },
      { question: "Neglect involves:", options: ["Failure to meet basic needs", "Active violence", "Theft of money", "Verbal insults"], correct: "Failure to meet basic needs" },
      { question: "MASH stands for:", options: ["Multi-Agency Safeguarding Hub", "Medical Assessment of Safety Hazards", "Mandatory Adult Safety Helpline", "Minor Ailment Service Hub"], correct: "Multi-Agency Safeguarding Hub" },
    ],
  },
  {
    title: "Information Sharing & Multi-Agency Working",
    spec_area: "Area 7",
    volume: "Core Paper 1",
    section: "Core Area 7.3 — Information Sharing",
    content: `## Information Sharing\n\n- The duty to share information to protect can override confidentiality (Caldicott Principle 6).\n- Share on a need-to-know basis, factually and promptly.\n\n## Recording a Concern\n\nRecord factually, promptly and objectively — what was said, what was seen, actions taken. Use the person's own words where relevant.\n\n## Multi-Agency Working\n\nSafeguarding is a shared responsibility across health, social care, police and education. Effective information sharing underpins coordinated protection.`,
    sk_codes: ["SK8", "SK10", "SK18"],
    performance_outcomes: ["PO7", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 7", "Care Act 2014", "Caldicott Principles"],
    estimated_duration: 10,
    order_index: 21,
    knowledge_checks: [
      { question: "Caldicott Principle 6 means the duty to share information to protect:", options: ["Can override confidentiality", "Never overrides confidentiality", "Is illegal", "Only applies to children"], correct: "Can override confidentiality" },
      { question: "When recording a safeguarding concern, you should:", options: ["Record factually, promptly and objectively", "Record your opinions only", "Wait a week", "Record verbally only"], correct: "Record factually, promptly and objectively" },
      { question: "Safeguarding is a responsibility shared across:", options: ["Health, social care, police and education", "Doctors only", "Nurses only", "The patient's family only"], correct: "Health, social care, police and education" },
      { question: "Safeguarding information should be shared on a:", options: ["Need-to-know basis", "Public broadcast", "Social media post", "Need-to-gossip basis"], correct: "Need-to-know basis" },
      { question: "When recording what a person said, you should:", options: ["Use their own words where relevant", "Paraphrase loosely", "Add your interpretation", "Omit detail"], correct: "Use their own words where relevant" },
      { question: "Multi-agency working is underpinned by:", options: ["Effective information sharing", "Secrecy", "Single-agency control", "Avoiding records"], correct: "Effective information sharing" },
      { question: "A safeguarding referral should be made to:", options: ["The safeguarding lead or MASH", "The local newspaper", "The patient's family", "No one"], correct: "The safeguarding lead or MASH" },
      { question: "Confidentiality can be lawfully breached when:", options: ["There is a safeguarding or public interest justification", "You feel like it", "A colleague asks", "It is convenient"], correct: "There is a safeguarding or public interest justification" },
      { question: "The 'Partnership' safeguarding principle refers to:", options: ["Agencies working together", "Private companies", "Patient payments", "Hospital catering"], correct: "Agencies working together" },
      { question: "Objective recording means:", options: ["Stating facts without opinion", "Adding personal views", "Guessing causes", "Omitting dates"], correct: "Stating facts without opinion" },
    ],
  },
];