// Area 8 — Core Science Concepts (3 sub-modules)

export const AREA8_MODULES = [
  {
    title: "Cell Theory & Ultrastructure",
    spec_area: "Area 8",
    volume: "Core Paper 2",
    section: "Core Area 8.1 — Cells",
    content: `## Cell Theory\n\n1. All living organisms are composed of one or more functional cells.\n2. Cells are the basic structural and organisational unit of life.\n3. All cells arise from pre-existing cells through division.\n\n## Eukaryotic Cell Ultrastructure\n\n- **Cell Surface Membrane:** Fluid mosaic model; controls selective transport and displays cell surface antigens.\n- **Nucleus:** Houses genetic material (DNA) and controls gene expression.\n- **Mitochondria:** Double-membraned; site of aerobic respiration producing ATP.\n- **Rough Endoplasmic Reticulum (RER):** Ribosome-studded; protein translation, packaging, and transport.\n- **Golgi Apparatus:** Modifies, packages, and sorts proteins for secretion.\n- **Lysosomes:** Contain digestive enzymes for intracellular waste breakdown.`,
    sk_codes: ["SK17"],
    performance_outcomes: ["PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 8", "NHS: Cell Biology Reference"],
    estimated_duration: 10,
    order_index: 22,
    knowledge_checks: [
      { question: "How many tenets make up cell theory?", options: ["2", "3", "4", "5"], correct: "3" },
      { question: "All cells arise from:", options: ["Pre-existing cells", "Spontaneous generation", "Air", "Light"], correct: "Pre-existing cells" },
      { question: "Which organelle is the site of aerobic respiration?", options: ["Mitochondria", "Nucleus", "Golgi", "Lysosome"], correct: "Mitochondria" },
      { question: "The cell membrane is described by which model?", options: ["Fluid mosaic", "Solid lattice", "Rigid shell", "Sponge model"], correct: "Fluid mosaic" },
      { question: "The nucleus houses which genetic material?", options: ["DNA", "RNA only", "Lipids", "Glycogen"], correct: "DNA" },
      { question: "RER is studded with which structures?", options: ["Ribosomes", "Lysosomes", "Vacuoles", "Centrioles"], correct: "Ribosomes" },
      { question: "The Golgi apparatus modifies, packages and sorts:", options: ["Proteins", "DNA", "Carbohydrates only", "Water"], correct: "Proteins" },
      { question: "Lysosomes contain:", options: ["Digestive enzymes", "DNA", "Chlorophyll", "Insulin"], correct: "Digestive enzymes" },
      { question: "ATP is produced mainly during:", options: ["Aerobic respiration", "Diffusion", "Osmosis", "Transcription"], correct: "Aerobic respiration" },
      { question: "The cell surface membrane displays:", options: ["Cell surface antigens", "Ribosomes", "DNA", "Glycogen"], correct: "Cell surface antigens" },
    ],
  },
  {
    title: "Biochemistry — Macromolecules & Enzymes",
    spec_area: "Area 8",
    volume: "Core Paper 2",
    section: "Core Area 8.2 — Biochemistry",
    content: `## Biochemistry\n\n- **Triglyceride** = 1 Glycerol + 3 Fatty Acids.\n- **Proteins:** Primary → secondary → tertiary → quaternary structure.\n- **Carbohydrates:** Prime metabolic fuel; stored as glycogen.\n- **Lipids:** Amphipathic phospholipids form bilayers (hydrophilic head, hydrophobic tail).\n- **Enzymes:** Biological catalysts lowering activation energy; affected by temperature, pH, and substrate concentration.\n\n## Glycogen Storage\n\nThe liver and muscle store glucose as glycogen in humans.`,
    sk_codes: ["SK17"],
    performance_outcomes: ["PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 8", "Clinical Skills.net: Biochemistry Fundamentals"],
    estimated_duration: 10,
    order_index: 23,
    knowledge_checks: [
      { question: "A triglyceride consists of 1 glycerol and how many fatty acids?", options: ["1", "2", "3", "4"], correct: "3" },
      { question: "Enzymes act as biological catalysts by lowering:", options: ["Activation energy", "Temperature", "pH", "Substrate concentration"], correct: "Activation energy" },
      { question: "Phospholipids have a hydrophilic head and a hydrophobic:", options: ["Tail", "Nucleus", "Membrane", "Core"], correct: "Tail" },
      { question: "Which stores glucose as glycogen in humans?", options: ["Liver and muscle", "Brain only", "Skin", "Bone"], correct: "Liver and muscle" },
      { question: "Which is a protein structure level?", options: ["Tertiary", "Cuboidal", "Hexagonal", "Radial"], correct: "Tertiary" },
      { question: "Enzyme activity is affected by temperature, pH and:", options: ["Substrate concentration", "Light colour", "Sound", "Humidity"], correct: "Substrate concentration" },
      { question: "Carbohydrates are the body's prime:", options: ["Metabolic fuel", "Structural protein", "Genetic material", "Enzyme"], correct: "Metabolic fuel" },
      { question: "A phospholipid is described as:", options: ["Amphipathic", "Hydrophobic only", "Hydrophilic only", "Inert"], correct: "Amphipathic" },
      { question: "Protein structure levels in order are:", options: ["Primary, secondary, tertiary, quaternary", "Alpha, beta, gamma, delta", "A, B, C, D", "1D, 2D, 3D, 4D"], correct: "Primary, secondary, tertiary, quaternary" },
      { question: "Enzymes are:", options: ["Biological catalysts", "Genetic material", "Energy stores", "Structural fibres only"], correct: "Biological catalysts" },
    ],
  },
  {
    title: "Genetics & Chemistry for Health",
    spec_area: "Area 8",
    volume: "Core Paper 2",
    section: "Core Area 8.3 — Genetics & Chemistry",
    content: `## Genetics\n\n- DNA structure (double helix), replication, transcription, translation.\n- Mendelian inheritance and genetic disorders relevant to healthcare.\n\n## Gene Expression\n\nDNA replication, transcription and translation are part of gene expression.\n\n## Chemistry for Health\n\n- pH and the acid-base balance.\n- Solutions, concentrations, and dilutions used in drug administration.\n- Moles and molar solutions.\n\n## pH Scale\n\nA solution with a pH below 7 is acidic; above 7 is alkaline; 7 is neutral.`,
    sk_codes: ["SK17"],
    performance_outcomes: ["PO8"],
    references: ["T Level Health Specification — Core Paper 2, Area 8", "Clinical Skills.net: Biochemistry Fundamentals"],
    estimated_duration: 10,
    order_index: 24,
    knowledge_checks: [
      { question: "DNA replication, transcription and translation are part of:", options: ["Gene expression", "Digestion", "Respiration", "Photosynthesis"], correct: "Gene expression" },
      { question: "Mendelian inheritance describes:", options: ["Patterns of genetic inheritance", "Digestion", "Cell division only", "Evolution"], correct: "Patterns of genetic inheritance" },
      { question: "A solution with a pH below 7 is:", options: ["Acidic", "Alkaline", "Neutral", "Buffered"], correct: "Acidic" },
      { question: "A mole is a measure of:", options: ["Amount of substance", "Volume", "Length", "Temperature"], correct: "Amount of substance" },
      { question: "DNA has a structure described as a:", options: ["Double helix", "Single strand", "Triple helix", "Flat sheet"], correct: "Double helix" },
      { question: "Transcription produces:", options: ["RNA from DNA", "Protein from RNA", "DNA from RNA", "Lipids from glucose"], correct: "RNA from DNA" },
      { question: "Translation produces:", options: ["Protein from RNA", "RNA from DNA", "DNA from RNA", "Glycogen from glucose"], correct: "Protein from RNA" },
      { question: "A neutral solution has a pH of:", options: ["0", "7", "14", "1"], correct: "7" },
      { question: "Drug dilutions in clinical practice rely on understanding:", options: ["Concentrations and ratios", "Cell theory", "Mendelian genetics", "Enzyme kinetics"], correct: "Concentrations and ratios" },
      { question: "A molar solution expresses concentration in:", options: ["Moles per litre", "Grams per metre", "Litres per mole", "Degrees per litre"], correct: "Moles per litre" },
    ],
  },
];