// Area 2 — Health, Safety & Environmental Regulations (3 sub-modules)

export const AREA2_MODULES = [
  {
    title: "Key Health & Safety Legislation",
    spec_area: "Area 2",
    volume: "Core Paper 1",
    section: "Core Area 2.1 — Health & Safety Legislation",
    content: `## Key Legislation\n\n- **Health and Safety at Work Act 1974 (HASAWA):** Employers must provide a safe working environment; employees must take reasonable care of their own and others' safety.\n- **Manual Handling Operations Regulations 1992:** Risk reduction for repositioning individuals or transferring stock (hierarchy: avoid, assess, reduce).\n- **Control of Substances Hazardous to Health (COSHH) 2002:** Safe management and exposure limitation for hazardous cleaning agents, medications, or clinical waste.\n- **Reporting of Injuries, Diseases and Dangerous Occurrences Regulations (RIDDOR) 2013:** Systematic reporting of serious workplace accidents, occupational illnesses, or equipment failures to the HSE.\n- **Provision and Use of Work Equipment Regulations (PUWER) 1998:** Safe use and maintenance of work equipment.\n- **Management of Health and Safety at Work Regulations 1999:** requires employers to carry out risk assessments.\n\n## Employer vs Employee Duties\n\nEmployers must protect health, safety and welfare at work. Employees must take reasonable care, cooperate with the employer, and not interfere with safety provisions.`,
    sk_codes: ["SK7", "SK18"],
    performance_outcomes: ["PO2", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 2", "HASAWA 1974", "HSE: COSHH & RIDDOR"],
    estimated_duration: 12,
    order_index: 4,
    knowledge_checks: [
      { question: "Which Act places a duty on employers to ensure a safe working environment?", options: ["HASAWA 1974", "COSHH 2002", "RIDDOR 2013", "PUWER 1998"], correct: "HASAWA 1974" },
      { question: "RIDDOR 2013 requires reporting of:", options: ["All near misses only", "Serious accidents, diseases and dangerous occurrences", "Staff holidays", "Patient complaints"], correct: "Serious accidents, diseases and dangerous occurrences" },
      { question: "COSHH 2002 relates to:", options: ["Manual handling", "Substances hazardous to health", "Work equipment", "Fire safety"], correct: "Substances hazardous to health" },
      { question: "Which regulation governs safe use and maintenance of work equipment?", options: ["PUWER 1998", "RIDDOR 2013", "COSHH 2002", "HASAWA 1974"], correct: "PUWER 1998" },
      { question: "Who enforces RIDDOR reporting?", options: ["CQC", "HSE", "NMC", "GMC"], correct: "HSE" },
      { question: "Under HASAWA, employees must:", options: ["Take reasonable care of their own and others' safety", "Ignore hazards not in their job description", "Only work when supervised", "Provide their own PPE"], correct: "Take reasonable care of their own and others' safety" },
      { question: "The Management of Health and Safety at Work Regulations 1999 require employers to:", options: ["Pay hazard pay", "Carry out risk assessments", "Provide free meals", "Limit shifts to 4 hours"], correct: "Carry out risk assessments" },
      { question: "The correct manual handling hierarchy is:", options: ["Reduce, Avoid, Assess", "Avoid, Assess, Reduce", "Assess, Avoid, Reduce", "Reduce, Assess, Avoid"], correct: "Avoid, Assess, Reduce" },
      { question: "PUWER 1998 requires work equipment to be:", options: ["Suitable, maintained and inspected", "Imported cheaply", "Operated without training", "Shared by all staff at once"], correct: "Suitable, maintained and inspected" },
      { question: "RIDDOR reports are submitted to the:", options: ["HSE", "CQC", "NMC", "Local MP"], correct: "HSE" },
    ],
  },
  {
    title: "Risk Assessment & Clinical Governance",
    spec_area: "Area 2",
    volume: "Core Paper 1",
    section: "Core Area 2.2 — Risk Assessment & Governance",
    content: `## Risk Assessment\n\nFive steps: identify hazards; decide who might be harmed and how; evaluate risks and implement controls; record findings; review and update. **Risk = Likelihood × Severity.**\n\nA **dynamic risk assessment** is a continuous, on-the-spot assessment carried out in real time — for example before approaching an agitated patient.\n\n## Clinical Governance\n\nA system through which NHS organisations are accountable for continuously improving the quality of services. Key pillars: risk management, clinical audit, evidence-based practice, patient involvement, staffing, education, and clinical effectiveness.\n\n## Clinical Audit\n\nClinical audit compares current practice against agreed standards, identifies gaps, and implements change. It is a core component of clinical governance and quality improvement.`,
    sk_codes: ["SK7", "SK18"],
    performance_outcomes: ["PO2", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 2", "HSE: Risk Assessment", "NHS England: Clinical Governance"],
    estimated_duration: 10,
    order_index: 5,
    knowledge_checks: [
      { question: "What is the formula for risk?", options: ["Likelihood + Severity", "Likelihood × Severity", "Likelihood ÷ Severity", "Severity − Likelihood"], correct: "Likelihood × Severity" },
      { question: "How many steps are in the HSE risk assessment process?", options: ["3", "4", "5", "7"], correct: "5" },
      { question: "Clinical governance is primarily about:", options: ["Maximising profit", "Continuous quality improvement", "Reducing staff numbers", "Private partnerships"], correct: "Continuous quality improvement" },
      { question: "Which is NOT a pillar of clinical governance?", options: ["Clinical audit", "Risk management", "Marketing", "Evidence-based practice"], correct: "Marketing" },
      { question: "Clinical audit compares practice against:", options: ["Agreed standards", "Random opinions", "Last year's budget", "Social media"], correct: "Agreed standards" },
      { question: "Clinical audit is a component of:", options: ["Clinical governance", "RIDDOR", "COSHH", "Manual handling"], correct: "Clinical governance" },
      { question: "A dynamic risk assessment is:", options: ["A one-off written assessment", "A continuous on-the-spot assessment", "An annual audit", "A financial review"], correct: "A continuous on-the-spot assessment" },
      { question: "The first step of a risk assessment is to:", options: ["Identify hazards", "Record findings", "Implement controls", "Review yearly"], correct: "Identify hazards" },
      { question: "Risk management is a pillar of:", options: ["Clinical governance", "COSHH", "PUWER", "RIDDOR"], correct: "Clinical governance" },
      { question: "Evidence-based practice is part of:", options: ["Clinical governance", "Manual handling law", "RIDDOR", "COSHH"], correct: "Clinical governance" },
    ],
  },
  {
    title: "Environmental Practice & Infection Control Law",
    spec_area: "Area 2",
    volume: "Core Paper 1",
    section: "Core Area 2.3 — Environmental & Infection Control",
    content: `## Environmental Considerations\n\n- Safe disposal of clinical waste (sharps, pharmaceutical, infectious waste streams).\n- Sustainability and environmental impact of healthcare practice.\n\n### Waste Streams\n- **Sharps** → sharps bin.\n- **Infectious clinical waste** → orange/yellow bag.\n- **Pharmaceutical waste** → yellow pharmaceutical waste stream.\n- **Domestic waste** → black bag.\n\n## Infection Control Legislation\n\n- **Health and Social Care Act 2008:** Code of Practice on infection prevention.\n- The Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 set out requirements for registered providers.\n\n## Sustainability\n\nHealthcare has a significant environmental footprint. Staff contribute by reducing waste, segregating streams correctly, switching off equipment, and following sustainable procurement.`,
    sk_codes: ["SK7", "SK18"],
    performance_outcomes: ["PO2", "PO10"],
    references: ["T Level Health Specification — Core Paper 1, Area 2", "Health and Social Care Act 2008", "HSE: Clinical Waste"],
    estimated_duration: 10,
    order_index: 6,
    knowledge_checks: [
      { question: "Sharps should be disposed of in:", options: ["Yellow clinical waste bag", "Black domestic bin", "Sharps bin", "Cardboard box"], correct: "Sharps bin" },
      { question: "Pharmaceutical waste is disposed of via:", options: ["Black bag", "Sharps bin", "Yellow pharmaceutical waste stream", "Down the sink"], correct: "Yellow pharmaceutical waste stream" },
      { question: "Which Act includes a Code of Practice on infection prevention?", options: ["Health and Social Care Act 2008", "HASAWA 1974", "Equality Act 2010", "Care Act 2014"], correct: "Health and Social Care Act 2008" },
      { question: "Infectious clinical waste is typically colour-coded:", options: ["Black", "Orange/yellow", "Clear", "Blue"], correct: "Orange/yellow" },
      { question: "Domestic waste goes in a:", options: ["Black bag", "Sharps bin", "Orange bag", "Yellow bin"], correct: "Black bag" },
      { question: "Sustainability in healthcare practice relates to which area?", options: ["Area 1", "Area 2", "Area 8", "Area 9"], correct: "Area 2" },
      { question: "The Regulated Activities Regulations 2014 apply to:", options: ["Registered providers", "Patients only", "Visitors only", "Catering staff only"], correct: "Registered providers" },
      { question: "Correct waste segregation protects:", options: ["Staff, public and the environment", "Only the patient", "Only the cleaner", "Hospital finances"], correct: "Staff, public and the environment" },
      { question: "Switching off unused equipment supports:", options: ["Sustainability", "Infection rates", "Manual handling", "RIDDOR"], correct: "Sustainability" },
      { question: "The environmental footprint of healthcare can be reduced by:", options: ["Correct waste segregation", "Burning waste", "Mixing waste streams", "Using more single-use plastics"], correct: "Correct waste segregation" },
    ],
  },
];