// Area 4 — Good Scientific & Clinical Practice (3 sub-modules)

export const AREA4_MODULES = [
  {
    title: "Professional Values, the 6 Cs & the NMC Code",
    spec_area: "Area 4",
    volume: "Core Paper 1",
    section: "Core Area 4.1 — Professional Values",
    content: `## The 6 Cs (NHS Compassion in Practice)\n\nCare, Compassion, Competence, Communication, Courage, Commitment.\n\n## The NMC Code\n\nFour priorities:\n1. Prioritise people.\n2. Practise effectively.\n3. Preserve safety.\n4. Promote professionalism and trust.\n\n## Accountability & Duty of Candour\n\n- **Accountability:** professionals are answerable for their acts and omissions.\n- **Duty of candour:** be open and honest when things go wrong — apologise, explain, and take action.\n\n## Standard Operating Procedures (SOPs)\n\nWritten instructions to ensure consistent, safe, repeatable clinical and laboratory procedures.`,
    sk_codes: ["SK1", "SK16", "SK18"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 4", "NMC Code", "NHS England: The 6 Cs"],
    estimated_duration: 10,
    order_index: 10,
    knowledge_checks: [
      { question: "How many of the '6 Cs' are there in NHS practice?", options: ["4", "5", "6", "7"], correct: "6" },
      { question: "Which is NOT one of the 6 Cs?", options: ["Care", "Compassion", "Competition", "Courage"], correct: "Competition" },
      { question: "The NMC Code priority 'practise effectively' means:", options: ["Work alone always", "Use best available evidence", "Avoid documentation", "Prioritise speed over safety"], correct: "Use best available evidence" },
      { question: "Which is a professional value in the NMC Code?", options: ["Promote professionalism and trust", "Maximise profit", "Avoid teamwork", "Skip documentation"], correct: "Promote professionalism and trust" },
      { question: "Duty of candour requires clinicians to:", options: ["Be open and honest when things go wrong", "Avoid patients", "Work silently", "Refuse to document errors"], correct: "Be open and honest when things go wrong" },
      { question: "An SOP is:", options: ["A standard operating procedure", "A specialist out-patient", "A safety override protocol", "A statistical outcome profile"], correct: "A standard operating procedure" },
      { question: "Accountability means a professional is:", options: ["Answerable for their acts and omissions", "Exempt from documentation", "Free to ignore policy", "Unsupervised always"], correct: "Answerable for their acts and omissions" },
      { question: "Competence in the 6 Cs refers to:", options: ["Having the skills and knowledge to deliver care", "Competition between staff", "Completing tasks quickly", "Computer literacy only"], correct: "Having the skills and knowledge to deliver care" },
      { question: "The 6 Cs were introduced through:", options: ["Compassion in Practice", "COSHH", "RIDDOR", "The Care Act"], correct: "Compassion in Practice" },
      { question: "SOPs ensure procedures are:", options: ["Consistent, safe and repeatable", "Secret", "Unwritten", "Optional"], correct: "Consistent, safe and repeatable" },
    ],
  },
  {
    title: "Evidence-Based Practice & Quality Improvement",
    spec_area: "Area 4",
    volume: "Core Paper 1",
    section: "Core Area 4.2 — Evidence & Quality",
    content: `## Evidence-Based Practice\n\nIntegrating best available research evidence, clinical expertise, and patient values.\n\n### Hierarchy of Evidence\n\nSystematic reviews/meta-analyses > RCTs > cohort studies > case-control > expert opinion.\n\n- Using guidelines (NICE) and clinical standards to inform practice.\n\n## Quality Improvement\n\n- **Plan-Do-Study-Act (PDSA)** cycles.\n- **Clinical audit:** comparing practice against agreed standards and implementing change.\n- **Reflective practice** to support continuous professional development (CPD).`,
    sk_codes: ["SK1", "SK16", "SK18"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 4", "NICE Evidence Standards"],
    estimated_duration: 10,
    order_index: 11,
    knowledge_checks: [
      { question: "Evidence-based practice integrates research evidence, clinical expertise and:", options: ["Patient values", "Cost", "Hospital policy alone", "Tradition"], correct: "Patient values" },
      { question: "Which sits at the top of the hierarchy of evidence?", options: ["Expert opinion", "Case study", "Systematic review/meta-analysis", "Anecdote"], correct: "Systematic review/meta-analysis" },
      { question: "PDSA stands for:", options: ["Plan-Do-Study-Act", "Predict-Do-Stop-Assess", "Plan-Document-Share-Audit", "Prepare-Do-Standardise-Assure"], correct: "Plan-Do-Study-Act" },
      { question: "Clinical audit compares practice against:", options: ["Agreed standards", "Random opinions", "Last year's budget", "Social media"], correct: "Agreed standards" },
      { question: "Which organisation publishes clinical guidelines in England?", options: ["NICE", "CQC", "HMRC", "DVLA"], correct: "NICE" },
      { question: "Reflective practice supports:", options: ["Continuous professional development", "Avoiding work", "Hiding mistakes", "Reducing hours"], correct: "Continuous professional development" },
      { question: "A randomised controlled trial (RCT) sits where in the evidence hierarchy?", options: ["Above cohort studies", "Below expert opinion", "At the very bottom", "Outside the hierarchy"], correct: "Above cohort studies" },
      { question: "A PDSA cycle is a method of:", options: ["Quality improvement", "Waste disposal", "Manual handling", "Drug calculation"], correct: "Quality improvement" },
      { question: "Expert opinion sits where in the evidence hierarchy?", options: ["Near the bottom", "At the top", "Above RCTs", "Outside the hierarchy entirely"], correct: "Near the bottom" },
      { question: "NICE guidelines are used to:", options: ["Inform evidence-based practice", "Replace clinical judgement entirely", "Set staff salaries", "Schedule surgery"], correct: "Inform evidence-based practice" },
    ],
  },
  {
    title: "Clinical Skills, Medication Safety & Scientific Practice",
    spec_area: "Area 4",
    volume: "Core Paper 1",
    section: "Core Area 4.3 — Clinical & Scientific Skills",
    content: `## Clinical Skills & Observations\n\n- Accurate measurement and recording of vital signs (NEWS2).\n- Aseptic non-touch technique (ANTT) for invasive procedures.\n- Safe administration of medicines using the 'rights': right patient, drug, dose, route, time, documentation.\n\n## Laboratory & Scientific Practice\n\n- Health and safety in laboratory settings.\n- Use of standardised equipment and calibrated instruments.\n- Accurate measurement, recording and reporting of results.\n- Documentation and traceability of samples and results.\n\n## Calibration & Traceability\n\nA calibrated instrument is set against a known standard. Traceability means samples and results can be tracked through every stage of processing.`,
    sk_codes: ["SK1", "SK16", "SK18"],
    performance_outcomes: ["PO4", "PO9"],
    references: ["T Level Health Specification — Core Paper 1, Area 4", "ANTT: Aseptic Non-Touch Technique"],
    estimated_duration: 10,
    order_index: 12,
    knowledge_checks: [
      { question: "ANTT stands for:", options: ["Aseptic Non-Touch Technique", "Aseptic Nursing Treatment Tool", "Assessment of Need and Treatment", "Antibiotic Non-Tolerant Test"], correct: "Aseptic Non-Touch Technique" },
      { question: "Which is one of the 'rights' of medication administration?", options: ["Right patient", "Right ward", "Right colour", "Right mood"], correct: "Right patient" },
      { question: "Which is a vital sign measured in NEWS2?", options: ["Respiratory rate", "Blood glucose only", "Height", "Weight"], correct: "Respiratory rate" },
      { question: "A calibrated instrument is one that:", options: ["Is set against a known standard", "Is brand new", "Is disposable", "Requires no maintenance"], correct: "Is set against a known standard" },
      { question: "Traceability of samples means:", options: ["Samples can be tracked through every stage", "Samples are destroyed immediately", "Samples are shared publicly", "Samples are unlabelled"], correct: "Samples can be tracked through every stage" },
      { question: "The 'right documentation' in medicines administration refers to:", options: ["Recording the drug, dose, time, route and signer", "Recording only the patient name", "No recording needed", "Recording in pencil"], correct: "Recording the drug, dose, time, route and signer" },
      { question: "How many 'rights' of medication administration are commonly cited?", options: ["3", "5", "6", "10"], correct: "6" },
      { question: "ANTT is used for:", options: ["Invasive procedures", "Ward cleaning", "Staff rotas", "Meal planning"], correct: "Invasive procedures" },
      { question: "Accurate measurement and recording of results is part of:", options: ["Good scientific practice", "Marketing", "Catering", "Finance"], correct: "Good scientific practice" },
      { question: "Laboratory health and safety is governed by:", options: ["HASAWA and COSHH", "The Care Act alone", "The Equality Act", "The Mental Capacity Act"], correct: "HASAWA and COSHH" },
    ],
  },
];